close #4 走行距離を算出する
KatLab-MiyazakiUniv/etrobocon2023 pull request #10
Opened 2023-05-18 03:55 UTC by desty505

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
etrobocon2023/moduleの直下にCalculatorフォルダ(etrobocon2023/module/Calculator/)を作成し、
そこに以下の2つのファイルを追加しました
- Mileage.h
- Mileage.cpp

etrobocon2023/testに以下のファイルをテストコードとして追加しました
- MileageTest.cpp

etrobocon2023/のCMakeLists.txtに以下の参照先を追加しました

- include_directories(${PROJECT_SOURCE_DIR}/module/Calculator)
- ${PROJECT_SOURCE_DIR}/module/*/*.cpp

# 動作テスト
MileageTest.cppを通ることを確認しました

2023-05-19 10:51 UTC, miyashita64 requested changes
細かいところだけ

2023-05-19 10:51 UTC, miyashita64 commented on CMakeLists.txt
> +  ${PROJECT_SOURCE_DIR}/module/*/*.cpp
```suggestion
  ${PROJECT_SOURCE_DIR}/module/Calculator/*.cpp
```
の方が安全かな

2023-05-19 10:51 UTC, miyashita64 commented on module/Calculator/Mileage.cpp
> + **  @author TanakaShinnosuke
一意な方のユーザ名に合わせたいから、desty505の方がいいかな

2023-05-19 10:51 UTC, miyashita64 commented on module/Calculator/Mileage.cpp
> +  double rightWheel = calculateWheelMileage(rightAngle);
```suggestion
  double rightWheelMileage = calculateWheelMileage(rightAngle);
```
の方が適切かも。長いけど。

2023-05-19 10:51 UTC, miyashita64 commented on module/Calculator/Mileage.h
> + **  @author TanakaShinnosuke
ここも

2023-05-19 10:51 UTC, miyashita64 commented on test/MileageTest.cpp
> + * @author TanakaShinnosuke
ここも

2023-05-19 10:51 UTC, miyashita64 commented on test/MileageTest.cpp
> +    double rightWheel = 2 * rightAngle * radius * M_PI / 360;
```suggestion
    double rightWheelMilage = 2 * rightAngle * radius * M_PI / 360;
```
かな？気に入らなければ無視してもいいです。

2023-05-20 12:17 UTC, KakinokiKanta requested changes
いくつか修正お願いします

2023-05-20 12:17 UTC, KakinokiKanta commented on module/Calculator/Mileage.cpp
> +  //タイヤの累計走行距離＝2 * π * タイヤの半径　* (タイヤの回転角度 / 360[deg])
```suggestion
  // タイヤの累計走行距離 ＝ 2 * π * タイヤの半径　* (タイヤの回転角度 / 360[deg])
```
できれば…

2023-05-20 12:17 UTC, KakinokiKanta commented on test/MileageTest.cpp
> +namespace etrobocon2022_test {
```suggestion
namespace etrobocon2023_test {
```
2023だね

2023-05-20 12:17 UTC, KakinokiKanta commented on test/MileageTest.cpp
> +}  // namespace etrobocon2022_test
```suggestion
}  // namespace etrobocon2023_test
```
ここも

2023-05-20 12:17 UTC, KakinokiKanta commented on test/MileageTest.cpp
> +  TEST(MileageTest, calculateMileage_minus)
```suggestion
  TEST(MileageTest, calculateMileageMinus)
```
コーディング規約に書いてなかったと思うんだけど、テスト名にはアンダースコア(_)を使わないようにしてほしい。理由は、宮下さんが勉強会で説明してた通りなんだけど、詳しくは下記参照。
https://qiita.com/hashitaku/items/814fa7641fdec8694d5f

2023-05-20 12:17 UTC, KakinokiKanta commented on test/MileageTest.cpp
> +  TEST(MileageTest, calculateMileage_zero)
```suggestion
  TEST(MileageTest, calculateMileageZero)
```
ここも

2023-05-21 02:50 UTC, kawanoichi approved these changes
レビュー遅くなってすみません。
見た感じ問題ないかと思います。
![103115](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/7a3702f8-ca2b-4485-915b-9828359e0918)

2023-05-21 04:20 UTC, bizyutyu requested changes, later dismissed

2023-05-21 04:20 UTC, bizyutyu commented on test/MileageTest.cpp
> +    double leftWheelMileage = 2 * leftAngle * radius * M_PI / 360;
この部分の2と360についてなのですが、Mileage.cppでは2.0と360.0を用いて計算しているので、処理に問題はなくても、どちらか一方に統一したほうが良いのではないのではないかと。
他のところについてもお願いします。

2023-05-21 04:20 UTC, bizyutyu commented on test/MileageTest.cpp
> +    double leftWheelMileage = 2 * leftAngle * radius * M_PI / 360;
ここも同様に

2023-05-21 04:20 UTC, bizyutyu commented on test/MileageTest.cpp
> +    double leftWheelMileage = 2 * leftAngle * radius * M_PI / 360;
ここも同様に

2023-05-21 06:23 UTC, miyashita64 requested changes
@fn見落としてた

2023-05-21 06:23 UTC, miyashita64 commented on module/Calculator/Mileage.h
> +  ** @fn double calculateWheelMileage(int angle);
@fnの行は消して欲しいです。

2023-05-21 06:23 UTC, miyashita64 commented on module/Calculator/Mileage.h
> +   ** @fn　double calculateMileage(int rightAngle, int leftAngle);
ここも

2023-05-21 13:37 UTC, bizyutyu reviewed
自分のRequest changeについての修正箇所についてはOKです。

2023-05-21 16:31 UTC, KakinokiKanta requested changes
追加でちょっとだけ

2023-05-21 16:31 UTC, KakinokiKanta commented on module/Calculator/Mileage.h
> + **/
```suggestion
 **  @author desty505
```
コンフリクトの解消とかするときにも出てくると思うんだけど、この辺は普通に消しちゃって良いよ

2023-05-21 16:31 UTC, KakinokiKanta commented on module/Calculator/Mileage.h
> +>>>>>>> work-4
```suggestion
```
宮下さんからの指摘もあるからここは全部消して良いよ

2023-05-22 01:55 UTC, KakinokiKanta approved these changes
LGTM!!

2023-05-22 01:58 UTC, miyashita64 commented
LGTM!!
![LGTM](https://image.lgtmoon.dev/209307)

2023-05-22 01:59 UTC, miyashita64 approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/209307)

2023-05-22 02:53 UTC, merged