add: 試行錯誤
KatLab-MiyazakiUniv/etrobocon2023 pull request #100
Opened 2023-08-19 16:16 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-09-03 03:25 UTC, miyashita64 requested changes
めっちゃ今更かもしれんが、直接PWM値をいじるControllerがPWM値を管理(メンバとして保持)する方が確実だと思った。Controller自体がstaticだし。

それと、ミーティングで決まったのかもしれんけど、PWM値指定の回頭を実装するなら、回頭用のPWM値っていつ使うの？

2023-09-03 03:25 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.cpp
> +  ManagePwm::updateRightPwm(rightPwm);
これライントレースできるっけ？

2023-09-03 03:25 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.h
> +  static constexpr double R_K_D = 0.0007;
Rotation用であることをコメントして欲しい。
値は、追々調整ってことだよね？

2023-09-03 03:25 UTC, miyashita64 commented on module/common/ManagePwm.cpp
> +  manageRightPwm = _inputRightPwm;
今の所、車輪モータのPWM値は上書きされないよね？
もしかしてetrobocon2023.cppのステージング抜けてる？

2023-09-03 03:25 UTC, miyashita64 commented on module/common/ManagePwm.cpp
> + * @brief 走行体の左右車輪のPWMを所持するクラス
ControllerもしくはSystemInfoでもいい気がした。

2023-09-03 04:28 UTC, miyashita64 commented
あと、プルリク名closeつけておくれ

2023-09-03 06:07 UTC, kawanoichi commented
動作テストが「確認次第更新します。」になっているけど、停止しないかどうかも分かっていない感じ？

2023-09-03 14:08 UTC, bizyutyu commented
> 動作テストが「確認次第更新します。」になっているけど、実際に停止しないかどうかも確認できていない感じ？

先程確認して、各動作のつながりスムーズになっていることは確認しました。個人的には、中々スムーズになっていると思います。
ただ、元々明確に停止が入っていたわけではないので、機会があったら他の人にも確認してもらいたい感じです。

2023-09-03 18:29 UTC, miyashita64 commented on module/common/ManagePwm.cpp
> +  manageRightPwm = _inputRightPwm;
ごめんわかった。
SpeedCalculatorの初期値にだけ影響してるんか。

2023-09-04 02:31 UTC, aridome222 approved these changes
一通り見た感じ問題ないと思います。
![LGTM](https://image.lgtmoon.dev/102908)

2023-09-04 15:23 UTC, KakinokiKanta approved these changes
レビューが遅くなって申し訳ない。
いくつか質問に回答するか、変更してほしい。

2023-09-04 15:23 UTC, KakinokiKanta commented on module/common/ManagePwm.cpp
> +double ManagePwm::manageLeftPwm = 0.0;
ここの初期化ってヘッダ側でできない?
後、インスタンス化を禁止しているなら、明示的にしてほしい

2023-09-04 15:23 UTC, KakinokiKanta commented on module/common/ManagePwm.h
> + public:
```suggestion
 public:
  ManagePwm() = delete;  // 明示的にインスタンス化を禁止
```
ここで明示的にインスタンス化を禁止してほしい

2023-09-04 15:23 UTC, KakinokiKanta commented on module/common/ManagePwm.h
> +  static double manageLeftPwm;   // 左車輪PWM
```suggestion
  static double manageRightPwm = 0.0;  // 右車輪PWM
  static double manageLeftPwm = 0.0;   // 左車輪PWM
```
こういう初期化ってできないんだっけ?

2023-09-05 04:50 UTC, bizyutyu commented on module/common/ManagePwm.h
> +  static double manageLeftPwm;   // 左車輪PWM
C++では、static変数はヘッダ側で宣言出来るけど、明示的な初期化はできないみたい。（コンパイルエラーになる）
暗黙的に0に初期化されている様だけど。
- [https://skpme.com/633/](url)
- [https://learn.microsoft.com/ja-jp/cpp/cpp/initializers?view=msvc-170](url)

2023-09-05 07:48 UTC, YKhm20020 reviewed
不要な気もしますが一応出しました。他は大丈夫だと思いますので、確認次第LGTM出します。

2023-09-05 07:48 UTC, molpui0726 commented on module/Motion/LineTracing.cpp
> +  double turnPwm = 0;     // 旋回値を計算
```suggestion
  double turnPwm = 0.0;     // 旋回値を計算
```
影響はないとは思いますが、double 型の Distance 2つと、Straight.h の MIN_PWM に合わせるなら小数点までになります。

2023-09-05 07:48 UTC, molpui0726 commented on module/Motion/Straight.cpp
> +  double currentRightPwm = 0;  // 現在の右タイヤpwd値
```suggestion
  double currentLeftPwm = 0.0;   // 現在の左タイヤpwd値
  double currentRightPwm = 0.0;  // 現在の右タイヤpwd値
```
ここも同様です。

2023-09-05 07:48 UTC, YKhm20020 commented on module/Calculator/SpeedCalculator.h
> +  // 回頭用PIDゲイン
```suggestion
  // 回頭用PIDゲイン
  // TODO: 追々調整予定
```
調整予定であれば、その旨を記述するとより安全かと思いました。

2023-09-05 08:36 UTC, miyashita64 approved these changes
LGTM！！
![LGTM](https://image.lgtmoon.dev/139948)

2023-09-06 04:59 UTC, YKhm20020 approved these changes
![200607](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/2c2ecc32-03cb-4e82-a264-ade73bcfe967)
LGTMです、お疲れ様でした！

2023-09-06 10:09 UTC, merged