close #103 Pwm指定回頭動作の作成
KatLab-MiyazakiUniv/etrobocon2023 pull request #104
Opened 2023-09-02 02:22 UTC by Negimarge

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
PwmRotation.cpp, PwmRotation.h, PwmRotationTest.cppの追加

# 動作テスト
gテスト動作済み

2023-09-03 03:05 UTC, miyashita64 reviewed
コードは特に問題ないと思います。
実機で動くかだけ確認したい。

2023-09-03 04:30 UTC, Negimarge commented
https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/117429880/f7441df6-3ce5-4d15-974d-b57582131360


それぞれ、pwm値40,50,60,70,80,90,100で左右に回頭したものです

2023-09-03 05:02 UTC, kodama0720 approved these changes
LGTM!

2023-09-03 06:04 UTC, kawanoichi requested changes
コメントが一つだけ抜けていました。
他はいいと思います

2023-09-03 06:04 UTC, kawanoichi commented on module/MotionParser.cpp
> +  } else if(strcmp(str, "PR") == 0) {
```suggestion
  } else if(strcmp(str, "PR") == 0) {  // 文字列がPRの場合
```

2023-09-03 18:34 UTC, miyashita64 approved these changes
動画ありがとう！
![LGTM](https://image.lgtmoon.dev/82328)

2023-09-04 01:11 UTC, aridome222 requested changes
1つだけ修正お願いします。

2023-09-04 01:11 UTC, aridome222 commented on test/test_data/CommandParserTestData.csv
> +PR,90,90,clockwise,Pwd値指定回頭
```suggestion
PR,90,90,clockwise,Pwm値指定回頭
```
スペルミス

2023-09-04 02:38 UTC, YKhm20020 reviewed
コメントのところ一箇所だけですが。それ以外は大丈夫だと思います。

2023-09-04 02:38 UTC, YKhm20020 commented on module/Motion/PwmRotation.h
> + * @file   Rotation.h
```suggestion
 * @file   PwmRotation.h
```
コメントですが。.cppの方と合わせるとこう。

2023-09-04 04:37 UTC, kawanoichi approved these changes
![193885](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/c0d9496b-bf56-4a97-9517-4873836bd2f1)

2023-09-04 15:25 UTC, KakinokiKanta requested changes
ばっちりです!実機での動作確認までありがとう!!
![LGTM](https://image.lgtmoon.dev/221052)

2023-09-04 15:25 UTC, KakinokiKanta approved these changes

2023-09-05 06:49 UTC, aridome222 approved these changes

2023-09-05 06:50 UTC, YKhm20020 approved these changes
LGTM!!!
![207463](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/ecfd0d9b-35dd-4402-88b4-5edda58ab180)

2023-09-05 06:51 UTC, merged