close #104 フィグBの撮影動作に前進・後退動作を追加
KatLab-MiyazakiUniv/etrobocon2023 pull request #107
Opened 2023-09-03 02:39 UTC by YKhm20020

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
フィグBを撮影する際、撮影動作の前後に前進・後退の動作を追加。  
Motion 下の以下のファイルの一部を変更。

- CameraAction.h
- CameraAction.cpp

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-09-03 03:41 UTC, miyashita64 requested changes
フィグBから前進で離れて、後退で近づく流れだと思ってるけど、間違ってたらごめん。

2023-09-03 03:41 UTC, miyashita64 commented on module/Motion/CameraAction.cpp
> +  if(target == false) {
前のプルリク見逃してたけど、isAとかの方が直感的だと思う。Bにしてtrueの時にしてもいいけど。
```suggestion
  if(isA == false) {
```

2023-09-03 03:41 UTC, miyashita64 commented on module/Motion/CameraAction.cpp
author漏れ

2023-09-03 03:41 UTC, miyashita64 commented on module/Motion/CameraAction.cpp
> +  // 撮影対象がB（targetがfalse）の場合は、バックでフィグへ接近
近付くんだっけ？離れるんじゃなくて？

2023-09-03 03:41 UTC, miyashita64 commented on module/Motion/CameraAction.cpp
> +    DistanceStraight dsToLine(targetDistance, -1.0 * targetSpeed);
-targetSpeed = - (-150) = 150 で前進より、
targetSpeedが150でバックの時に-ついてる方が個人的にはわかりやすい。

2023-09-03 04:48 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/86808)

2023-09-03 05:42 UTC, kawanoichi approved these changes
LGTM！！

2023-09-03 18:41 UTC, miyashita64 approved these changes
LGTM!!
![image](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/83441177/7dc3a9f0-3e63-425a-aac0-ccfc35fa9340)

2023-09-04 00:57 UTC, aridome222 commented on module/Motion/CameraAction.cpp
>    if(postTargetAngle != 0) {
```
  // 黒線復帰のための回頭をする
  if(postTargetAngle != 0) {
```

上の方で事前条件を判定しているのに、ここでまたする必要ってあるんでしたっけ？
preTargetAngleの方も。

2023-09-04 15:43 UTC, KakinokiKanta approved these changes
レビュー遅くなった...
アリドメくんのやつに対応してくれれば、それ以外は問題なさそう
![LGTM](https://image.lgtmoon.dev/221054)

2023-09-04 15:43 UTC, KakinokiKanta commented on module/Motion/CameraAction.cpp
>    if(postTargetAngle != 0) {
確かにいらないかも...

2023-09-05 06:42 UTC, bizyutyu approved these changes
お疲れ様です。
![LGTM](https://image.lgtmoon.dev/179306)

2023-09-06 10:07 UTC, merged