#close LAPゲートまでの調整
KatLab-MiyazakiUniv/etrobocon2023 pull request #109
Opened 2023-09-09 08:43 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-09-18 07:49 UTC, kodama0720 requested changes

2023-09-18 07:49 UTC, kodama0720 commented on module/API/Measurer.h
> +  static void updateManageBrightness(const int brightness);
setManageBrightnessにした方が、セッターゲッターが分かりやすいと思う
あと、Measurerにはゲッターしか書かないかと思ったけど、別のクラス作るほどでもないか

2023-09-18 11:56 UTC, KakinokiKanta requested changes
特に問題はなさそうです。コメントの書き方で1か所指摘してますけど、正直どっちでも大丈夫です。

2023-09-18 11:56 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * 管理用輝度をセット（原則キャリブレーション時しか使わない）
```suggestion
   * 管理用輝度をセット
   * @note 原則キャリブレーション時しか使わない
```
の方が個人的には好み

2023-09-18 14:11 UTC, miyashita64 requested changes
SpeedCalculatorかのフラグより偏差の初期値を渡せばきれいにできそう。
やりたいこと履き違えてたらごめん

2023-09-18 14:11 UTC, miyashita64 commented on module/Calculator/Pid.cpp
> +    preDeviation(_isSpeedCalculator ? 0 : _targetValue - double(Measurer::getManageBrightness())),
```suggestion
Pid::Pid(double _kp, double _ki, double _kd, double _targetValue, double _initialDeviation)
  : gain(_kp, _ki, _kd),
    preDeviation(_initialDeviation),
```
遅いかもしれけど、偏差の初期値渡せば、Mesuarerに値持たせる必要なくて綺麗にできそう

2023-09-18 14:11 UTC, miyashita64 commented on module/Calculator/Pid.h
> +  Pid(double _kp, double _ki, double _kd, double _targetValue, bool _isSpeedCalculator = true);
```suggestion
  Pid(double _kp, double _ki, double _kd, double _targetValue, double _initialDeviation = 0.0);
```

2023-09-18 14:11 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
> +  Pid pid(gain.kp, gain.ki, gain.kd, targetBrightness, false);
```suggestion
  Pid pid(gain.kp, gain.ki, gain.kd, targetBrightness, Measurer::getBrightness());
```

2023-09-18 15:18 UTC, bizyutyu commented on module/Calculator/Pid.cpp
> +    preDeviation(_isSpeedCalculator ? 0 : _targetValue - double(Measurer::getManageBrightness())),
回答になっていないかも知れませんが、偏差の初期値を求めるために、前回取得した輝度をどこかが持っておく必要がある気がします（ライントレースの場合）。

2023-09-18 17:37 UTC, miyashita64 commented on module/Calculator/Pid.cpp
> +    preDeviation(_isSpeedCalculator ? 0 : _targetValue - double(Measurer::getManageBrightness())),
なるほど。失礼。Mesuarerについては大丈夫です。
ただ、PIDクラスに渡す値としては、SpeedCalculatorから呼び出されているか、より、メンバ(偏差)の初期値を渡す方がいいと思う。

2023-09-18 17:38 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
> +  Pid pid(gain.kp, gain.ki, gain.kd, targetBrightness, false);
```suggestion
  Pid pid(gain.kp, gain.ki, gain.kd, targetBrightness, targetBrightness - Measurer::getBrightness());
```
こうか...

2023-09-18 18:46 UTC, aridome222 approved these changes
他の方のご指摘を修正して頂ければ、見た感じ大丈夫だと思います。
![LGTM](https://image.lgtmoon.dev/187465)

2023-09-18 19:18 UTC, Negimarge approved these changes
PIDの引数だけどちらかに決めれば
LGTM

2023-09-19 00:24 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/20644)

2023-09-19 04:27 UTC, miyashita64 approved these changes
お疲れ様！
![LGTM](https://image.lgtmoon.dev/212177)

2023-09-19 07:10 UTC, KakinokiKanta approved these changes
LGTM

2023-09-19 08:07 UTC, merged