close #112 画像のファイル名を指定
KatLab-MiyazakiUniv/etrobocon2023 pull request #116
Opened 2023-09-15 10:34 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-09-17 08:19 UTC, miyashita64 reviewed
処理的に引っかかるとこはなかったです。
すごく細々したことだけ。

2023-09-17 08:19 UTC, miyashita64 commented on rear_camera_py/Makefile
> +	@echo "画像を取得する(画像のファイル名を指定する)"
```suggestion
	@echo "画像を撮影する(画像のファイル名を指定する)"
```
の方がはっきりしていいと思う。

2023-09-17 08:19 UTC, miyashita64 commented on rear_camera_py/src/camera_interface.py
>      # 1枚の画像を取得する
上のコメントに倣うなら、「1枚だけ画像を撮影する」？

2023-09-17 08:19 UTC, miyashita64 commented on rear_camera_py/src/camera_interface.py
> +            data_name = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
```suggestion
            date_str = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
```
の方がしっくりはくる。少なくともdata→dateかな。

2023-09-17 08:24 UTC, bizyutyu approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/173264)

2023-09-17 19:03 UTC, kawanoichi commented on rear_camera_py/src/camera_interface.py
> +            data_name = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
データファイルの名前という意味でdataを使ってた。
img_name, file_nameとかの方がいいですか？

2023-09-18 03:33 UTC, KakinokiKanta requested changes
1か所だけお願いします。

2023-09-18 03:33 UTC, KakinokiKanta commented on rear_camera_py/src/camera_interface.py
> +                        help="1秒ごとに撮影を実行する")
ここって1秒ごとに画像を取得しに行ってるんですよね？なら「1秒ごとに画像を取得する」のままでもいいんじゃないですか？

2023-09-18 06:53 UTC, kodama0720 requested changes

2023-09-18 06:53 UTC, kodama0720 commented on Makefile
> +	@echo " $$ make all"
個人的にはmake all-checkとかがいい

2023-09-18 06:53 UTC, kodama0720 commented on rear_camera_py/Makefile
> +	@echo " $$ make image SAVE_NAME=FigA_1.png"
```suggestion
	@echo " $$ make image SAVE_NAME=(画像のファイル名)"
```
がいいかな？

2023-09-18 06:53 UTC, kodama0720 commented on rear_camera_py/Makefile
> +endif
デフォルト値を設定するみたいなコメントが欲しい

2023-09-18 08:35 UTC, kawanoichi commented on rear_camera_py/src/camera_interface.py
> +                        help="1秒ごとに撮影を実行する")
個人的にどっちでもいいので @miyashita64 回答よろしく

2023-09-18 08:37 UTC, kawanoichi commented on Makefile
> +	@echo " $$ make all"
ちなみに理由きいてもいい？(好みも可)

2023-09-18 08:51 UTC, kodama0720 commented on Makefile
> +	@echo " $$ make all"
そう
ビルドとかまでやってそうに見えるかもしれない

2023-09-18 08:58 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/218689)

2023-09-18 13:14 UTC, miyashita64 commented on rear_camera_py/src/camera_interface.py
> +            data_name = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
なるほど。
そういうことなら、file_nameで.pngも含めてほしい。

2023-09-18 13:34 UTC, miyashita64 commented on rear_camera_py/src/camera_interface.py
> +                        help="1秒ごとに撮影を実行する")
変更前から取得だったみたいだし取得でいいや

2023-09-18 17:19 UTC, miyashita64 approved these changes
お疲れ様
![LGTM](https://image.lgtmoon.dev/121845)

2023-09-18 19:23 UTC, Negimarge approved these changes
LGTM

2023-09-19 07:15 UTC, KakinokiKanta approved these changes
![LGTM](https://image.lgtmoon.dev/222630)

2023-09-19 07:15 UTC, merged