close #113 撮影終了フラグを管理する
KatLab-MiyazakiUniv/etrobocon2023 pull request #117
Opened 2023-09-17 02:05 UTC by miyashita64

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
SystemInfo上で定義していた撮影終了フラグを、ファイルの有無で判断するようにした

(共有メモリやソケット通信は実装してみたものの、ロボコン環境で使用するライブラリがincludeできず、仕方なくこの形になりました)

# 動作テスト
実機ではまだです。月曜までにはやります。

2023-09-17 07:59 UTC, kawanoichi requested changes
これって"skip_camera_action.flag"があるかないかで撮影動作をskipするかどうかを判断するという認識であってますか？

サーバー関連をちゃんと把握できてないんやけど、フラグを立てるかどうかの判断はカメラシステムがすると思うんやけど、カメラシステムは setTrueSkipCameraAction()をどうやって実行するんだっけ？カメラシステム側のClient.get_robot_state()を実行するだけ？

2023-09-17 08:02 UTC, miyashita64 commented
http://走行体のIP/robot_info/camera_action_skip_flag_trueにPOSTリクエストを送って実行する

2023-09-17 08:05 UTC, kawanoichi commented
こっちも書き直さないとインスタンス化だけでそれ実行できなくない？
```
class Client:
    """走行体のサーバにリクエストを送り、ロボットの状態を取得するクラス."""

    def __init__(self, server_ip: str) -> None:
        """Clientのコンストラクタ.

        Args:
            server_ip (string): サーバのIPアドレス
        """
        self.server_ip = server_ip

    def get_robot_state(self) -> str:
        """走行体の状態を取得するために、サーバにリクエストを送る.

        Returns:
            response_text: 走行体の状態
        """
        url = f"http://{self.server_ip}/robot_info/state"
        req = urllib.request.Request(url)
        response_text = ""
```

2023-09-17 10:54 UTC, miyashita64 commented
[こちら](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/pull/29)で追加したので、レビューよろしくお願いします

2023-09-17 15:08 UTC, bizyutyu reviewed
コードに問題はないと思うのですが、質問があるので回答お願いします。

2023-09-17 15:08 UTC, bizyutyu commented on server/flask_server.py
> -    return open_data
ここを含め、元々あったread()とかwrite()関数って、iOSアプリとの通信のためにあったと思うのですが、消して大丈夫なんですかね？

2023-09-17 15:45 UTC, miyashita64 commented on server/flask_server.py
> -    return open_data
今回のイテレーションで追加されるから問題はないと思うけど。コンフリクトはどうせ起きるだろうし。
戻した方がいいかな？

2023-09-17 19:51 UTC, kawanoichi requested changes

2023-09-17 19:51 UTC, kawanoichi commented on server/flask_server.py
> +    return str(robot_info["state"])
getState()のreturnはrobot_info["state"]をstr変換してないけど何か違うんだっけ？一緒ならどちらかに合わせる？

2023-09-17 19:51 UTC, kawanoichi commented on server/flask_server.py
> + @auther  desty505 aridome222 miyashita64
```suggestion
 @author  desty505 aridome222 miyashita64
```

2023-09-18 02:34 UTC, bizyutyu commented on server/flask_server.py
> -    return open_data
他のタスクで追加されることを忘れてました。
なら、このままでも良いと思います！

2023-09-18 06:25 UTC, kodama0720 requested changes

2023-09-18 06:25 UTC, kodama0720 commented on server/flask_server.py
> +    #   - False: 撮影動作を行う
ここいらない？

2023-09-18 06:25 UTC, kodama0720 commented on server/flask_server.py
> +# '/robot_info/skip_camera_action'へのPOSTリクエストに対する操作
```suggestion
# '/robot_info/skip_camera_action_true'へのPOSTリクエストに対する操作
```

2023-09-18 11:23 UTC, bizyutyu approved these changes
お疲れ様です！
![LGTM](https://image.lgtmoon.dev/138070)

2023-09-18 12:10 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/143857)

2023-09-18 12:15 UTC, KakinokiKanta reviewed
特に問題はなさそうです。ただ、コメント残してるので対応してほしいです。

2023-09-18 12:15 UTC, KakinokiKanta commented on scripts/init_robot_info.sh
> +IP="172.20.1.1:8000"
このIPアドレスってカメラシステム(PC)のIPアドレスですかね？Bluetoothができなくてテザリングすることになった場合、変更する必要があると思うので、wikiとかに変更が必要になる部分をまとめておいてもらえると助かります。

2023-09-18 12:15 UTC, KakinokiKanta commented on scripts/set_state.sh
> +IP="172.20.1.1:8000"
ここも

2023-09-18 12:15 UTC, KakinokiKanta commented on server/flask_server.py
> +        ip = "172.20.1.1"
ここも

2023-09-18 13:07 UTC, miyashita64 commented on scripts/init_robot_info.sh
> +IP="172.20.1.1:8000"
RasPiのIPだね。
wikiの件は了解です。今週中にやります。

2023-09-18 13:25 UTC, kawanoichi requested changes

2023-09-18 13:25 UTC, kawanoichi commented on server/flask_server.py
> +def init() -> None:
```suggestion
def init() -> str:
```

2023-09-18 13:25 UTC, kawanoichi commented on server/flask_server.py
> +    """ロボットの走行情報を初期化する."""
```suggestion
    """ロボットの走行情報を初期化する.
    Return:
            robot_info(str): ロボットの状態
    """
```

2023-09-18 13:25 UTC, kawanoichi commented on server/flask_server.py
> +    """撮影動作終了フラグを立てる."""
```suggestion
def setTrueSkipCameraAction() -> str:
    """撮影動作終了フラグを立てる.
    
    Returns:
        str:  任意の値
    """
```
任意の値ならsuccessのboolの方がいい気もするけど、してないのはわざと？

2023-09-18 13:42 UTC, kawanoichi requested changes

2023-09-18 13:42 UTC, kawanoichi commented on server/flask_server.py
> +    #   - finish: 処理停止
```suggestion
    #   - finish: ゴールエリア侵入(処理停止)
```

2023-09-18 13:46 UTC, miyashita64 commented on server/flask_server.py
> +    """撮影動作終了フラグを立てる."""
bool値も"True"か"False"の文字列で返すことになるから気持ち悪いなって思ったけど、意味のない文字よりましか。
変えます。

2023-09-18 14:01 UTC, kawanoichi requested changes

2023-09-18 14:01 UTC, kawanoichi commented on scripts/init_robot_info.sh
> +
おそらく初期化かな？なんのファイルかのコメントよろしく
あと、このファイルどこで実行している？見つけきれんかった...

2023-09-18 16:44 UTC, kawanoichi commented on server/flask_server.py
> +    """撮影動作終了フラグを立てる."""
ちなみに文字列ではなくboolを返したらどうなるの？エラー？

2023-09-18 16:47 UTC, miyashita64 commented on server/flask_server.py
> +    """撮影動作終了フラグを立てる."""
エラーだね
文字列を期待しているがブーツ値が渡されましたみたいな

2023-09-18 17:04 UTC, kawanoichi requested changes
- author漏れ
- noteのコマンドに「＄」をつけてほしい

2023-09-18 17:04 UTC, kawanoichi commented on scripts/init_robot_info.sh
> +    bash init_robot_info.sh {RasPIのIP(任意)}
```suggestion
    $ bash init_robot_info.sh {RasPIのIP(任意)}
```

2023-09-18 17:24 UTC, miyashita64 commented on scripts/init_robot_info.sh
> +    bash init_robot_info.sh {RasPIのIP(任意)}
author書いてないのは誰が作ったか把握してない...
今回はコメントの追加だから書くのもどうかなと。

2023-09-18 17:46 UTC, kawanoichi approved these changes
お疲れさまでした
![222538](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/1a811430-be8b-461b-abd0-746307781645)

2023-09-18 17:49 UTC, miyashita64 commented on scripts/init_robot_info.sh
> +    bash init_robot_info.sh {RasPIのIP(任意)}
とりあえず、GitHubの履歴から最後に編集した人を含めました。

2023-09-18 19:07 UTC, Negimarge approved these changes
LGTM

2023-09-19 17:25 UTC, KakinokiKanta approved these changes
LGTM!

2023-09-20 07:18 UTC, merged