#121 テスト環境の変更
KatLab-MiyazakiUniv/etrobocon2023 pull request #126
Opened 2023-09-22 21:07 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-09-25 09:41 UTC, miyashita64 requested changes
workflowは何となく動きそうしかわからなかった。

2023-09-25 09:41 UTC, miyashita64 commented on Makefile
> +	@echo " $$ make c-all-check"
普段使い用にどっちもやるmake all-check もあると抜けなくていいと思う。

2023-09-25 09:41 UTC, miyashita64 commented on Makefile
> +	cd $(MAKEFILE_PATH)/server && python3 flask_server.py
全然文句はないんだけど、なんで上に持ってきたの？

2023-09-25 09:41 UTC, miyashita64 commented on rear_camera_py/Makefile
>  	rm -rf image_data/
画像取得関連よりは、キャリブレーションに近い？

2023-09-25 10:47 UTC, kawanoichi commented on Makefile
> +	@echo " $$ make c-all-check"
helpに合わせたつもりだったけど、できてないね。
直します

2023-09-25 10:47 UTC, kawanoichi commented on Makefile
> +	cd $(MAKEFILE_PATH)/server && python3 flask_server.py
helpに合わせたつもりだったけど、できてないね。
直します

2023-09-25 11:09 UTC, kawanoichi commented on rear_camera_py/Makefile
>  	rm -rf image_data/
キャリブレーションコマンドを次のタスクで用意するのかな？今の段階だとここでいいと思う

2023-09-25 11:32 UTC, miyashita64 commented on rear_camera_py/Makefile
>  	rm -rf image_data/
33-35行目のcalibrateコマンド

2023-09-25 11:46 UTC, miyashita64 commented on rear_camera_py/Makefile
>  	rm -rf image_data/
開発しやすいならそっちの方がいいか

2023-09-25 12:15 UTC, miyashita64 requested changes

2023-09-25 12:15 UTC, miyashita64 commented on Makefile
>  all-check:
helpに追記お願いします。

あと、これは良し悪しあるから判断は任せるけど、↓だと、変更あった時にチェック項目が変わった時に変更が一カ所で済む。
```
@${make} c-all-check
@${make} python-all-check
```

2023-09-25 12:25 UTC, kawanoichi commented on Makefile
>  all-check:
個人的にformat-checkは最後に実行したいから今の状態にしている
じゃないと見つけるのが大変。

2023-09-25 12:37 UTC, miyashita64 approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/89780)

2023-09-25 13:48 UTC, YKhm20020 reviewed
2つだけ、python コマンドについてお書きしたところがありますので、よろしければお答えしていただけるとありがたいです。
コメントした後に思ったのですが、むしろ python ないし python3 のコマンドじゃないと動かないみたいなことがあったりしますか？

2023-09-25 13:48 UTC, YKhm20020 commented on rear_camera_py/Makefile
>  	python -m src --calibrate
この場所のコマンドが python3 ではなく python になっていますが、これって実行できますか？
環境変数変わってなくて、前動いてたなら大丈夫だと思います🙆‍♀

2023-09-25 13:48 UTC, YKhm20020 commented on rear_camera_py/Makefile
> +	python -m unittest
ここも同じくです。今回追加しているところなので動くとは思いますが、お答えしていただけると幸いです。

2023-09-25 14:26 UTC, kawanoichi commented on rear_camera_py/Makefile
> +	python -m unittest
自分の環境でしか調べることができないので正確な情報かどうかはわかりませんが、wslで以下のように表示されれば問題ないと思います。バージョンが違う場合は複数のpythonが入っている可能性があるため使う際に注意が必要になってくると思います。
```
$ python -V
Python 3.9.2
$ python3 -V
Python 3.9.2
```
ただし、自分の環境のpowershell上ではpython3では実行できないので、pythonで実行しないといけません。

Makefileで修正しない理由は以下の通りです。
- 他の人の環境が分からない
- 本番前なので、あまり今は実行コマンド系は触りたくない

2023-09-25 14:32 UTC, kawanoichi commented on rear_camera_py/Makefile
>  	python -m src --calibrate
`python -m src --calibrate`を実装したのが僕ではないと思うので動くかどうかは正直分かりません

2023-09-26 03:39 UTC, YKhm20020 approved these changes
お答えいただきありがとうございました、LGTMです、お疲れ様でした！
![69697](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/6fc43e2f-c458-40d3-9c33-ddae3fd89fad)

2023-09-26 04:17 UTC, aridome222 approved these changes
すみません、レビュー遅れました。
問題ないと思います！
LGTM!

2023-09-26 05:22 UTC, KakinokiKanta approved these changes
LGTM!!

2023-09-26 05:23 UTC, merged