#127 地区大会前の調整と処理の修正
KatLab-MiyazakiUniv/etrobocon2023 pull request #129
Opened 2023-09-27 18:15 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-10-07 13:18 UTC, aridome222 requested changes
処理に関係ない細かい部分ですが、修正お願いします。

2023-10-07 13:35 UTC, bizyutyu reviewed
いくつか質問しているので、回答お願いします。

2023-10-07 13:35 UTC, bizyutyu commented on module/Motion/CameraAction.cpp
> +  printf("%s\n", cmd);
この部分は、snap_image実行時の、
`echo "$(SAVE_NAME) 画像取得！！！！！！！"`
と内容的にかぶる気もするのですが、確認の為にあえて出力しているんですかね？

2023-10-07 13:35 UTC, bizyutyu commented on rear_camera_py/Makefile
> +	sudo python3 src/capture_snap_image.py  --save_path $(SAVE_NAME)
ここも含め、sudoでやっている理由を教えて欲しいです。
撮影画像の権限が確定でrootになるので、撮影画像を扱う処理(scpコマンドなど)に影響が出るかが少し気になります。（多分大丈夫だとは思いますが）

2023-10-07 14:08 UTC, miyashita64 requested changes
関数名だけ気になりました

2023-10-07 14:08 UTC, miyashita64 commented on rear_camera_py/src/capture_snap_image.py
> +    def start(self) -> None:
クラス名的にcapture()とか？

2023-10-07 14:32 UTC, KakinokiKanta reviewed
処理に問題はないように感じます。単純に疑問に思ったところをコメントしているので、回答お願いします。

2023-10-07 14:32 UTC, KakinokiKanta commented on rear_camera_py/src/capture_snap_image.py
> +            result = cv2.addWeighted(img, 2.5, blurred, -1.5, 0)  # 差分から鮮明化
このあたりのパラメータについては、何か参考にした資料はありますか。あれば、リンクを張っておいてほしいです。

2023-10-07 14:32 UTC, KakinokiKanta commented on rear_camera_py/src/camera_interface.py
> +    camera = CameraInterface(camera_id=args.camera_num)
今回の変更で、ここの呼び出しにかかる時間を大幅に短縮できるようになったという認識なのですが、理由はOpenCVとPillowを比べた際にOpenCVの方が早かったということですかね？軽く調べた限りだと、画像の取得だけならPillowの方が早そうだと感じたのですが。
[https://qiita.com/BUU-SAN/items/e82655a814f2ca95926e](url)

2023-10-08 08:25 UTC, kawanoichi commented on module/Motion/CameraAction.cpp
> +  printf("%s\n", cmd);
実行した際に個人的にするグミつけることができなかったからわかりやすいように表示している。
調整組がいらないというならば消す

2023-10-08 08:30 UTC, kawanoichi commented on rear_camera_py/Makefile
> +	sudo python3 src/capture_snap_image.py  --save_path $(SAVE_NAME)
あんまり権限についての知識がないんやけど、「撮影画像の権限が確定でrootになる」ってのはなぜ？
調整時に権限がないって怒られたからつけたんよね。

2023-10-08 08:32 UTC, kawanoichi commented on rear_camera_py/src/capture_snap_image.py
> +            result = cv2.addWeighted(img, 2.5, blurred, -1.5, 0)  # 差分から鮮明化
ごめんなさい。もう記憶にありません

2023-10-08 08:33 UTC, kawanoichi commented on rear_camera_py/src/camera_interface.py
> +    camera = CameraInterface(camera_id=args.camera_num)
リンクを貼りなおしてください

2023-10-08 08:38 UTC, kawanoichi commented
@aridome222 
修正部分どこでしょうか？

2023-10-08 08:40 UTC, bizyutyu commented on module/Motion/CameraAction.cpp
> +  printf("%s\n", cmd);
あって困ることはないので個人的にはそのままでOKだと思います！

2023-10-08 08:57 UTC, bizyutyu commented on rear_camera_py/Makefile
> +	sudo python3 src/capture_snap_image.py  --save_path $(SAVE_NAME)
sudoでコマンドを実行すると、コマンドによって作成されるファイルの権限が必ずrootになるはずなので、そういう意味で使ってました。逆にsudoを使わないと、必ずしも生成ファイルの権限がrootにならないという認識です。
sudoで成功したということは、生成ファイル(image_data/ など)の権限がrootでないといけないと思われるのでsudoを使うべきなのだと思います。
「調整時に権限がないって怒られた」ということは、その時生成されたファイルの権限がroot以外だったのかもしれないですね、、、

2023-10-08 09:29 UTC, miyashita64 approved these changes
ありがとう。お疲れ様！
![LGTM](https://image.lgtmoon.dev/217768)

2023-10-08 09:32 UTC, aridome222 requested changes
Add review commentせずにRequest changes送ってしまって全部消えてしまっていました。
すみません。1つだけ気になった点があります。

2023-10-08 09:32 UTC, aridome222 commented on rear_camera_py/Makefile
> +## 画像取得関連 ##@
末尾に@を付けているのは何か意図があるんでしょうか？

2023-10-08 09:40 UTC, bizyutyu approved these changes
お疲れ様です！
![LGTM](https://image.lgtmoon.dev/164855)

2023-10-08 14:34 UTC, aridome222 approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/202847)

2023-10-13 04:10 UTC, KakinokiKanta approved these changes
LGTM

2023-10-13 04:11 UTC, merged