D制御にフィルタを追加
KatLab-MiyazakiUniv/etrobocon2023 pull request #132
Opened 2023-10-06 04:42 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-10-18 12:50 UTC, kodama0720 requested changes
動画が欲しい。変更でライントレースの精度は上がってそう？

2023-10-18 12:50 UTC, kodama0720 commented on module/Calculator/Pid.cpp
> +    d = d / (1.0 + timeConstant * (fabs(d) / gain.kp));
この式どこから拾ってきたの？説明が欲しい。

2023-10-18 12:50 UTC, kodama0720 commented on module/Motion/PwmRotation.cpp
> +  Controller::stopMotor();
モーターストップのコマンド化って何のためにしてるの？
コマンドで停止するならここで停止入れる必要ない？

2023-10-19 06:55 UTC, bizyutyu commented on module/Motion/PwmRotation.cpp
> +  Controller::stopMotor();
- ライントレース後に実行されていたContoroller::stopMotor()を消していた(今は戻していますが)ので、ライントレース後に左右モーターストップする必要がある時用に作成しました。（少し後退→前進の時など）
- 現段階では、ライントレース後にContoroller::stopMotor()する形に戻しており、特にコマンドの用途もないので、要らないですかね？

2023-10-19 07:04 UTC, bizyutyu reviewed
動画は今日中にアップロードします。少々お待ちください。
今回の変更で、過大なD値によるライントレース旋回値への影響は無くせましたが、正常時(上手くライントレースできているとき)のD値への影響が若干ある為、精度は少し下がっている印象です。
今回追加したフィルタの時定数やライントレースPIDゲインの調整が必要そうです。

2023-10-19 07:10 UTC, kawanoichi commented
そもそもこのタスクって何の課題を解決するためのものだっけ？
変更点だけでなく、課題と発見した原因を明記してほしい

2023-10-19 07:15 UTC, bizyutyu commented on module/Motion/PwmRotation.cpp
> +  Controller::stopMotor();
回頭前（PWM・速度指定ともに）のContoroller::stopMotor()を削除しました。

2023-10-19 07:22 UTC, bizyutyu commented
> そもそもこのタスクって何の課題を解決するためのものだっけ？ スタート後の失敗ってのは急発進とはちがうんだっけ？

走行に関する問題として、
- 急加速する・回頭が終わらず回転し続ける
- ライントレース旋回値が大きくなりすぎてコースアウトする
という問題があり、このタスクは２つ目を解決する為のものです。（説明に追記しておきます）

2023-10-19 08:34 UTC, kawanoichi approved these changes
この処理が正しいのかは正直分かりませんが、原因の解消ができているなら、とりあえずこのタスクはいいと思います！！
![225811](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/f27bb3a2-9188-4a2b-aa05-6610cb4f8180)

2023-10-19 10:50 UTC, miyashita64 approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/157080)

2023-10-19 17:23 UTC, bizyutyu commented
走行チェックや見直しをしていて遅れてしまいましたが、動画をアップロードしたので確認お願いします。
フィルタの式を旋回値の算出に合った形に変えたので、これまでの走行精度をほぼ保ったまま、変更を加えることが出来ていると思います。

2023-10-19 17:39 UTC, Negimarge approved these changes
dゲインの制御という認識でLGTM!!

2023-10-20 02:45 UTC, kodama0720 approved these changes
動画見た感じよさそう
![LGTM](https://image.lgtmoon.dev/135740)

2023-10-20 06:18 UTC, bizyutyu commented
![image](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/132331737/cc61335b-171a-4123-be32-4fec9df9857b)

2023-10-20 06:27 UTC, merged