#135 ブロックdeおかたづけのエリア情報を取得する (作業中)
KatLab-MiyazakiUniv/etrobocon2023 pull request #136
Opened 2023-10-09 13:59 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-11-02 07:32 UTC, miyashita64 approved these changes
とりあえず

2023-11-02 08:06 UTC, desty505 approved these changes
LGTM！

2023-11-02 08:24 UTC, aridome222 approved these changes
LGTM！

2023-11-09 02:57 UTC, miyashita64 requested changes
一旦

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/calculator.py
> +class Calculator:
```suggestion
class LineCalculator:
```
とか？

Lineクラスにして、コンストラクタに複数座標を渡してインスタンス化、line.calc_distance_coord()みたいな感じで距離算出とかでもいいかも

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/calculator.py
> +    def calc_dis_line_to_coordi(coordi: np.ndarray, line: np.ndarray) \
clacかcalculateは混ぜないで欲しいです。

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/get_area_info.py
> +class Color(Enum):
```suggestion
class RgbColor(Enum):
```

Rgbだけでもいいかな？

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/get_area_info.py
> +        self.block_max_count_blue = 2
クラス変数でよくね？

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/get_area_info.py
> +        self.course_info_block = np.zeros(16).reshape(4, 4)
```suggestion
        self.course_info_block = np.zeros((4, 4))
```
でよくなかったっけ？

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/get_area_info.py
> +        self.column_verctor_3 = np.array([None, None])
row_vectorsとcolumn_vectorsとかの方が良くない？

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/get_area_info.py
> +            # return None, develop_img
消し忘れ？

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/get_area_info.py
> +        # if self.develop:
消し忘れ？

2023-11-09 02:57 UTC, miyashita64 commented on rear_camera_py/src/get_area_info.py
> +        detect_flag = 0
好み
```suggestion
        is_detected = False
```

2023-11-09 06:03 UTC, kawanoichi commented on rear_camera_py/src/get_area_info.py
> +        self.block_max_count_blue = 2
探すブロックについては、ブロック検出数によって変わる可能性があるのでブロックを表す値の変数だけクラス変数(定数)にしました。

2023-11-09 06:03 UTC, kawanoichi commented on rear_camera_py/src/get_area_info.py
> +        self.column_verctor_3 = np.array([None, None])
変更が大変なので却下

2023-11-09 13:14 UTC, bizyutyu requested changes
現状気づいたところです。

2023-11-09 13:14 UTC, bizyutyu commented on rear_camera_py/src/get_area_info.py
> +        """画像を6色画像に変換する関数.
```suggestion
        """画像からコース情報を取得する関数.
```

2023-11-09 13:14 UTC, bizyutyu commented on rear_camera_py/src/block_de_treasure_hunter.py
>          # TODO: ここまで、マージする際に差し替える
6行くらい前の `# TODO: ここから、マージする際に差し替える` からここまでは、消して良いと思います。
get_area_info側での処理までレビューできてないので、エラーが返ってきた時の為に残してるのだったらすいません。
```suggestion
```

2023-11-09 16:22 UTC, ykimura0726 approved these changes
コードに問題はないと思うので、LGTMです、お疲れ様でした！
ただ、調整用ブランチの方ではダミーブロックを1、トレジャーブロックを2で番号を振っていたと思うので、どっちかを変える必要はあると思われます。

2023-11-10 06:02 UTC, Negimarge approved these changes
LGTM

2023-11-10 06:13 UTC, miyashita64 approved these changes
LGTM

2023-11-10 07:05 UTC, bizyutyu approved these changes
お疲れ様です。LGTM!
![LGTM](https://image.lgtmoon.dev/147222)

2023-11-10 07:06 UTC, merged