close #134 回頭補正のキャリブレーション修正
KatLab-MiyazakiUniv/etrobocon2023 pull request #137
Opened 2023-10-17 14:27 UTC by aridome222

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

2023-10-17 15:28 UTC, miyashita64 requested changes
動画欲しいです。

2023-10-17 15:28 UTC, miyashita64 commented on module/Motion/CorrectingRotation.cpp
> +    printf("横線を採用！！！\n");
実験用なら消して、残すつもりならlogger使っておくれ。
```suggestion
    logger.log("横線を採用！！！\n");
```

2023-10-17 15:28 UTC, miyashita64 commented on module/Motion/CorrectingRotation.cpp
> +#include <stdio.h>
たぶん使わない。

2023-10-17 15:28 UTC, miyashita64 commented on module/Motion/CorrectingRotation.h
> +#include "SpeedCalculator.h"
多分使ってない？(SystemInfoも)
```suggestion
```

2023-10-18 11:30 UTC, kawanoichi requested changes
失敗したときの角度を算出した画像(検出した線を表示した画像)はないですか？

2023-10-18 11:40 UTC, aridome222 commented
> 失敗したときの角度を算出した画像(検出した線を表示した画像)はないですか？

2023-10-18 11:46 UTC, kawanoichi commented
できればリアカメラで撮影した画像(回頭補正用)を[googledrive](https://drive.google.com/drive/folders/1rKMwL65iQK8EY9ShZH8cYDr9HsGKTp1G)に保存しててほしいです。

2023-10-18 11:54 UTC, aridome222 commented
> 失敗したときの角度を算出した画像(検出した線を表示した画像)はないですか？

残念ながらその時の画像は無いのですが、make debugで失敗するであろう時の角度を算出した画像ならあります。
失敗する条件として、
横線が採用された場合に計測角度がマイナスの値だと失敗し、縦線が採用された場合に計測角度がプラスの値だと失敗します。

2023-10-18 12:05 UTC, aridome222 commented
> できればリアカメラで撮影した画像(回頭補正用)を[googledrive](https://drive.google.com/drive/folders/1rKMwL65iQK8EY9ShZH8cYDr9HsGKTp1G)に保存しててほしいです。

ブロックでトレジャーフォルダに、回頭補正用のフォルダを作成し、
横線／縦線で、成功した時と失敗した時と、そもそも線検出できなかった時の画像を入れておきました。

2023-10-21 03:38 UTC, closed without merging