close #141 端点サークルまでの動作確認・調整
KatLab-MiyazakiUniv/etrobocon2023 pull request #143
Opened 2023-10-25 03:39 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-11-01 05:38 UTC, miyashita64 requested changes
調整お疲れ様です。
subjectについてだけ

2023-11-01 05:38 UTC, miyashita64 commented on module/Motion/CameraAction.h
> +   * @param _subject 撮影対象　true:ミニフィグA false:ミニフィグB
コメントの修正漏れ

2023-11-01 05:38 UTC, miyashita64 commented on module/Motion/CameraAction.cpp
> +  : sj(_subject),
メンバ変数名は省略せずにsubjectの方が何かわかっていいと思う。

2023-11-01 05:38 UTC, miyashita64 commented on module/Motion/CameraAction.h
> +  enum class subject { A, B, BA };
クラス名はコーディング規約上アッパーキャメルケースでお願いします。
変数かクラスかが見分けやすいので。

[コーディング規約](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E3%82%AF%E3%83%A9%E3%82%B9)

2023-11-01 05:38 UTC, miyashita64 commented on module/MotionParser.cpp
> +  if(strcmp(command, "CA") == 0) {  //  コマンドがCAの場合
文字列をSubjectに変換するのに、コマンドの分岐は必要ないんじゃない？どちらかと言うと、コマンドに関係なく変換はできるべきだと思う

2023-11-01 05:38 UTC, miyashita64 commented on module/Motion/CameraAction.h
> +   * @param subject A:ミニフィグA B:ミニフィグB BA:ブロックエリア
クラス上では、BLOCK_AREAなりBLOCKの方がわかりやすいと思う。
コマンドでの打ち間違いが怖いなら、パーサーでBAをSubject::BLOCKに変換すれば問題なさそう。
(BAから変換するならBLOCK_AREAか？)

2023-11-01 05:38 UTC, miyashita64 commented on module/MotionParser.cpp
> +  return CameraAction::subject::A;
これ、何かの間違いでここにきた時に、変な画像がフィグAの画像として扱われるのは不味くない？
UNDEFINEDとかINVALIDとかそれ用のSubjectを作る方が適切だと思う。

2023-11-01 13:50 UTC, bizyutyu commented on module/Motion/CameraAction.h
> +  enum class subject { A, B, BA };
※enum classは、列挙型の一種みたいです。クラスに似た特性を持ってはいますが、どちらかというと型という方が正しいかもしれません。enum struct と書いても代用できるみたいです。(参考ページ)[https://learn.microsoft.com/ja-jp/cpp/cpp/enumerations-cpp?view=msvc-170]

2023-11-01 13:55 UTC, bizyutyu commented on module/Motion/CameraAction.h
> +   * @param subject A:ミニフィグA B:ミニフィグB BA:ブロックエリア
確かにそうですね。変更しようと思います。

2023-11-01 19:41 UTC, aridome222 approved these changes
他に指摘できる部分は無かったです。お疲れ様です。
![LGTM](https://image.lgtmoon.dev/113549)

2023-11-02 00:36 UTC, YKhm20020 approved these changes
宮下さんの指摘箇所以外は大丈夫だと思われます、お疲れ様でした！
![114068](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/163fdd99-35e8-4ff3-becb-df3447153895)

2023-11-02 02:45 UTC, bizyutyu commented on module/MotionParser.cpp
> +  return CameraAction::subject::A;
現在は、Subject型にUNDEFINEDを追加し、
- コマンドの引数でA,B,BA以外が入力された場合にパーサーでUNDEFINEDをセットする
- CameraActionがUNDEFINEDを受け取ったら撮影は行わない(撮影スキップ時と同じ動作をする)ようにしています。

2023-11-02 02:52 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/6571)

2023-11-02 04:46 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/71543)

2023-11-02 07:41 UTC, merged