close #139 ブブロックエリアにおける経路探索と対応コマンドの生成
KatLab-MiyazakiUniv/etrobocon2023 pull request #145
Opened 2023-10-30 14:05 UTC by miyashita64

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- ブロックの位置情報を入力として、ブロックを通るような経路を実現する動作を探索するクラス群を追加した

# 動作テスト
載せます

2023-11-01 06:54 UTC, kodama0720 reviewed
見た感じよさそうに思いました。

2023-11-01 06:54 UTC, kodama0720 commented on rear_camera_py/src/robot.py
> +        return hash(self.y + self.x * 10 + self.direction.value * 100 + self.cost * 1000)
これ何に使う？

2023-11-01 08:05 UTC, miyashita64 commented on rear_camera_py/src/robot.py
> +        return hash(self.y + self.x * 10 + self.direction.value * 100 + self.cost * 1000)
探索するときに重複とか探索済みの要素を排除するために、setを使って集合にしてるんだけど、そのときに使われるらしい。
何も指定せずに独自クラスを集合にすると、インスタンスのメモリで同じ要素かが判断されるらしい。今回は、座標と方角とコストが同じインスタンスは同じ状態として扱いたいから、__eq__と__hash__を指定してる。

[独自のクラスをSetで扱えるように...](https://www.yoheim.net/blog.php?q=20171001)

2023-11-01 16:14 UTC, desty505 approved these changes
大丈夫だと思います！
![LGTM](https://image.lgtmoon.dev/217969)

2023-11-01 16:52 UTC, bizyutyu requested changes
よろしくお願いします。

2023-11-01 16:52 UTC, bizyutyu commented on rear_camera_py/src/block_de_treasure_hunter.py
> +            is_left_course = args[1] == "true"
```suggestion
        if args[1] == "left" or args[1] == "right":
            is_left_course = args[1] == "left"
```
コマンドの引数なら、left/rightの方が分かりやすい？
個人的な好みなので、無視でもOKです。

2023-11-01 16:52 UTC, bizyutyu commented on rear_camera_py/src/block_de_treasure_hunter.py
> +            commands += f"{motion.make_command()}\n"
この部分について、経路探索して得られた経路を通るコマンドをそのまま出力していると思うのですが、
CurveクラスでのIRやIL，Navigateクラスで最後に追加しているPRなど、角度算出をしてコマンドの引数に使っているものに関しては、実機だと指定角度が大きすぎるのではないでしょうか？
経路探索で算出されているangleを辿ってみると、Directionクラスにたどり着くのですが、おそらく0.90.180などの値しか返してこないと思うので、コマンド書き出しのときに何かしら角度を調整する処理が必要かもしれません。
※IRやIL，PRなどを角度指定無しでも使えるようにする方が簡単かもしれません。（その場合は別タスクになる気もします）

2023-11-01 17:14 UTC, miyashita64 commented on rear_camera_py/src/block_de_treasure_hunter.py
> +            commands += f"{motion.make_command()}\n"
確かに直進、左折、右折、後ろに進む(180度回頭して直進)の4つ作った方がいいかもね。
ひとまず、今回のタスクではMotionに角度変換用の処理を追加しようと思います。

2023-11-01 19:12 UTC, aridome222 requested changes
1点だけ修正お願いします。

2023-11-01 19:12 UTC, aridome222 commented on rear_camera_py/src/block_de_treasure_hunter.py
> +            hunter.hunt(is_left_course)
is_left_courseはbool型なので、Trueを入れるべきだと思います。

2023-11-01 19:42 UTC, YKhm20020 commented on rear_camera_py/src/block_de_treasure_hunter.py
> +            hunter.hunt(is_left_course)
ここについては高倉さんからコメントを頂いていて、それを宮下さんが修正していただいたところで、たしかに型を考えると元の方がいい気もする。見やすさだと bool -> String に変換して一致するかをチェックした方がいいけど、処理的には無駄ある気がする。

宮下さん的にはどっちがいいと思いますか？

2023-11-02 01:33 UTC, miyashita64 commented on rear_camera_py/src/block_de_treasure_hunter.py
> +            hunter.hunt(is_left_course)
C++側からこのpython実行しようとしたときに、↓っぽい処理をやらんといかんと思う。

①変更前
`sprintf(buf, "python block_de_treasure_hunter.py %s", isLeftCourse? "true" : "false"`);

②変更後
`sprintf(buf, "python block_de_treasure_hunter.py %s", isLeftCourse? "left" : "right"`);

この場合、どっちにしろbool->文字列の変換はしないといけない。
ならleft/rightの方がわかりやすいかなと思った。



変換なしでやるなら
`sprintf(buf, "python block_de_treasure_hunter.py %d", isLeftCourse`);
で1ならleft,0ならrightとかだけど、これは見づらすぎるから個人的にない。

2023-11-02 01:57 UTC, bizyutyu approved these changes
お疲れ様です。
![LGTM](https://image.lgtmoon.dev/226970)

2023-11-02 02:44 UTC, Negimarge approved these changes
LGTM

2023-11-02 04:30 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/88558)

2023-11-02 08:03 UTC, aridome222 approved these changes
LGTM！

2023-11-02 08:04 UTC, merged