close #147 ブロックdeトレジャーハンターの攻略に必要な要素を統合する
KatLab-MiyazakiUniv/etrobocon2023 pull request #149
Opened 2023-11-08 06:41 UTC by miyashita64

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
## 動作関連
- ブロックエリア内の動作コマンドについて、パラメータをコマンド引数で指定ではなくクラスが持つように変更
- 後ろを向くコマンド(BR)とパーサーの処理を追加

## 経路計画関連
- rear-camera-py/Makefileにブロックdeトレジャーハンター攻略を計画するコマンドを追加(開発用)
- 経路探索時にブロック移動動作(BT)、180度回頭(BR)、回頭補正(XR)を扱うように変更
  - XRを含むコマンドファイルを読み込むテストを実行した場合、リアカメラにアクセスできずにWarningが起こりテストが失敗するため、「角度補正を実行した直後のrear_camera_pyにアクセスできないWarning」だけは握りつぶす処理を追加
- ブロックエリアへの侵入用の動作コマンドを計画時にファイル書き込みするように変更
- 計画時に書き込むコマンドファイルのパスを変更
- Navigatorのテストを追加

# 動作テスト
実際に走行を行い、1つ目のブロックまでは経路に沿って走行できることを確認した。
ただし、ブロック移動後の復帰がうまくいかないため、要調整。

2023-11-09 07:19 UTC, kawanoichi requested changes

2023-11-09 07:19 UTC, kawanoichi commented on rear_camera_py/Makefile
> +	cd src && python3 block_de_treasure_hunter.py right
```suggestion
hunt-l:
	python3 src/block_de_treasure_hunter.py left

hunt-r:
	python3 src/block_de_treasure_hunter.py right
```
わざわざ1個のコマンドで済むのに、2個のコマンドを合わせるのは無駄な気がするのでこっち派。
コマンドは小文字でないといけないとかある？LRの方がわかりやすいと思う

2023-11-09 07:19 UTC, kawanoichi commented on module/Motion/BlockAreaMotion.h
>  #define BLOCK_MOTION_H
ファイルの消し忘れ？

2023-11-09 07:19 UTC, kawanoichi commented on module/Motion/CameraAction.cpp
> +           makeImageCommand, imageName);
`rear_camera_py/Makefile`の`make image`の部分を変更しないと、ファイル名受け取るような形になっていない

2023-11-09 07:19 UTC, kawanoichi commented on rear_camera_py/src/navigator.py
> +                    "angle": 60.0,  # 90度回頭
確認やけど、90度回頭の指定が60度でOK？

2023-11-09 08:40 UTC, miyashita64 commented on module/Motion/BlockAreaMotion.h
>  #define BLOCK_MOTION_H
継承されてる

2023-11-09 08:41 UTC, miyashita64 commented on rear_camera_py/src/navigator.py
> +                    "angle": 60.0,  # 90度回頭
概ねそのぐらい。

2023-11-10 08:05 UTC, bizyutyu approved these changes
![LGTM](https://image.lgtmoon.dev/68903)

2023-11-10 08:11 UTC, KakinokiKanta approved these changes
![LGTM](https://image.lgtmoon.dev/227778)

2023-11-10 08:23 UTC, kawanoichi approved these changes
![112117](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/5ad62c2a-91e1-421d-a86e-4413a0f42a68)

2023-11-10 11:39 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/146779)

2023-11-10 15:54 UTC, merged