close #14 READMEにビルド方法を追記
KatLab-MiyazakiUniv/etrobocon2023 pull request #20
Opened 2023-05-22 11:45 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
READMEにビルド方法を追記

2023-05-22 18:44 UTC, KakinokiKanta requested changes
wikiの記述ありがとうございます

2023-05-22 18:44 UTC, KakinokiKanta commented on README.md
> +$ cd ~/etrobo
```suggestion
$ cd ~/etrobo/workspace
```
じゃなかったですっけ？

2023-05-22 18:48 UTC, kawanoichi commented on README.md
> +$ cd ~/etrobo
自分の環境だとworkspace下でビルドできないんよね。
確認していただけると嬉しい

2023-05-23 05:38 UTC, KakinokiKanta submitted a review, later dismissed
LGTM!!

2023-05-23 05:38 UTC, KakinokiKanta commented on README.md
> +$ cd ~/etrobo
僕の勘違いでした。僕もworkspace下じゃできませんでした。

2023-05-24 01:40 UTC, miyashita64 approved these changes, later dismissed
LGTM
![LGTM](https://image.lgtmoon.dev/209564)

2023-06-02 05:59 UTC, aridome222 approved these changes
![LGTM](https://image.lgtmoon.dev/164449)

2023-06-04 04:47 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/210758)

2023-06-04 06:28 UTC, bizyutyu approved these changes
![LGTM](https://image.lgtmoon.dev/111743)

2023-06-04 19:45 UTC, merged