close #22 時間を計測するTimerクラスを追加
KatLab-MiyazakiUniv/etrobocon2023 pull request #24
Opened 2023-05-27 07:01 UTC by ykimura0726

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
sleep, now関数を別ファイルに作成。module/API下に以下のファイルを追加。
- Timer.h
- Timer.cpp

test/dummy下に以下のファイルを追加。
- Clock.h
- Clock.cpp

sleep, now関数を別ファイルに分けたため、それらの関数をmodule/API下の該当ファイルから削除。
- Controller.h
- Controller.cpp

test/dummy下のev3api_voltage.cppのcase文の分岐を0, 1から0, defaultに変更。

# 動作テスト

## 添付資料

2023-05-27 07:12 UTC, KakinokiKanta requested changes
修正お願いします

2023-05-27 07:12 UTC, KakinokiKanta commented on module/API/Timer.h
> +  Timer() = delete;  // 明示的にインスタンス化を禁止
インスタンス化しなくても良いのでは？

2023-05-27 07:43 UTC, KakinokiKanta approved these changes
よろしく

2023-05-27 07:43 UTC, KakinokiKanta commented on module/API/Timer.h
> +  static void sleep(int milliSec = 10);
```suggestion
  void sleep(int milliSec = 10);
```
いらないよ

2023-05-27 07:43 UTC, KakinokiKanta commented on module/API/Timer.h
> +  static int now();
```suggestion
  int now();
```
ここも

2023-05-27 08:03 UTC, KakinokiKanta requested changes
clockはインスタンス化してほしい

2023-05-27 08:03 UTC, KakinokiKanta commented on module/API/Timer.h
> +
```suggestion
　private:
   Clock clock;
```
Clockのインスタンス化はした方が良いかな

2023-05-27 08:03 UTC, KakinokiKanta commented on module/API/Timer.cpp
> +  ev3api::Clock().sleep(milliSec * 1000);
```suggestion
  clock.sleep(milliSec * 1000);
```

2023-05-27 08:03 UTC, KakinokiKanta commented on module/API/Timer.cpp
> +  return ev3api::Clock().now() / 1000;  // マイクロ秒をミリ秒になおしてreturn
```suggestion
  return clock.now() / 1000;  // マイクロ秒をミリ秒になおしてreturn
```

2023-05-27 08:15 UTC, KakinokiKanta approved these changes
![image](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/105735727/b8b7fdb9-a277-4b33-892f-b5acf915cc37)

2023-05-27 08:26 UTC, aridome222 approved these changes

2023-05-27 08:31 UTC, aridome222 approved these changes
![LGTM](https://image.lgtmoon.dev/160888)

2023-05-29 04:40 UTC, bizyutyu approved these changes
遅くなりました。LGTM!

2023-05-29 04:40 UTC, bizyutyu approved these changes
遅くなりました。LGTM!

2023-05-29 08:24 UTC, merged