close#13 ticket-13 コースの左右、目標輝度の設定
KatLab-MiyazakiUniv/etrobocon2023 pull request #26
Opened 2023-05-27 09:11 UTC by aridome222

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
module下に以下のファイルを追加。
- Calibrator.cpp
- Calibrator.h

# 動作テスト

## 添付資料

2023-06-02 09:52 UTC, miyashita64 requested changes
内容はいいと思います。
コメントだけ修正お願いします。

2023-06-02 09:52 UTC, miyashita64 commented on module/Calibrator.cpp
> +  // 黒と白の輝度を測定して目標輝度を求める
処理的には↓かな？
```suggestion
  // 目標輝度を測定する
```

2023-06-02 14:14 UTC, miyashita64 commented on test/dummy/SonarSensor.cpp
>  int SonarSensor::getDistance()
値が変わらないなら、変わりそうな↓の処理は消して
`return distance;`
だけにした方がいいかも。

2023-06-02 14:23 UTC, molpui0726 commented on module/Calibrator.h
> +  bool isLeftCourse;     // true:左コース, false: 右コース
```suggestion
  bool isLeftCourse;     // true:Lコース, false: Rコース
```
コメントで動作に影響ないうえに細かいですが。getLefftCourseと書き方合わせるといいと思います。
それかgetIsLeftCourseの法を右コース、左コースに合わせてもいいと思いますが、後の記述がLRなのでこの修正がいいかもしれません。

2023-06-03 08:56 UTC, KakinokiKanta approved these changes
LGTM!

2023-06-04 04:04 UTC, bizyutyu approved these changes
問題ないと思います。
![LGTM](https://image.lgtmoon.dev/127446)

2023-06-04 04:39 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/23142)

2023-06-05 06:03 UTC, merged