close #19 RasPiにWebサーバを設置する
KatLab-MiyazakiUniv/etrobocon2023 pull request #27
Opened 2023-05-29 05:09 UTC by desty505

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
etrobocon2023下にcommunicate_pyというファイルを作成

# 動作テスト
SendServer.pyでサーバを起動およびサーバにdata.csvにあるデータを送信できた。
ReadServer.pyでサーバに送られているデータをresult.csvにデータを書き込むことができた。

# これから
SendServer.pyではサーバの起動とサーバにデータを送信するのを１つにまとめてしまっているため、
RasPi→PCの通信しかできないため、SendServer.pyをサーバの起動とデータの送信という２つに分割しようと考えてます。
現在(5月29日)は受け取ったデータをテキストとして受け取り、result.csvに書き込んでいるが、
これを数値データに変換し、計算等を行えるように変更しようと考えてます。

2023-06-01 13:17 UTC, kawanoichi requested changes
data.csv、data2.csv、result.csvファイルは必要ですか？
TimerとClockって何か変更しましたか？

2023-06-01 13:17 UTC, kawanoichi commented on server/flask_server.py
> +# データを取得
コメントが左寄せはわざとですか？それとも自動で修正されていますか？

2023-06-02 01:56 UTC, desty505 commented on server/flask_server.py
> +# データを取得
data.csvは必要です。
data2.csvとresult.csvはサーバ通信がうまくいっているかどうかを確認するときに使ったファイルで必須ではないです。テスト用のファイルという風に認識いただければ大丈夫です。

TimerとCrockは何も変更していないです。git pullがうまくいかなかったので、対処法を試してみたらなんか出てきました。柿木さんにも確認していただきながら行ったので多分大丈夫だと思います。

コメントの左寄せはわざとです。変更したほうがいいですか？

2023-06-02 09:43 UTC, kawanoichi commented on server/flask_server.py
> +# データを取得
このままマージすると必要でないファイルも残ってしまうので、必要ないファイルは消してもらっていいと思います。
コメントはできるだけコードの先頭に合わせるのが一般的だと思います。※可読性のため

2023-06-02 10:10 UTC, kawanoichi requested changes
READMEはMarkdown形式でお願いします

2023-06-02 10:10 UTC, kawanoichi commented on server/scripts/README.md
> +curl -X POST -H "Content-Type: text/plain; charset = utf-8" -d '@scripts/data2.csv' http://<サーバIPアドレス>:8000
```suggestion
curl -X POST -H "Content-Type: text/plain; charset = utf-8" -d '@scripts/"送信するcsvファイル"' http://<サーバIPアドレス>:8000
```
加えて、コマンドの場合、コードブロックを使用してください。
[コードブロックの書き方](https://docs.github.com/ja/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

2023-06-02 10:22 UTC, kawanoichi commented on server/scripts/README.md
> +curl -o scripts/result.csv http://<サーバIPアドレス>:8000/
```suggestion
curl -o scripts/"受信するcsvファイル" http://<サーバIPアドレス>:8000/
```
ここも

2023-06-02 10:23 UTC, kawanoichi requested changes
ごめんなさい、コメントできてなかったです。

2023-06-02 11:17 UTC, miyashita64 requested changes
send()がいつ呼ばれるかと、READMEに記載があったCSVファイルが何なのかを、ソースコード中のコメントやREADMEで書いてほしいです。

2023-06-02 11:17 UTC, miyashita64 commented on server/scripts/README.md
> +
サーバについてのREADMEってことなら、サーバの起動・停止方法について記述してほしいです。
あと、設置場所は`server/README.md`だと思う。

2023-06-02 11:17 UTC, miyashita64 commented on server/scripts/README.md
> +調整用IOSアプリと通信する用のflaskサーバプログラムです。
違和感が...
```suggestion
調整用iOSアプリと通信する用のflaskサーバプログラムです。
```

2023-06-02 11:17 UTC, miyashita64 commented on server/flask_server.py
> +    app.run(host='192.168.11.16', port=8000)
直接ipアドレス指定すると、走行体１でしか動かないと思うからこんな感じでどうでしょう
```suggestion
    ip = "127.0.0.1"
    host = os.uname()[1]
    if host == "katlab":
        ip = "192.168.11.16"
    elif host == "katlab2":
        ip = "192.168.11.17"
    app.run(host=ip, port=8000)
```

2023-06-02 11:17 UTC, miyashita64 commented on server/flask_server.py
> +from flask import Flask, request
これでよかったような
```suggestion
from flask import Flask, url_for, request
```

2023-06-02 11:17 UTC, miyashita64 commented on server/scripts/data.csv
> +100,200,300
フォルダ名は、`scripts/`というより`datas/`とか`datafiles/`とかかな。

2023-06-02 11:17 UTC, miyashita64 commented on server/flask_server.py
> +            file.close()
完全に好みの話なので、無視してもらってもいいです。
```suggestion
    request_data = request.get_data()
    charset = request.mimetype_params.get('charset') or 'UTF-8'
    request_text = request_data.decode(charset, 'replace')

    if len(request_text) != 0:
        data_list = re.split('[ ,]', request_text)
        change_path = "scripts/data.csv"
        with open(change_path, 'w', encoding='utf-8', newline="") as file:
            writer = csv.writer(file)
            writer.writerow(data_list)
            file.close()
```

2023-06-02 11:17 UTC, miyashita64 commented on server/scripts/README.md
> +curl -X POST -H "Content-Type: text/plain; charset = utf-8" -d '@scripts/data2.csv' http://<サーバIPアドレス>:8000
`@scripts/data2.csv`がなんのファイルか説明が欲しいです。

2023-06-02 11:17 UTC, miyashita64 commented on server/scripts/README.md
> +curl -o scripts/result.csv http://<サーバIPアドレス>:8000/
`scripts/result.csv`がなんのファイルか説明が欲しいです。

2023-06-02 11:17 UTC, miyashita64 commented on server/flask_server.py
> +    if len(request_text) != 0:
全体的にコメントが欲しいです。
`request_text`ってリクエストをテキスト化したもの？それともリクエストの中から、READMEのコマンドで指定してたファイルの中身ってこと？

2023-06-02 11:17 UTC, miyashita64 commented on server/flask_server.py
> +def send():
いつ呼ばれるの？

2023-06-02 11:17 UTC, miyashita64 commented on server/flask_server.py
> +import requests
使ってない？

2023-06-02 11:17 UTC, miyashita64 commented on server/flask_server.py
> +        data_list = re.split('[ ,]', request_text)
csvのライブラリをインポートしてるなら、reより専用の処理使った方がいいと思う。
csv.reader()って関数があるみたい。

https://note.nkmk.me/python-csv-reader-writer/

2023-06-02 12:17 UTC, desty505 commented on server/flask_server.py
> +import requests
osとrequestsは使ってませんでした。すみません。
csvは、データをcsvファイルとして出力するときに使っているので必要そうです。

2023-06-02 13:11 UTC, desty505 commented on server/flask_server.py
> +        data_list = re.split('[ ,]', request_text)
説明不足で申し訳ないのですが、
サーバにデータを送信する際にcsvファイルで送信する場合と文字列を直接する場合の２つに対応させているので、
reのままの方が良いと思ったのですが、どうですか？

2023-06-02 13:33 UTC, miyashita64 commented on server/scripts/data.csv
> +100,200,300
他のCSVファイルについても同様

2023-06-02 13:54 UTC, miyashita64 requested changes
追加された`server/communication_py/`は、テスト用のファイル？
もしそうなら、`server/test/`みたいなとこにおいてほしい。

2023-06-02 13:54 UTC, miyashita64 commented on communication_py/ReadServer.py
> +import requests
どういうファイルかわからんけど(説明おねがい)、サーバというよりクライアント？

2023-06-02 13:54 UTC, miyashita64 commented on communication_py/SendServer.py
> +import os
これは何用のファイル？

2023-06-02 13:54 UTC, miyashita64 commented on communication_py/scripts/result.csv
> +100,200
これも`datafiles/`かな

2023-06-02 13:54 UTC, miyashita64 commented on server/flask_server.py
> +        data_list = re.split('[ ,]', request_text)
文字列を直接ってどういうこと？
request_textではない？

2023-06-02 13:54 UTC, miyashita64 commented on server/flask_server.py
> +@app.route('/', methods=["POST", "GET"])
README見た感じ、データ送信はPOSTで、データ受信はGETでやってるんだよね？
もしそうなら、if文でリクエスト内のテキストの有無を判定するより、GETかPOSTで判断する方がWebらしいと思う(関数名はテキトー)。
参考：https://shigeblog221.com/flask-get-post/

```suggestion
@app.route('/', methods=["GET"])
def read():
    # ファイル読込の処理

@app.route('/', methods=["POST"])
def write():
    # ファイル更新の処理
```

2023-06-02 14:07 UTC, desty505 commented on communication_py/SendServer.py
> +import os
すみません。
communication_py自体が必要なくなったディレクトリだったのですが、消し忘れてました。

2023-06-02 14:15 UTC, desty505 commented on server/flask_server.py
> +@app.route('/', methods=["POST", "GET"])
分かりました。
ありがとうございます。
参考にさせていただきます。

2023-06-02 14:29 UTC, miyashita64 commented on server/flask_server.py
> +        data_list = re.split('[ ,]', request_text)
READMEの更新で何となくわかりました。
わかったうえで、サーバに対して、文字列とCSVを使い分けたい場合、そもそも送りたいデータが違うと思うので、URLで分けるべきだと思います。例えば、CSVで更新したいパラメータを送信する場合と、停止命令の文字列を送信する場合とで、送信先のURLは分けるべきだと思います。(あくまで構造の話で、現段階で強制停止の処理を書けって言ってるわけじゃないです。)

```
@app.route('/params', methods=["POST"])
def set_params():
    # パラメータのcsvファイルを読み込んで更新する処理

@app.route('/stop', methods=["POST"])
def stop():
    # 走行体を強制停止する処理
```

2023-06-02 18:58 UTC, kawanoichi requested changes
コメントの書き方についてです。このタイミングになって申し訳ありませんが、変更をお願いします。

2023-06-02 18:58 UTC, kawanoichi commented on server/flask_server.py
> +def server():
```suggestion
def server():
    """関数の簡単な説明.

    関数の詳細(必要であれば書く)
    
    Returns:
        戻り値の型: 戻り値の概要
    """
```
今回、pythonの書き方についての説明をしていなかったので申し訳ないですが、このテンプレに合わせて関数のコメントを書き換えてください。
「# server()は"http://"サーバIPアドレス":8000/"にアクセスがされたときに実行される」は関数の詳細のところに書いていいと思います。

これは、pythonのドキュメントコメント(Googleスタイル)の書き方に合わせています。
詳しくは以下参照。
[Google スタイルの docstring をドキュメントに取り込む](https://www.sphinx-doc.org/ja/master/usage/extensions/napoleon.html)
[Pythonのドキュメントコメントの書き方(Googleスタイル編)](https://www.memory-lovers.blog/entry/2019/01/10/004107)[](https://www.memory-lovers.blog/entry/2019/01/10/004107)

2023-06-04 04:31 UTC, miyashita64 requested changes

2023-06-04 04:31 UTC, miyashita64 commented on server/flask_server.py
> +    """
形式としては、こんな感じでお願いします。
文章は案です。

```suggestion
    """GETリクエストに対しcsvファイルの内容を返す.

    "http://サーバIPアドレス:8000/"にGETリクエストされたときに実行される
    
    Returns:
        str:  サーバが持つcsvファイルの内容
    """
```

他の関数も同様。

2023-06-04 04:31 UTC, miyashita64 commented on server/flask_server.py
> +    """
ここも

2023-06-04 04:31 UTC, miyashita64 commented on server/flask_server.py
> +    return open_data
書き込みの関数としては成功/失敗だけ返す方が綺麗な気がするけど、仕様的にファイルの内容返す方が都合がいい？

2023-06-04 05:27 UTC, bizyutyu commented on server/flask_server.py
> +    open_path = "datafiles/data.csv"
open_pathにパスを代入する

2023-06-04 11:36 UTC, miyashita64 approved these changes
LGTM!!
お疲れ様！
![LGTM](https://image.lgtmoon.dev/206550)

2023-06-04 12:09 UTC, aridome222 approved these changes
重めのタスクお疲れ様！
![LGTM](https://image.lgtmoon.dev/107134)

2023-06-04 13:20 UTC, bizyutyu requested changes
対応していただけると幸いです。
内容おかしかったら、指摘してもらえると助かります。
コメント後の"Reviewchanges"押し忘れて、今更なリクエストになりました。すいません。

2023-06-04 13:20 UTC, bizyutyu commented on server/flask_server.py
> +    open_path = "datafiles/data.csv"
open_pathへのパス代入を２回しているので、先頭の方で（import宣言前？）
open_path = "datafiles/data.csv"
などとしたほうが良いのではないかと思う

2023-06-04 13:20 UTC, bizyutyu commented on server/flask_server.py
> +    open_path = "datafiles/data.csv"
ここについても同様です。

2023-06-04 13:20 UTC, bizyutyu commented on server/flask_server.py
> +        change_path = "datafiles/data.csv"
理解が正しいなら、扱うファイルは１つだけみたいなので、
change_pathとopen_pathに分けずに、file_pathなどにした上でファイル先頭で
file_path = "datafiles/data.csv"が、更にスッキリすると思います。

2023-06-04 13:29 UTC, desty505 commented on server/flask_server.py
> +        change_path = "datafiles/data.csv"
了解しました。
修正しておきます。

2023-06-04 13:33 UTC, bizyutyu commented on server/flask_server.py
> +        change_path = "datafiles/data.csv"
ありがとう！お願いします。

2023-06-04 14:08 UTC, desty505 commented on server/flask_server.py
> +        change_path = "datafiles/data.csv"
すみません。
pythonにはC言語でいうdefineのような定数定義の方法がなく、
これを解決する方法を調べる時間が欲しいので変更が遅れそうです。

2023-06-04 14:54 UTC, bizyutyu commented on server/flask_server.py
> +        change_path = "datafiles/data.csv"
返事遅くなりました。

define的なものを使うわけではなくて、ファイルの最初の方で、
file_path = "datafiles/data.csv"をしておいて、
それぞれの@（デコレータ）の中で、
open(file_path)
みたいにすることは出来ないかな？
そうすれば、ファイルパスの代入（今の状態でいうとopen_path = "datafiles/data.csv"）が１回で済むと思う。

2023-06-04 15:05 UTC, bizyutyu commented on server/flask_server.py
> +        change_path = "datafiles/data.csv"
補足：
Pythonでは、不変な値を表現する場合は、FILE_PATHみたいに変数名を大文字で書くことが慣習とされているみたいです。
[https://maku77.github.io/python/syntax/const.html](url)

2023-06-05 09:05 UTC, kawanoichi reviewed
![207544](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/08a14fcf-ccb1-4f8e-ae16-3da2d5965507)

2023-06-05 09:06 UTC, kawanoichi approved these changes

2023-06-05 09:06 UTC, kawanoichi approved these changes

2023-06-05 13:07 UTC, bizyutyu approved these changes
リクエストの対応ありがとう！
お疲れ様です！！LGTM！！

2023-06-05 13:07 UTC, merged