close #16 色の識別
KatLab-MiyazakiUniv/etrobocon2023 pull request #30
Opened 2023-05-30 09:32 UTC by ykimura0726

# チェックリスト

- [ ] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点

色を識別するColorJudgeクラスの作成のため、module/Calculator下に以下のファイルを追加。
- ColorJudge.h
- ColorJudge.cpp

test直下にダミーテストColorJudgeTest.cppを追加。

test下にtest_dataのディレクトリを追加。test_data下に判定に必要なRGB値を書き込んだRgbData.hを追加。

CMakeList.txtに以下の文を追加。
include_directories(${PROJECT_SOURCE_DIR}/test/test_data)

clang-formatが通りませんでした。エラー箇所全てがコメントがある行を参照しているため、コメントの書き方が原因だと考えていますが、自動整形がこのコメントの書き方になるため、他に原因があるかもしれません。現在原因究明にあたっています。

# 動作テスト

## 添付資料

2023-06-02 11:28 UTC, miyashita64 requested changes
フォーマットは[clang-formatの調査](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/pull/32)でやってる↓のコマンドで通る？
`$ clang-format -i -style=file ファイル名`

2023-06-02 11:28 UTC, miyashita64 commented on module/Calculator/ColorJudge.cpp
> +  int min;
`minValue`の方がいいかな

2023-06-02 11:28 UTC, miyashita64 commented on module/Calculator/ColorJudge.cpp
> +  int min = std::min({ _rgb.r, _rgb.g, _rgb.b });
同様
```suggestion
  int maxValue = std::max({ _rgb.r, _rgb.g, _rgb.b });
  int minValue = std::min({ _rgb.r, _rgb.g, _rgb.b });
```

2023-06-02 14:18 UTC, YKhm20020 commented
> フォーマットは[clang-formatの調査](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/pull/32)でやってる↓のコマンドで通る？ `$ clang-format -i -style=file ファイル名`

通りました。ありがとうございます🙏

2023-06-02 15:02 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/210727)

2023-06-03 10:18 UTC, aridome222 approved these changes
一通り目を通した感じ大丈夫そう！
![LGTM](https://image.lgtmoon.dev/189216)

2023-06-03 15:12 UTC, KakinokiKanta approved these changes
switch文じゃない方が良いかな？

2023-06-03 15:12 UTC, KakinokiKanta commented on module/Calculator/ColorJudge.cpp
> +  }
C++だと「==」で文字列の比較が行えるから、strcmpはあんまり使わないイメージがある。可読性の面でも「str == "BLACK"」の方が見やすいし変えてほしいかな。後これだけ「else if」を列挙しているなら、「switch case」の方が良いんじゃない？switch文だと何か問題があるんだっけ？

2023-06-03 15:12 UTC, KakinokiKanta commented on module/Calculator/ColorJudge.cpp
> +  }
ここも「switch case」じゃダメかな？

2023-06-05 09:06 UTC, merged