close #11 指定速度に相当するPWM値を算出するSpeedCalculatorの追加
KatLab-MiyazakiUniv/etrobocon2023 pull request #31
Opened 2023-05-30 13:45 UTC by bizyutyu

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- SpeedCalculatorクラスの追加
- Controller内でMotorインスタンスのアドレスを保持するように変更

# 動作テスト
- Google Testにより、指定速度に相当するPWM値を算出する関数を呼び出せることを確認した
- 実機により、指定速度によって走行速度が変わることを確認した

## 実験データ
実験:速度300mm/sを指定し3秒間走行させた。(900mm進むと期待)
結果:隣のメジャーで780mm程度走行した。
考察:100mm程度の差は、斜めに進んだこととPIDで指定速度にするまでに若干のラグあることが原因だと思われる。

https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/83441177/93857beb-d577-4657-b903-af8daad1c4af

2023-06-01 13:00 UTC, kawanoichi requested changes
Controllerはいいような気がします。
テストはまだ見ていないです。

2023-06-01 13:00 UTC, kawanoichi commented on module/Calculator/SpeedCalculator.h
> +   * @param diffMileage 移動距離[mm/s]
```suggestion
   * @param diffMileage 移動距離[mm]
```
距離だよね？

2023-06-01 13:00 UTC, kawanoichi commented on module/Calculator/SpeedCalculator.cpp
> +  double speed = 1000.0 * diffMileage / diffTime;
結果は一緒ですが、単位を合わせるという意味では
```suggestion
  double speed = diffMileage / (diffTime / 1000.0);
```
もしくは
```suggestion
  double speed = diffMileage / (diffTime * 0.001);
```
の方がいいと思います。

2023-06-01 13:00 UTC, kawanoichi commented on module/Calculator/SpeedCalculator.h
> +   * @return 走行体全体の累計走行距離[mm]
```suggestion
   * @return 走行速度に相当するPWM値
```

2023-06-02 11:45 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.cpp
> +  double speed = 1000.0 * diffMileage / diffTime;
割り算からやってしまうと小さな値が切り捨てられてしまう場合があるので、掛け算を先にやってます。

2023-06-04 06:40 UTC, kawanoichi approved these changes
![210759](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/37ffa82d-8335-4aa6-bfa6-8d2ba4a69f46)

2023-06-04 11:57 UTC, aridome222 approved these changes
大丈夫だと思います！
![LGTM](https://image.lgtmoon.dev/80537)

2023-06-05 06:12 UTC, KakinokiKanta approved these changes
LGTM!

2023-06-05 13:08 UTC, merged