close #12 CIでclang-formatが通らない件の調査
KatLab-MiyazakiUniv/etrobocon2023 pull request #32
Opened 2023-05-31 09:11 UTC by kawanoichi

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
通らなかったclang-formatはコマンドで行うことで、解決できた。
よって、build、start、format、gtestを行うMakefileを作成した。

## 使用方法

### ビルドする
```
$ make build"
```
### 走行を開始する\(実機限定\)
```
$ make start"
```

### 指定ファイルをフォーマットする
```
$ make format FILES=test/PidTest.cpp"
```
### すべての変更ファイルをフォーマットする
```
$ make format"
```
### テストを実行する
```
$ make gtest"
```

# 動作テスト
実機、ノートPCどちらも動作確認済み

2023-06-02 05:27 UTC, aridome222 requested changes

2023-06-02 05:27 UTC, aridome222 commented on .gitignore
> +# vsdode設定ファイル
```suggestion
# vscode設定ファイル
```
細かいかもしれませんが一応

2023-06-02 15:00 UTC, aridome222 approved these changes

2023-06-04 10:35 UTC, YKhm20020 approved these changes
大丈夫だと思います！　少なくとも誤字脱字はないように見えます。
![201557](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/d406d3fa-de45-4d51-a38c-2adf9c9841cf)

2023-06-05 05:48 UTC, bizyutyu approved these changes
[![LGTM](https://image.lgtmoon.dev/210801)](url)

2023-06-05 05:49 UTC, merged