close #33 直進する
KatLab-MiyazakiUniv/etrobocon2023 pull request #38
Opened 2023-06-12 03:30 UTC by Negimarge

# チェックリスト

- [x] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
 - 直進の中間クラスを追加

# 動作テスト
 - warningのみでもbuildができませんでした

## 添付資料

2023-06-12 04:44 UTC, Negimarge commented
# make buildした時のログ
nakiz@LAPTOP-MUDS86N5:~/etrobo/workspace/etrobocon2023$ make build
cd /home/nakiz/etrobo && make app=etrobocon2023
invoke: make app=etrobocon2023
make[1]: Entering directory '/home/nakiz/etrobo/hrp3/sdk/workspace'
rm -rf /home/nakiz/etrobo/hrp3/sdk/workspace/.././OBJ/
Generating Makefile from ../common/Makefile.app.
make[2]: Entering directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
rm -f cfg1_out cfg1_out.o cfg1_out.c cfg1_out.syms cfg1_out.srec module_cfg.h module_cfg.c \#* *~ *.o
make[2]: Leaving directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
make[2]: Entering directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
  CFG[1]  module_cfg.h
[cfg.rb] Generated cfg1_out.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CFG[2]  module_cfg.h
[cfg.rb] Generated module_cfg.c
[cfg.rb] Generated module_cfg.h
make[2]: Leaving directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
make[2]: Entering directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
  CC      module_cfg.c
  CC      ../../library/t_perror.c
  CC      ../../library/strerror.c
  CC      ../../library/vasyslog.c
  CC      ../../target/ev3_gcc/TLSF-2.4.6/src/tlsf.c
  CC      ../common/ev3api/src/ev3api.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_battery.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_brick.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_fs.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_speaker.c
  CC      ../common/ev3api/src/ev3api_lcd.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_motor.c
  CC      ../common/ev3api/src/ev3api_newlib.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_sensor.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calibrator.cpp
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/EtRobocon2023.cpp
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/API/Controller.cpp
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/API/Measurer.cpp
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/API/Timer.cpp
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/ColorJudge.cpp
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/Mileage.cpp
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/Pid.cpp
make[2]: *** No rule to make target 'Logger.cpp', needed by 'Logger.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/SpeedCalculator.cpp
In file included from /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/SpeedCalculator.cpp:6:0:
/home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/SpeedCalculator.h: In constructor 'SpeedCalculator::SpeedCalculator(double)':
/home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/SpeedCalculator.h:33:16: warning: 'SpeedCalculator::targetSpeed' will be initialized after [-Wreorder]
   const double targetSpeed;
                ^~~~~~~~~~~
/home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/SpeedCalculator.h:31:7: warning:   'Pid SpeedCalculator::pid' [-Wreorder]
   Pid pid;
       ^~~
/home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calculator/SpeedCalculator.cpp:8:1: warning:   when initialized here [-Wreorder]
 SpeedCalculator::SpeedCalculator(double _targetSpeed)
 ^~~~~~~~~~~~~~~
make[2]: Leaving directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
make[1]: *** [../common/Makefile.workspace:97: app] Error 2
make[1]: Leaving directory '/home/nakiz/etrobo/hrp3/sdk/workspace'
fakemake on HRP3: make failed ... app=etrobocon2023
make: *** [Makefile:24: build] Error 1
nakiz@LAPTOP-MUDS86N5:~/etrobo/workspace/etrobocon2023$ git branch
  main
* ticket-33
  work-33
nakiz@LAPTOP-MUDS86N5:~/etrobo/workspace/etrobocon2023$ make build
cd /home/nakiz/etrobo && make app=etrobocon2023
invoke: make app=etrobocon2023
make[1]: Entering directory '/home/nakiz/etrobo/hrp3/sdk/workspace'
rm -rf /home/nakiz/etrobo/hrp3/sdk/workspace/.././OBJ/
Generating Makefile from ../common/Makefile.app.
make[2]: Entering directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
rm -f cfg1_out cfg1_out.o cfg1_out.c cfg1_out.syms cfg1_out.srec module_cfg.h module_cfg.c \#* *~ *.o
make[2]: Leaving directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
make[2]: Entering directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
  CFG[1]  module_cfg.h
[cfg.rb] Generated cfg1_out.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CFG[2]  module_cfg.h
[cfg.rb] Generated module_cfg.c
[cfg.rb] Generated module_cfg.h
make[2]: Leaving directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
make[2]: Entering directory '/home/nakiz/etrobo/hrp3/sdk/OBJ'
  CC      module_cfg.c
  CC      ../../library/t_perror.c
  CC      ../../library/strerror.c
  CC      ../../library/vasyslog.c
  CC      ../../target/ev3_gcc/TLSF-2.4.6/src/tlsf.c
  CC      ../common/ev3api/src/ev3api.c
  CC      ../common/ev3api/src/ev3api_battery.c
  CC      ../common/ev3api/src/ev3api_brick.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_fs.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_speaker.c
  CC      ../common/ev3api/src/ev3api_lcd.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_motor.c
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CC      ../common/ev3api/src/ev3api_newlib.c
  CC      ../common/ev3api/src/ev3api_sensor.c
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Calibrator.cpp
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-std=gnu++11' is valid for C++/ObjC++ but not for C
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/EtRobocon2023.cpp
  CXX     /home/nakiz/etrobo/hrp3/sdk/workspace/etrobocon2023/module/API/Controller.cpp
  CXX     /home/naki [...]

2023-06-12 04:52 UTC, Negimarge commented
#make build時のスクリーンショット
![スクリーンショット (7)](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/117429880/c787aa79-dbfc-441a-8e59-9bbe2e8bde6d)
![スクリーンショット (8)](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/117429880/712e35a9-6ba1-411b-b3b5-86d212e6b17e)
![スクリーンショット (9)](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/117429880/0c0fdf7e-ce6e-44bb-b2b5-8b7234ec1ceb)

2023-06-27 16:15 UTC, KakinokiKanta commented
buildができないってのは、自分のPCのローカルでってこと?
CIは通ってると思うんだけど

2023-06-28 05:23 UTC, miyashita64 requested changes
無理に揃える必要はないけど、できるだけ回頭と近い形にしてほしい

2023-06-28 05:23 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +    adjustmentPwm = static_cast<int>(pid.calculatePid(error));
左右の誤差等、この辺りのどの動作にも共通する誤差は、SpeedCalculator辺りが調整べきことな気がする。(今できないけど)

実際に走らせてみて、「同じpwm値を指定しているのに、斜めに走る」って問題が出てからSpeedCalculatorを拡張する方がいいと思う。

2023-06-28 05:23 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +  if(runPreconditionJudgement() != true) {
好みの話
```suggestion
  if(!runPreconditionJudgement()) {
```

2023-06-28 05:23 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +  int initialLeftMotorCount = Measurer::getLeftCount();
メンバで持っていいと思う。

2023-06-28 05:23 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +                                 currentRightMotorCount, currentLeftMotorCount)
別コメントで挙げた
①左右の誤差はSpeedCalculatorが担うべき
②init〇〇Countをメンバする
を適用するなら、

current〇〇Countは、事後条件判定の中で取得してもいいと思う。色指定の場合はMotorCount必要ないし。

2023-06-28 05:23 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +bool Straight::runPreconditionJudgement()
オーバーライド前提なら、return false;だけ書いて、オーバライドできていない異常事態でも即座に動作を終了する方がいいと思った。

2023-06-28 05:23 UTC, miyashita64 commented on module/Motion/Straight.h
> +   * @param _speed       目標速度[mm/s]
```suggestion
   * breif コンストラクタ
   * @param _targetValue 目標値 目標距離か目標色　オーバーライド必須
   * @param _speed       目標速度[mm/s]
   * @note オーバーライド必須
```
かな

他も同様

2023-06-28 05:23 UTC, miyashita64 commented on module/Motion/Straight.h
> +  virtual bool runPreconditionJudgement();
is〇〇の方がbool値を返すことが明示的だと思う

2023-06-29 05:55 UTC, bizyutyu requested changes

2023-06-29 05:55 UTC, bizyutyu commented on module/Motion/Straight.h
> +  virtual void logRunning();
レビュー遅くなりました。
今気づいてる箇所だけ。修正お願いします。
```suggestion
  /**
   * @brief 実行のログを取る
   */
  void logRunning();
```

2023-06-29 08:45 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +bool Straight::runPreconditionJudgement()
そもそもオーバライド前提の関数は基底クラスのcppで実装しなくていいのかな？

2023-07-01 07:23 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +    logger.logWarning("The speed value passed to \"target\"Straight is 0");
```suggestion
    logger.logWarning("The speed value passed to \"target\" Straight is 0");
```

2023-07-01 07:23 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +    snprintf(buf, BUF_SIZE, "The pwm value passed to \"target\"Straight is %d", pwm);
```suggestion
    snprintf(buf, BUF_SIZE, "The pwm value passed to \"target\" Straight is %d", pwm);
```

2023-07-01 07:23 UTC, miyashita64 commented on module/Motion/Straight.h
> +  virtual bool isRunPreconditionJudgement();
```suggestion
  virtual bool isMetPrecondition();
```
とかのがいいかな？

2023-07-01 07:23 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +  snprintf(buf, BUF_SIZE, "Run \"targetValue\"Straight (\"targetValue\": %d, targetSpeed: %f)",
```suggestion
  snprintf(buf, BUF_SIZE, "Run \"targetValue\" Straight (\"targetValue\": %d, targetSpeed: %f)",
```

2023-07-01 07:57 UTC, KakinokiKanta approved these changes
![a](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/105735727/a110d3fa-8dce-4f96-891d-4bbfd67f3198)

2023-07-01 07:57 UTC, miyashita64 approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/69404)

2023-07-01 07:57 UTC, aridome222 approved these changes
LGTM!
https://cdn-ak.f.st-hatena.com/images/fotolife/o/okatat/20200210/20200210132940.jpg

2023-07-01 07:59 UTC, YKhm20020 approved these changes
LGTM!　お疲れ様でした🙇
![203547](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/143775d7-a460-418c-a6d7-4946b8b62239)

2023-07-01 08:01 UTC, bizyutyu approved these changes
![LGTM](https://image.lgtmoon.dev/213910)

2023-07-01 08:01 UTC, merged