close #34 回頭する
KatLab-MiyazakiUniv/etrobocon2023 pull request #40
Opened 2023-06-12 09:26 UTC by desty505

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
角度指定による回頭動作を行うクラスを追加しました
回頭動作をまとめたクラスを追加しました
角度指定による回頭動作のテストファイルを追加しました

# 動作テスト

# 今後について
プルリクを書いている途中に私が実装しているものも方向性が違うことに気付きました
すぐに修正しますが、とりあえずプルリクをあげたかったのであげました
（このコメントは修正したときに消します）

2023-06-18 17:11 UTC, KakinokiKanta requested changes
遅くなって申し訳ないんだけど、眠すぎてちゃんと読めてないから、続きは明日見ます。

2023-06-18 17:11 UTC, KakinokiKanta commented on module/Motion/Motion.cpp
> + * @author kodama0720 mutotaka0426
```suggestion
 * @author desty505
```
ここは今年のリポジトリに追加した人で良いよ

2023-06-18 17:11 UTC, KakinokiKanta commented on module/Motion/Motion.h
> + * @author kodama0720 mutotaka0426
```suggestion
 * @author desty505
```
ここも

2023-06-18 17:11 UTC, KakinokiKanta commented on module/common/Logger.cpp
> + * @author sap2368 mutotaka0426
```suggestion
 * @author desty505
```
ここも

2023-06-18 17:11 UTC, KakinokiKanta commented on module/common/Logger.h
> + * @author sap2368 mutotaka0426
```suggestion
 * @author desty505
```
ここも

2023-06-18 17:11 UTC, KakinokiKanta commented on module/common/SystemInfo.h
> + * @author mutotaka0426
```suggestion
 * @author desty505
```
ここもだね

2023-06-19 02:48 UTC, aridome222 reviewed
柿木先輩の指摘通り修正してもらえれば、見たところ大丈夫だと思います。

2023-06-19 02:48 UTC, aridome222 commented on module/Motion/Rotation.cpp
> +  int rightSign = isClockwise ? -1 : 1;
時計回りなら、なぜ「leftSign」が1、「rightSign」が-1になるのかがよく分かりませんでした。
ここらへんが理解できなかったので、解説してもらえると助かります。

2023-06-19 08:18 UTC, miyashita64 requested changes
距離だけを考えてたからかもしれんけど、全体的に目標距離により過ぎだと思った。
修正お願いします。

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.h
> +   * @param targetValue 回頭の条件値　色または回頭角度
```suggestion
   * @brief 直進する際の事前条件判定をする
   * @param targetValue 回頭の条件値　色または回頭角度
   * @note オーバーライド必須
```
の方がいいかな。@remarkでもいいけど。

https://cercopes-z.com/Doxygen/cmd-brief-dxy.html

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.h
> +   * オーバーライド必須
これも

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  virtual bool run_precondition_judgement(int targetValue);
```suggestion
  virtual bool runPreconditionJudgement(int targetValue);
```

キャメルケースでお願いします。

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  virtual bool run_postcondition_judgement(double leftMileage, double rightMileage);
これもキャメルケースでお願いします

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  virtual bool run_postcondition_judgement(double leftMileage, double rightMileage);
これ、左右の車輪の走行距離渡してるけど、この時点で終了条件と走行距離に関係はないから、関数内で値を取得する方が自然だと思う。
(開始時の回転数はメンバとして保持しておく)

2023-06-19 08:18 UTC, miyashita64 commented on module/common/SystemInfo.h
> +static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
しばらく使わないから消して欲しい

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  : targetValue(_targetValue), targetSpeed(_targetSpeed), isClockwise(_isClockwise)
この時点ではtargetValueはなくていいかな。
目標距離だよね？

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  }
これは事前条件に含めてもいいような

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  if(run_precondition_judgement(targetValue) != true) {
```suggestion
  if(!run_precondition_judgement(targetValue)) {
```

好みの話

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +    return;
ここでもwarning出すべきだと思う。

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  double targetRightDistance = rightMileage + targetDistance * rightSign;
これは終了条件を満たしているかの関数内で計算することかな。

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +          * rightSign;
これも終了条件判定の中かな

2023-06-19 08:18 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +    if(run_postcondition_judgement(leftMileage, rightMileage) != true) break;
事後条件って終了時に満たしているべき条件であって、終了するための条件じゃないと思う。

2023-06-19 08:26 UTC, bizyutyu requested changes

2023-06-19 08:26 UTC, bizyutyu commented on module/Motion/Rotation.cpp
> +          * rightSign;
今年は去年のコードと違って、run_postcondition_judgementで事後条件判定を行っている関係で、diffLeftDistanceとdiffRightDistanceは使ってないようなので消してOKだと思う。

2023-06-19 08:28 UTC, kawanoichi requested changes

2023-06-19 08:28 UTC, kawanoichi commented on module/common/Logger.cpp
> +  system("bash ./etrobocon2022/scripts/organize_logfile.sh");
```suggestion
  system("bash ./etrobocon2023/scripts/organize_logfile.sh");
```

2023-06-19 08:29 UTC, bizyutyu commented on module/Motion/Rotation.cpp
> +          * rightSign;
上で宮下さんが指摘してくれていたのと同じことだったので、そちらに対応してくれればOKです！

2023-06-19 08:45 UTC, bizyutyu requested changes

2023-06-19 08:45 UTC, bizyutyu commented on module/Motion/Rotation.cpp
> +  char buf[BUF_SIZE];
これは必要ないはず。

2023-06-19 09:02 UTC, desty505 commented on module/Motion/Rotation.cpp
> +  : targetValue(_targetValue), targetSpeed(_targetSpeed), isClockwise(_isClockwise)
目標距離です。
消しておきます。

2023-06-19 09:02 UTC, desty505 commented on module/common/SystemInfo.h
> +static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
消すのはサーバのポート番号だけですか？

2023-06-19 09:18 UTC, desty505 commented on module/Motion/Rotation.cpp
> +          * rightSign;
去年の名残で間違えて残していました。
今、必要なさそうなので消しておきます。

2023-06-19 09:18 UTC, desty505 commented on module/Motion/Rotation.cpp
> +          * rightSign;
了解しました。

2023-06-19 10:52 UTC, bizyutyu commented on module/common/SystemInfo.h
> +static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
行ごと消して良かったと思うよ。

2023-06-19 11:50 UTC, desty505 commented on module/Motion/Rotation.cpp
> +  int rightSign = isClockwise ? -1 : 1;
Signの変数は車輪の回転方向の係数をあらわしています。（leftSignが左車輪、rightSignが右車輪）
なので、左車輪の回転が前方向（ leftSign = 1 ）かつ右車輪の回転が後ろ方向（ rightSign = -1）だと、
時計回りに回転します。

こういう感じの説明になるのですが、コメントアウトで追加した方がいいですか？

2023-06-19 12:02 UTC, desty505 commented on module/common/SystemInfo.h
> +static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
了解しました。
ちなみに、RADIUSとTREADも消すのかどうかをお聞きしたいです。

2023-06-19 12:04 UTC, miyashita64 requested changes
ごめん、targetValueが指定角度と指定色を兼ねるってコメント見落としてた。そういう作りにするなら、コンストラクタで初期化しても大丈夫です。

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Motion.h
> + * @author desty505s
```suggestion
 * @author desty505
```

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  double rightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
角度(距離)指定だけでしか使わないから、ここで計算する必要ないと思う。

もしくは、色指定でも回頭した角度を保持したいってことならメンバ変数として保持すべきだと思う。

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Rotation.h
> +   * @param _targetValue 回転角度(deg) 0~360
```suggestion
```

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Rotation.h
> +   * @brief 直進する際の事前条件判定をする
```suggestion
   * @brief 回頭する際の事前条件判定をする
```

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Rotation.h
> +   * @brief 直進する際の事後条件判定をする　返り値が真でモーターが止まる
```suggestion
   * @brief 回頭する際の事後条件判定をする　返り値が真でモーターが止まる
```

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  virtual bool runPreconditionJudgement(double targetSpeed);
```suggestion
  virtual bool isMetPrecondition(double targetSpeed);
```

とかで
true: 満たしている
false: 満たしていない
の方が直感的だと思った(任意)

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  virtual bool runPostconditionJudgement(double leftMileage, double rightMileage);
これも命名変えた方が満たす/満たさないのtrue/falseはわかりやすいと思う(任意)

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  return false;
okなときにfalseを返してngのときにtrueを返すのは直感的じゃない気がする。
関数名を否定的なfailedPrecondition()にするとか、真偽を逆にしてisMet〜とか、にした方がいいと思う

2023-06-19 12:04 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  int targetValue;   // 回転角度(deg) 0~360 もしくは 指定色
これ前のプルリクからこのコメントしてたなら見逃してたごめん。

このコメント通りで指定角度も指定色もint型のtargetValueとして扱うなら(これが綺麗かはさておき)、コンストラクタでtargetValueを初期化しても大丈夫。

2023-06-19 12:04 UTC, miyashita64 commented on module/common/SystemInfo.h
> +static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
ポートだけでok

2023-06-19 12:06 UTC, bizyutyu commented on module/common/SystemInfo.h
> +static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
確認したところ、RADIUSとTREADの行はそのままで良いみたいです。

2023-06-20 14:25 UTC, desty505 commented on module/Motion/Rotation.cpp
> +  double rightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
メンバ変数として保持するように書き直したつもりですが、
やり方があっているか分からないので確認いただきたいです。

2023-06-21 03:35 UTC, aridome222 commented on module/Motion/Rotation.cpp
> +  int rightSign = isClockwise ? -1 : 1;
なぜ左右の車輪が同じ方向に回転しないのかが疑問に思います。
左右の車輪がそれぞれ異なる方向に回転した場合の、走行体の動きのイメージができませんでした。

コメントが長くなるようであれば、追加しなくてもいいです。

2023-06-21 08:10 UTC, miyashita64 requested changes
Loggerのエラーはまだよくわかってません。

2023-06-21 08:10 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  double rightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
```suggestion
  // 呼び出し時の走行距離
  initLeftMileage = Mileage::calculateWheelMileage(Measurer::getLeftCount());
  initRightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
```

①メンバ変数は.cpp側では型定義(double)しなくていい
②命名は、初期の走行距離だとわかるように`init`とか付けてほしい(.h側も要変更)

2023-06-21 08:10 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  return true;
ここで判定してる事後条件はどういう意図？

2023-06-21 08:10 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  double rightMileage;  // クラス呼び出し時の右車輪の走行距離
`init`とか付けて、初期の値であることを明示してほしい

```suggestion
  double initLeftMileage;   // クラス呼び出し時の左車輪の走行距離
  double initRightMileage;  // クラス呼び出し時の右車輪の走行距離
```

2023-06-21 08:10 UTC, miyashita64 commented on module/Motion/logfile.txt
> +log highlight-text
紛れ込んでる？

2023-06-21 08:10 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +    if(!isMetPostcondition(leftMileage, rightMileage)) break;
①は対応してほしいです。②は好みです。

①事後条件は「満たしたから終了！」って条件ではなくて、「終了時に満たしてるから正常終了」って条件だと思うから、終了条件(もしくは継続条件)みたいに使うのは違うと思う。

②好みの話になるけど、whileの継続条件に入れてよくない？(postconditionを満たさない間継続)
場所の話で関数名は①で指摘したとおり事後条件ではないと思う。
```suggestion
  while(!isMetPostcondition(leftMileage, rightMileage)) {
```

2023-06-21 10:36 UTC, desty505 commented on module/Motion/Rotation.cpp
> +  return true;
ここの部分は質問するのを忘れていました。すみません。

何もオーバーライドをしなかった時(そんなことがあるのかは、よくわかってないです)に、
ずっと回頭し続けるのはよくないかなと思って、
デフォルトの事後条件として、
回頭を1周行ったら終了するようにしました。

余計そうなので消しますか？

2023-06-21 10:40 UTC, desty505 commented on module/Motion/Rotation.cpp
> +    if(!isMetPostcondition(leftMileage, rightMileage)) break;
質問を返してしまって申し訳ないのですが、

ここで必要なのは、
事後条件と終了条件のどちらなのか分かってないのですが、
どちらがいいと思いますか？

2023-06-21 13:09 UTC, desty505 commented on module/Motion/Rotation.cpp
> +  int rightSign = isClockwise ? -1 : 1;
回転方向の係数というワードだけ追加しておきます

2023-06-21 14:22 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  return true;
なるほど。
true返すだけでいいと思ってたけど、
- isMetPostcondition()を継続条件を判定する処理にするならfalse(回頭しない)
- isMetPostcondition()を終了条件を判定する処理にするならtrue(回頭しない)
にした方が、万一オーバーライドせずに実行したときに影響が少ないかな

2023-06-21 14:25 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +    if(!isMetPostcondition(leftMileage, rightMileage)) break;
終了条件(もしくは継続条件)がいいと思う。
事前条件定義してるから事後条件ある方がそれっぽいけど、検証すべき事後条件あんまり思いつかない。

2023-06-23 12:22 UTC, kawanoichi commented on test/LoggerTest.cpp
> + * @author sap268 mutotaka0426
```suggestion
 * @author desty505
```

2023-06-23 12:24 UTC, KakinokiKanta approved these changes
LGTM

2023-06-24 07:11 UTC, miyashita64 approved these changes
@kawanoichi の指摘以外はいいと思います。お疲れ様‼︎

![LGTM](https://image.lgtmoon.dev/138845)

2023-06-24 13:08 UTC, bizyutyu approved these changes
大変なタスクお疲れ様です！
![LGTM](https://image.lgtmoon.dev/213087)

2023-06-24 14:00 UTC, kawanoichi approved these changes
![15417](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/4d2a81f8-650d-4cb0-927e-8e23abf0aa41)

2023-06-25 04:15 UTC, merged