close #37 ライントレースの中間クラスを作成する
KatLab-MiyazakiUniv/etrobocon2023 pull request #44
Opened 2023-06-26 08:08 UTC by YKhm20020

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
module/Motion 下に以下のファイルを追加。
- LineTracing.h
- LineTracing.cpp

[イテレーション中に同じ変更を含む場合の対処](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/wiki/%E3%82%A4%E3%83%86%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E4%B8%AD%E3%81%AB%E5%90%8C%E3%81%98%E5%A4%89%E6%9B%B4%E3%82%92%E5%90%AB%E3%82%80%E5%A0%B4%E5%90%88%E3%81%AE%E5%AF%BE%E5%87%A6)で取り込んだところ、もとのブランチが消えたのでプルリク上げ直しています。正しく手順通りにできていれば作業内容は消えていないはずです。僕のは消えませんでした。宮下さんありがとうございます🙇

追記：
プルリク消えた件はブランチ移動を忘れたせいかもしれないです。申し訳ありません🙇

あと、ヘッダファイルの仮想関数化についてなのですが、virtual をそもそもつけるかと、つける場合はvirtualを記述したあとに = 0 をつけるときとつけないときの違いがあるか、それによって挙動が変わったりするのかがわかっていません。
根木原君によると、関数の中身（引数ではなく実際のコード）がある場合は virtual と = 0 をつけるみたいです。

# 動作テスト
子クラス実装でライントレース関係全体の Test を作成します。今のところコンパイルエラーは起きていないことだけ確認できています。

2023-06-27 16:10 UTC, KakinokiKanta requested changes
マジでレビュー遅くなって申し訳ない。
virtualに関しては、俺も調べてみたけど今の状態で良いように感じる。
ちょっとした修正だけお願いします。

ごめん調べ直したら、中身を書くのは不適切かも

2023-06-27 16:10 UTC, KakinokiKanta commented on module/Motion/LineTracing.cpp
> +  sign = isLeftEdge ? -1 : 1;
```suggestion
  edgeSign = isLeftEdge ? -1 : 1;
```
signだけだと何に対するものなのかわかりにくいから変更してほしい

2023-06-27 16:10 UTC, KakinokiKanta commented on module/Motion/LineTracing.h
> +  virtual bool isMetPrecondition(int pwm, double targetDistance) = 0;
```suggestion
  virtual bool isMetPreCondition(int pwm, double targetDistance) = 0;
```
じゃない？

2023-06-27 16:10 UTC, KakinokiKanta commented on module/Motion/LineTracing.h
> +  virtual bool isMetPostcondition(double initLeftMileage, double initRightMileage) = 0;
```suggestion
  virtual bool isMetPostCondition(double initLeftMileage, double initRightMileage) = 0;
```
これも

2023-06-28 05:45 UTC, miyashita64 requested changes
レビュー遅くなってすみません。
いくつか修正お願いします。

オーバーライド前提の関数は規定クラス側で実装した方がいいか、ないか方がいいかわからないので意見欲しいです。

2023-06-28 05:45 UTC, miyashita64 commented on module/Motion/LineTracing.h
> +  virtual bool isMetPostcondition(double initLeftMileage, double initRightMileage) = 0;
init〇〇Countはメンバ変数で持ってるから引数で渡す必要はないかな

2023-06-28 05:45 UTC, miyashita64 commented on module/Motion/LineTracing.h
> +  virtual bool isMetPrecondition(int pwm, double targetDistance) = 0;
前に@negiamargeが言ってた気がするけど、
preconditionは一単語でpost conditionは二単語だけど、表記を揃えるために一単語扱いしてるらしい。

2023-06-28 05:45 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
> +    pwm(_pwm),
ここは、目標速度を受け取ってほしい

2023-06-28 05:45 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
> +    // PID計算
```suggestion
    // 目標速度に対するpwm値を計算
    basePwm = // SpeedCalculatorでpwm値を計算する
    // PIDで旋回値を計算
```
pwm指定でなく速度指定したいからこんな感じの処理が加わるばす

2023-06-28 05:45 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
> +    currentPid = pid.calculatePid(Measurer::getBrightness()) * sign;
左右のモータ間のPWM値の差が入るから、turnPwmとか〇〇Pwmの形がいいと思う

2023-06-28 05:45 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
> +bool LineTracing::isMetPrecondition(int pwm, double targetDistance)
オーバーライド前提のときって、基底クラス側に実装って書いた方がいいのかな？
個人的には呼び出されない関数の実装があるのって紛らわしいと思うんだけど。

2023-06-28 05:52 UTC, KakinokiKanta commented on module/Motion/LineTracing.h
> +  virtual bool isMetPrecondition(int pwm, double targetDistance) = 0;
そういえばそんなことを言ってましたね
了解です

2023-06-28 06:30 UTC, KakinokiKanta commented on module/Motion/LineTracing.cpp
> +bool LineTracing::isMetPrecondition(int pwm, double targetDistance)
今回みたいな純粋仮装関数とする時は、関数の実装以前に、そもそも関数定義は書かないの一般的みたいです。

参考文献
https://www.asahi-net.or.jp/~yf8k-kbys/newcpp24.html
独習C++ 3.5.4　純粋仮想関数と抽象クラス

2023-06-28 06:42 UTC, KakinokiKanta commented on module/Motion/LineTracing.cpp
> +bool LineTracing::isMetPrecondition(int pwm, double targetDistance)
なので、これらの関数の実装は派生クラス側に書いた方が良い気がします

2023-06-28 09:10 UTC, YKhm20020 commented on module/Motion/LineTracing.cpp
> +bool LineTracing::isMetPrecondition(int pwm, double targetDistance)
ありがとうございます。わかりました。
isMetPrecondition, isMetPostcondition の2つは実装部分だけ削除します。
コンパイルには通っていることを確認済みです🙆‍♀

2023-06-29 06:02 UTC, bizyutyu reviewed
遅くなりましたが、レビューしました。
気づいた箇所があったら改めてコメントします。

2023-06-29 08:40 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
> +    pwm(_pwm),
ごめん。
目標距離を目標速度にしてってことではなくて、pwm値を目標速度に置き換えてほしい。

目標距離は受け取らないままでもokかな？

2023-06-29 08:42 UTC, miyashita64 requested changes

2023-06-29 08:42 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
> +    // 目標速度に対するpwm値を計算
```suggestion
```

2023-07-01 11:25 UTC, kawanoichi approved these changes
![213908](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/c7fcd0dc-31ce-4202-adad-2ae7aaaf8d19)

2023-07-01 11:40 UTC, miyashita64 approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/80339)

2023-07-01 11:50 UTC, KakinokiKanta approved these changes
![LGTM](https://image.lgtmoon.dev/172858)

2023-07-01 11:51 UTC, merged