close #46 回頭の子クラスを作成する
KatLab-MiyazakiUniv/etrobocon2023 pull request #47
Opened 2023-06-30 03:37 UTC by desty505

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- AngleRotation.cpp AngleRotation.h の追加
- AngleRotationTest.cppの追加
- Rotation.cpp Rotation.hの内容変更
　- targetSpeedの型をint型からdouble型に変更（ミスの修正）
　- isMetPrecondition() と isMetPostcondition()の引数を変更（オーバーライドを行うため）
　- メンバ変数 targetValueを追加 （目標値を保持する変数）

# 動作テスト
googletestが通っていません。
エラー内容も調べたのですが、
私の力で解決できるか分からなかったので、slackの質問の方を見ていただきたいです。

2023-07-01 17:26 UTC, miyashita64 requested changes
とりあえず。
起きたらちゃんとみます

2023-07-01 17:26 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  double initRightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
double必要だった？

2023-07-01 17:26 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  virtual bool isMetPostcondition(double initLeftMileage, double initRightMileage, int leftSign,
メンバでinit〇〇は持ってるから引数で渡さなくでいいんじゃない

2023-07-01 17:26 UTC, miyashita64 commented on module/Motion/Rotation.cpp
>  }
親クラスの.cpp側はこの関数自体消していいかも

2023-07-01 17:34 UTC, desty505 commented on module/Motion/Rotation.cpp
> +  double initRightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
なぜかわからないんですが、ここのdoubleを消すとエラーが起きました。
目標角度まで回転せずに終了してしまいます。

以下にエラー内容を書いてます。
[ RUN      ] AngleRotationTest.runRight
Expected: (expected) <= (actual), actual: 180 vs 84
[  FAILED  ] AngleRotationTest.runRight (0 ms)
[ RUN      ] AngleRotationTest.runLeft
Expected: (expected) <= (actual), actual: 180 vs 84
[  FAILED  ] AngleRotationTest.runLeft (0 ms)

2023-07-02 02:18 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  double initRightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
isMetPostconsition()のfalseを返す条件(終了条件)を||じゃなく&&にするとどう？

2023-07-02 06:46 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  double initRightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
多分原因は、テスト中のtargetSpeedが高すぎるからかな？
targetSpeedを60.0に設定したらテストは通った。
去年は、実装もテストもpwm値で設定してたから、割ときれいに期待値を出せたけど、今回実装側だけ動的に値を出してるから、期待値の設定が難しい...どうするのがいいんだろう

2023-07-02 08:42 UTC, miyashita64 requested changes
テスト通らない問題は実装より、SpeedCalculatorあたりかdummyの問題な気がするから、一旦initはメンバ扱いでいいと思う。

2023-07-02 08:42 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  double targetSpeed;       // 目標速度
気づくのがすごく遅くなったけど、↓の方がいいかも

```suggestion
  SpeedCalculator speedCalculator;
```

2023-07-02 08:42 UTC, miyashita64 commented on module/Motion/Rotation.cpp
>      SpeedCalculator SpeedCalculator(targetSpeed);
ここでSpeedCalculatorをインスタンス化すると、目標速度へのPWM値のPID制御ができないから、コンストラクタでインスタンス化した方がいいかな
```suggestion
```

2023-07-02 08:42 UTC, miyashita64 commented on module/Motion/Rotation.cpp
>      int pwm = SpeedCalculator.calcPwmFromSpeed();
```suggestion
    int pwm = speedCalculator.calcPwmFromSpeed();
```

2023-07-02 08:42 UTC, miyashita64 commented on module/Motion/Rotation.cpp
>    int rightSign = isClockwise ? -1 : 1;
11行目について欄外だからここに書く

メンバとしてtargetSpeedじゃなくて、speedCalculatorを保持した方がいいかも。

```
Rotation::Rotation(double _targetSpeed, bool _isClockwise)
  : speedCalculator(_targetSpeed), isClockwise(_isClockwise)
{
}
```

2023-07-02 08:42 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  class Timer Timer;
こうかな？classってなんだっけ？

```suggestion
  Timer timer;
```

2023-07-02 08:42 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +    Timer.sleep(10);
```suggestion
    timer.sleep(10);
```

2023-07-02 09:28 UTC, desty505 commented on module/Motion/Rotation.h
> +  double targetSpeed;       // 目標速度
この場合って、事前条件判定のtargetSpeedはどういうふうに変更するのが適切なのでしょうか？

2023-07-02 10:22 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  double initRightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
どこかでtaargetAngleの値が変わってるっぽい？

![image](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/83441177/d1767f8f-57a3-4e0a-8189-e68cb99bc850)

2023-07-02 10:46 UTC, desty505 commented on module/Motion/Rotation.cpp
> +  double initRightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
了解しました。
確認します。
ありがとうございます。

2023-07-02 10:51 UTC, miyashita64 commented on module/Motion/Rotation.h
> +  double targetSpeed;       // 目標速度
ごめん。事前条件の判定でtargetSpeed使ってたね。こっちは戻してください。

2023-07-02 10:54 UTC, miyashita64 commented on module/Motion/Rotation.cpp
>      SpeedCalculator SpeedCalculator(targetSpeed);
targetSpeedをメンバにして↓みたいに、ループの外でSpeedCalculatorインスタンス化する方がいいかも
```
  SpeedCalculator speedCalculator(targetSpeed);
  while(isMetPostcondition(initLeftMileage, initRightMileage, leftSign, rightSign)) {
    // PWM値を設定する
```

2023-07-02 12:42 UTC, desty505 commented on module/Motion/Rotation.cpp
> +  double initRightMileage = Mileage::calculateWheelMileage(Measurer::getRightCount());
原因はAngleRotation.hのprivateにもisClockwiseを持っていたからぽいです。

dummyとかの問題ではなさそうです。

2023-07-02 14:04 UTC, miyashita64 approved these changes
LGTM!!お疲れ様！
![LGTM](https://image.lgtmoon.dev/213919)

2023-07-03 02:05 UTC, KakinokiKanta approved these changes
レビュー遅くなって申し訳ない!
LGTM!!
![LGTM](https://image.lgtmoon.dev/205312)

2023-07-03 06:19 UTC, kodama0720 requested changes
良いと思います
コメントだけ少し修正お願いします

2023-07-03 06:21 UTC, kodama0720 commented on module/Motion/Rotation.h
>     * @param _isClockwise 回頭方向 ture:時計回り, false:反時計回り
```suggestion
   * @param _isClockwise 回頭方向 true:時計回り, false:反時計回り
```

2023-07-03 06:21 UTC, kodama0720 commented on module/Motion/Rotation.h
>    bool isClockwise;         // 回頭方向 ture:時計回り, false:反時計回り
```suggestion
  bool isClockwise;         // 回頭方向 true:時計回り, false:反時計回り
```

2023-07-03 06:21 UTC, kodama0720 commented on module/Motion/AngleRotation.h
> +   * @param _isClockwise 回頭方向 ture:時計回り, false:反時計回り
```suggestion
   * @param _isClockwise 回頭方向 true:時計回り, false:反時計回り
```

2023-07-03 06:30 UTC, kawanoichi approved these changes
![213992](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/efbd7e48-228e-4fcd-80d2-b90b67c10ff6)

2023-07-03 06:44 UTC, aridome222 approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/135848)

2023-07-03 06:45 UTC, bizyutyu approved these changes
![LGTM](https://image.lgtmoon.dev/149998)

2023-07-03 06:46 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/90404)

2023-07-03 06:58 UTC, miyashita64 requested changes
テストが通ってない

2023-07-03 12:31 UTC, bizyutyu reviewed
自分の環境でmake gtestが通らなかったので、
一度、田中くんのローカル環境でmake gtestが通るか、確認して欲しいです。

2023-07-03 12:45 UTC, desty505 commented
> 自分の環境でmake gtestが通らなかったので、 一度、田中くんのローカル環境でmake gtestが通るか、確認して欲しいです。

自分の環境では通りました。

2023-07-03 12:59 UTC, bizyutyu approved these changes
OK!確認ありがとう！

2023-07-04 03:22 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/214075)

2023-07-05 09:20 UTC, merged