close #42 カメラシステムがロボットの状況を把握できるようにする
KatLab-MiyazakiUniv/etrobocon2023 pull request #50
Opened 2023-06-30 21:08 UTC by aridome222

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
etrobocon2023/server/flask_server.pyに、
- GETリクエストに対してロボットの状況を返す処理を追加
- POSTリクエストに対してロボットの状況を更新する処理を追加

# 動作テスト
1. etrobocon2023/serverで、`$ python3 flask_server.py`をコマンドで打ち、サーバを起動させる。
2. etrobocon2023-camera-systemで、`$ make run`を打つ
3. カメラシステム側のコマンドライン上で、notReadyが定期的に出力される
4. `$ curl -X POST -H "Content-Type: text/plain" -d '～' http://127.0.0.1:8000/robot_info/state`で、'～'の部分を'wait'や'start'、'lap'にすれば、ロボットの状況を変えられる。
5.  '～'の部分を'finish'にすれば、サーバへの定期的なリクエストの送信を終了する。

2023-07-01 05:44 UTC, kawanoichi commented on server/flask_server.py
> +def send():
```suggestion
def send() -> str:
```

2023-07-01 05:45 UTC, kawanoichi commented on server/flask_server.py
> +        robot_info["state"]:  サーバが持つロボットの状況
```suggestion
        robot_info["state"] (str):  サーバが持つロボットの状況
```

2023-07-01 05:45 UTC, kawanoichi commented on server/flask_server.py
>  def write():
```suggestion
def write() -> str:
```

2023-07-01 05:46 UTC, kawanoichi commented on server/flask_server.py
> +def update():
```suggestion
def update() -> str:
```

2023-07-01 05:46 UTC, kawanoichi commented on server/flask_server.py
> +        robot_info["state"]:  サーバが持つロボットの状況
```suggestion
        robot_info["state"] (str):  サーバが持つロボットの状況
```

2023-07-01 05:47 UTC, kawanoichi commented on server/flask_server.py
>  from flask import Flask, url_for, request
```suggestion
from flask import Flask, request
```
使ってないかな？

2023-07-01 05:49 UTC, kawanoichi requested changes
とりあえず書き方の修正お願いします。
[Wiki](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84(Python))

2023-07-01 05:56 UTC, kawanoichi commented on server/flask_server.py
>  def read():
```suggestion
def read() -> str:
```

2023-07-01 05:56 UTC, kawanoichi requested changes
ここもです

2023-07-01 09:23 UTC, miyashita64 requested changes

2023-07-01 09:23 UTC, miyashita64 commented on server/flask_server.py
> +# サーバが扱うロボットの情報
```suggestion
# サーバが扱うロボットの情報
# state
#     notReady: 通信未確立
#     wait:   開始合図待ち
#     start:  走行開始
#     lap:    LAPゲート通過, finish: 処理停止
```
みたいなコメントが欲しい

2023-07-02 08:36 UTC, bizyutyu approved these changes
個人的には大丈夫だと思います。
![LGTM](https://images.lgtmgen.org/bd85aae4-5489-40d1-a1ae-c8cfde03ea40)

2023-07-02 14:07 UTC, miyashita64 approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/213920)

2023-07-02 17:42 UTC, kawanoichi approved these changes
![149044](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/761656e1-8ba7-4ae0-bbd4-7f253a958973)

2023-07-03 04:14 UTC, KakinokiKanta approved these changes
LGTM

2023-07-03 06:47 UTC, merged