close #45 直進の子クラス作成
KatLab-MiyazakiUniv/etrobocon2023 pull request #51
Opened 2023-07-01 09:57 UTC by Negimarge

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
子クラスを追加

# 動作テスト
仮想テーブルが原因で動かないです

2023-07-05 12:29 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/214340)

2023-07-06 04:01 UTC, desty505 approved these changes
LGTM！
[![LGTM](https://image.lgtmoon.dev/5315)](url)

2023-07-06 06:05 UTC, KakinokiKanta requested changes
1箇所だけ修正お願い。ほかについては問題なさそう

2023-07-06 06:05 UTC, KakinokiKanta commented on test/DistanceStraightTest.cpp
> +#include "Measurer.h"
```suggestion
#include "Measurer.h"
#include "Controller.h"
```
テストの方は影響あるかわからんけど、Measurer.hできるだけ先にincludeしてほしい

2023-07-06 06:10 UTC, bizyutyu approved these changes
指摘されてる箇所以外は大丈夫だと思います。
![LGTM！](https://image.lgtmoon.dev/214418)

2023-07-07 09:40 UTC, Negimarge commented
なぜかAngleRotationTestが触ってないのに壊れました
なぜこうなったかはわかりません
1: [ RUN      ] AngleRotationTest.runRight
1: /home/runner/work/etrobocon2023/etrobocon2023/test/AngleRotationTest.cpp:42: Failure
1: Expected: (expected) <= (actual), actual: 180 vs 90.4
1: 
1: [  FAILED  ] AngleRotationTest.runRight (0 ms)
1: [ RUN      ] AngleRotationTest.runLeft
1: /home/runner/work/etrobocon2023/etrobocon2023/test/AngleRotationTest.cpp:69: Failure
1: Expected: (expected) <= (actual), actual: 180 vs 90
1: 
1: [  FAILED  ] AngleRotationTest.runLeft (0 ms)

2023-07-07 10:20 UTC, desty505 commented
> なぜかAngleRotationTestが触ってないのに壊れました
> なぜこうなったかはわかりません
> 1: [ RUN ] AngleRotationTest.runRight
> 1: /home/runner/work/etrobocon2023/etrobocon2023/test/AngleRotationTest.cpp:42: Failure
> 1: Expected: (expected) <= (actual), actual: 180 vs 90.4
> 1:
> 1: [ FAILED ] AngleRotationTest.runRight (0 ms)
> 1: [ RUN ] AngleRotationTest.runLeft
> 1: /home/runner/work/etrobocon2023/etrobocon2023/test/AngleRotationTest.cpp:69: Failure
> 1: Expected: (expected) <= (actual), actual: 180 vs 90
> 1:
> 1: [ FAILED ] AngleRotationTest.runLeft (0 ms)

AngleRotationTest.cppでMeasurer.hをincludeしてないことか、
Measurer::rightMotor->reset();
Measurer::leftMotor->reset();
でモータカウントをリセットしてないのが問題かも。
迷惑かけてすみません。

2023-07-07 13:18 UTC, bizyutyu reviewed
細々したところの変更をお願いします。

2023-07-07 13:35 UTC, bizyutyu requested changes
下記の指摘以外で、Straight.hの”事後条件”も‘‘終了条件‘に変更お願いします。

2023-07-07 13:35 UTC, bizyutyu commented on module/Motion/ColorStraight.h
> +   * @brief 直進する際の事後条件判定をする　返り値が真でモーターが止まる
```suggestion
   * @brief 直進する際の終了条件判定をする　返り値が真でモーターが止まる
```

2023-07-07 13:35 UTC, bizyutyu commented on module/Motion/DistanceStraight.h
> +   * @brief 直進する際の事後条件判定をする　返り値が真でモーターが止まる
```suggestion
   * @brief 直進する際の終了条件判定をする　返り値が真でモーターが止まる
```

2023-07-08 08:09 UTC, bizyutyu approved these changes
修正ありがとう！お疲れ様です。
![LGTM](https://image.lgtmoon.dev/214655)

2023-07-08 11:37 UTC, KakinokiKanta approved these changes

2023-07-08 11:38 UTC, merged