close #43 ライントレースの子クラス作成
KatLab-MiyazakiUniv/etrobocon2023 pull request #54
Opened 2023-07-02 11:35 UTC by YKhm20020

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
テストに通っていません。原因はそれぞれ、
cannot declare variable ‘cl’ to be of abstract type ‘ColorLineTracing’ は、抽象クラスのオブジェクトを生成しようとしているから。
expression list treated as compound expression in initializer は、コンストラクタがないから、らしいです。

以下エラー文です。
```
In file included from /home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:7:
/home/ykhm20020/etrobo/workspace/etrobocon2023/module/Motion/ColorLineTracing.h:38:8: error: ‘bool ColorLineTracing::isMetPrecondition(int, COLOR)’ marked ‘override’, but does not override
   38 |   bool isMetPrecondition(int basePwm, COLOR targetColor) override;
      |        ^~~~~~~~~~~~~~~~~
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp: In member function ‘virtual void etrobocon2023_test::ColorLineTracingTest_runToGetFirst_Test::TestBody()’:
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:23:22: error: cannot declare variable ‘cl’ to be of abstract type ‘ColorLineTracing’
   23 |     ColorLineTracing cl(targetColor, targetBrightness, gain, isLeftEdge);
      |                      ^~
In file included from /home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:7:
/home/ykhm20020/etrobo/workspace/etrobocon2023/module/Motion/ColorLineTracing.h:14:7: note:   because the following virtual functions are pure within ‘ColorLineTracing’:
   14 | class ColorLineTracing : public LineTracing
      |       ^~~~~~~~~~~~~~~~
In file included from /home/ykhm20020/etrobo/workspace/etrobocon2023/module/Motion/ColorLineTracing.h:10,
                 from /home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:7:
/home/ykhm20020/etrobo/workspace/etrobocon2023/module/Motion/LineTracing.h:43:16: note:     ‘virtual bool LineTracing::isMetPostcondition()’
   43 |   virtual bool isMetPostcondition() = 0;
      |                ^~~~~~~~~~~~~~~~~~
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp: In member function ‘virtual void etrobocon2023_test::ColorLineTracingTest_runLeftEdge_Test::TestBody()’:
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:53:22: error: cannot declare variable ‘cl’ to be of abstract type ‘ColorLineTracing’
   53 |     ColorLineTracing cl(targetColor, targetBrightness, gain, isLeftEdge);
      |                      ^~
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp: In member function ‘virtual void etrobocon2023_test::ColorLineTracingTest_runRightEdge_Test::TestBody()’:
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:79:22: error: cannot declare variable ‘cl’ to be of abstract type ‘ColorLineTracing’
   79 |     ColorLineTracing cl(targetColor, targetBrightness, gain, isLeftEdge);
      |                      ^~
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp: In member function ‘virtual void etrobocon2023_test::ColorLineTracingTest_runBackLeftEdge_Test::TestBody()’:
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:105:22: error: cannot declare variable ‘cl’ to be of abstract type ‘ColorLineTracing’
  105 |     ColorLineTracing cl(targetColor, targetBrightness, gain, isLeftEdge);
      |                      ^~
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp: In member function ‘virtual void etrobocon2023_test::ColorLineTracingTest_runBackRightEdge_Test::TestBody()’:
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:131:22: error: cannot declare variable ‘cl’ to be of abstract type ‘ColorLineTracing’
  131 |     ColorLineTracing cl(targetColor, targetBrightness, gain, isLeftEdge);
      |                      ^~
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp: In member function ‘virtual void etrobocon2023_test::ColorLineTracingTest_runZeroPWM_Test::TestBody()’:
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:156:22: error: cannot declare variable ‘cl’ to be of abstract type ‘ColorLineTracing’
  156 |     ColorLineTracing cl(targetColor, targetBrightness, gain, isLeftEdge);
      |                      ^~
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp: In member function ‘virtual void etrobocon2023_test::ColorLineTracingTest_runNoneColor_Test::TestBody()’:
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:189:22: error: cannot declare variable ‘cl’ to be of abstract type ‘ColorLineTracing’
  189 |     ColorLineTracing cl(targetColor, targetBrightness, gain, isLeftEdge);
      |                      ^~
make[3]: *** [CMakeFiles/etrobocon2023_test.dir/build.make:102: CMakeFiles/etrobocon2023_test.dir/test/ColorLineTracingTest.cpp.o] Error 1
make[3]: Leaving directory '/home/ykhm20020/etrobo/hrp3/sdk/workspace/etrobocon2023/build'
make[2]: *** [CMakeFiles/Makefile2:140: CMakeFiles/etrobocon2023_test.dir/all] Error 2
make[2]: Leaving directory '/home/ykhm20020/etrobo/hrp3/sdk/workspace/etrobocon2023/build'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/ykhm20020/etrobo/hrp3/sdk/workspace/etrobocon2023/build'
make: *** [Makefile:47: gtest] Error 2

```

![スクリーンショット 2023-07-02 201527](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/58d7c9db-7e19-42dd-b203-5c2c5292ff48)

# 動作テスト

## 添付資料
以下サイトの方法試しましたが、通りませんでした。
[「純粋仮想関数」について勉強しました](https://www.pgls-kl.com/article/article_118.html)

試した結果のエラー文は以下の通りでした。ポインタ外してみたのですが、その場合は上のエラー文と同じものが表示されました。

```
/home/ykhm20020/etrobo/workspace/etrobocon2023/test/ColorLineTracingTest.cpp:23:73: error: expression list treated as compound expression in initializer [-fpermissive]
   23 |    ColorLineTracing *cl(targetColor, targetBrightness, gain, isLeftEdge) = new ColorLineTracing();
      |                                                                        ^
```

2023-07-04 04:31 UTC, miyashita64 reviewed
たぶん、これで大体のテストは通るはず

2023-07-04 04:31 UTC, miyashita64 commented on test/ColorLineTracingTest.cpp
> +
多分必要ないです

2023-07-04 04:31 UTC, miyashita64 commented on test/ColorLineTracingTest.cpp
> +
モータカウントを比較するようなテストの場合は、以下の処理を追加すれば、モータカウントが安定するはずです。
事前条件を満たさない場合のテストでは省略可能。

```suggestion
Mesuarer::leftMotor->reset();
Mesuarer::rightMotor->reset();
```

Mesuarerで失敗したテストに関しても似たような変更で解決できると思いますが、Straight系統で変更されてるので、コンフリクトが面倒なので、Starightがマージされたmainを取り込む形がいいと思います。

2023-07-04 11:22 UTC, YKhm20020 commented on test/ColorLineTracingTest.cpp
> +
ありがとうございます、すべてのテストをパスすることができました🙇
基本動作の確認に入れそうです👍

2023-07-05 03:58 UTC, bizyutyu commented on test/ColorLineTracingTest.cpp
> +    EXPECT_GE(expected + error, actual);  // 実行後に走行した距離が許容誤差以下である
ローカル環境だと、以下の部分のテストが通らないのですが、原因が分かる方いますか？
ついでに、許容誤差との比較について理解しきれてないので説明して欲しいです。
<img width="1440" alt="スクリーンショット 2023-07-05 12 52 42" src="https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/132331737/d12d0d38-673b-44cd-b261-b993f1b5b30a">

2023-07-05 13:23 UTC, miyashita64 commented on test/ColorLineTracingTest.cpp
> +    EXPECT_GE(expected + error, actual);  // 実行後に走行した距離が許容誤差以下である
原因はわからんけど、テストの内容はおかしい。
ColorLinetraceは速度指定で処理してるけど、走行距離の期待値はbasePwmで計算してるから、計算が合わない方がむしろ自然。（ちなみに、自分の環境では通りました。）
結果が違うことだけ気になるけど、シード値を指定しても、WindowsとMacとで乱数生成器が異なるとかあるのかな？

昨年は、モータ出力をPWM値指定で決めてたから、テスト上では速度がある程度一定で、走行距離の期待値を計算できた。ただ、テスト上ではColorSensorのダミーが乱数でRGB値を返すから、PIDの調整やらで多少PWM値が変わる。乱数のシード値は指定してるから、頑張って処理を追えば正確な値は計算できるけど、実装が変わるたびに計算する必要があるから、そのあたりのブレを許容誤差としてやってた。
テストケースのコメントにもあるけど、「進んでいること」と「進み過ぎないこと(止まっていること)」をテストしてる。今見ると「ちょっとしか進んでない」ケースを考慮できてないけど。

今年は、SpeedCalculatorのPID制御も加わって、計算が複雑な上に、SpeedCalculatorのPID調整次第で、計算上のモータカウントは振れ幅がでかいから、走行距離の期待値を使うのは向いてないかもしれん

2023-07-05 15:28 UTC, bizyutyu commented on test/ColorLineTracingTest.cpp
> +    EXPECT_GE(expected + error, actual);  // 実行後に走行した距離が許容誤差以下である
回答ありがとうございます！
質問の"make gtest"はMacで試した結果なので、自分のWSL環境でも試して見ようと思います(こちらはまだ試せていません)。
WindowsとMacの同じ関数の乱数生成の違いについても、個人的に調査してみようと思います。

2023-07-07 11:41 UTC, KakinokiKanta requested changes
修正お願いします

2023-07-07 11:41 UTC, KakinokiKanta commented on test/ColorLineTracingTest.cpp
> +    EXPECT_GE(expected + error, actual);  // 実行後に走行した距離が許容誤差以下である
```suggestion
```
結論、これはいらないということで

2023-07-07 11:41 UTC, KakinokiKanta commented on test/ColorLineTracingTest.cpp
> +    int error = Mileage::calculateMileage(basePwm * 0.05 * 2, basePwm * 0.05 * 2);  // 許容誤差
```suggestion
```
以下で言っている通り、ここの処理はなくて良いよ

2023-07-07 12:15 UTC, miyashita64 requested changes
細々したことだけどお願いします。

2023-07-07 12:15 UTC, miyashita64 commented on module/EtRobocon2023.cpp
> +#include "DistanceLineTracing.h"
動作確認用だと思うので消してください

2023-07-07 12:15 UTC, miyashita64 commented on module/Motion/ColorLineTracing.cpp
> +  if(colorCount == JUDGE_COUNT) return false;
どちらかといえば、こっちの方がいいかも。

```suggestion
  if(colorCount >= JUDGE_COUNT) return false;
```

2023-07-07 12:15 UTC, miyashita64 commented on module/Motion/Straight.cpp
> +  SpeedCalculator SpeedCalculator(targetSpeed);
Straightに関しての変更は消してほしい

2023-07-07 12:15 UTC, miyashita64 commented on module/Motion/Straight.h
> +  Timer timer;
これも消して

2023-07-07 13:37 UTC, aridome222 approved these changes
一通り見て問題なかったので、問題ないと思います。
![LGTM](https://image.lgtmoon.dev/125604)

2023-07-07 15:25 UTC, bizyutyu approved these changes
問題ないと思う！大変なタスクお疲れ様です。
![LGTM](https://image.lgtmoon.dev/87055)

2023-07-08 04:39 UTC, KakinokiKanta approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/132479)

2023-07-08 04:48 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/88537)

2023-07-09 11:37 UTC, merged