close #57 SpeedCalculatorのpwm算出を左右の車輪ごとに行うように変更
KatLab-MiyazakiUniv/etrobocon2023 pull request #63
Opened 2023-07-05 08:25 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
現在のリモートmainブランチを修正して、SpeedCalculatorのpwm算出を左右の車輪ごとに行うように変更しました。
具体的には、
- calcPwmFromSpeedを削除
- calcRightPwmFromSpeedとcalcLeftPwmFromSpeedの追加
- 上記変更に伴う、直進・ライントレース・回頭・SpeedCalculatorテストファイルの一部変更（主に、calcPwmFromSpeedを使っている部分）
を行っています。
子クラス
# 動作テスト
自身のローカル環境でビルドとテストは通りました。
## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-07-05 14:03 UTC, miyashita64 requested changes
大体良いと思います。
基本動作とのコンフリクトが怖いけど

2023-07-05 14:03 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.cpp
> +  prevTime = currentTime;
ここでprevTime更新したら、prevLeftMileageと整合性取れないと思う

2023-07-09 05:29 UTC, bizyutyu reviewed
テストは通ってないですが、レビューしてもらえると助かります。
テストが通っていない理由については、完全には分かっていません。

2023-07-09 12:37 UTC, miyashita64 requested changes
ライントレースはマージしたので取り込みお願いします。

2023-07-09 12:37 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.cpp
> +  prevLeftTime = timer.now();
```suggestion
  int currentTime = timer.now();
  prevRightTime = currentTime;
  prevLeftTime = currentTime;
```
の方がいいかも

2023-07-09 12:37 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.cpp
> +      = (diffRightMileage == 0.0) ? -targetSpeed : calcSpeed(diffRightMileage, diffRightTime);
よくよく考えるとこっちの方が調整しやすいかも。
(もしかしたら、テストもこの処理で初速が上がりすぎてる可能性はある)

```suggestion
  double currentRightSpeed
      = calcSpeed(diffRightMileage, diffRightTime);
```

2023-07-09 12:37 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.cpp
> +  int currentRightTime = timer.now();
```suggestion
  int currentTime = timer.now();
```
メンバと紛らわしい気もする。

他は右左固有の値だからleft/rightついててもいいと思うから、ここだけ変えるかは任意で

2023-07-09 12:37 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.h
> +  double leftPwm;
メンバで持たなくてもいいかな？

2023-07-09 14:05 UTC, bizyutyu commented on module/Calculator/SpeedCalculator.cpp
> +  int currentRightTime = timer.now();
このままにしておこうと思います。

2023-07-09 14:20 UTC, miyashita64 commented on module/Calculator/SpeedCalculator.h
> +  double leftPwm;
ごめん、持たないとダメだ

2023-07-09 14:40 UTC, bizyutyu commented on module/Calculator/SpeedCalculator.h
> +  double leftPwm;
元に戻しておきました。自分の方も、ビルド確認せずpushしてたので気づかなかったです。ありがとうございます。

2023-07-10 16:11 UTC, miyashita64 requested changes
１か所だけleft/rightの修正お願いします。

2023-07-10 16:11 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +    Controller::setRightMotorPwm(leftPwm * rightSign);
```suggestion
    Controller::setRightMotorPwm(rightPwm * rightSign);
```

2023-07-11 06:16 UTC, Negimarge requested changes
AngleRotationのテストに対するものです。

2023-07-11 06:16 UTC, Negimarge commented on test/AngleRotationTest.cpp
> +    // EXPECT_LE(expected, actual);
コメントアウトしているのは通らないからですか？もし、通らないとしたら理由を教えてください。

2023-07-11 06:16 UTC, Negimarge commented on test/AngleRotationTest.cpp
> +    // EXPECT_LE(expected, actual);
ここも

2023-07-11 06:20 UTC, KakinokiKanta approved these changes
上のやつに対応してくれればOK！
![LGTM](https://image.lgtmoon.dev/170114)

2023-07-11 08:12 UTC, Negimarge approved these changes
LGTM

2023-07-11 08:17 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/12589)

2023-07-11 09:19 UTC, YKhm20020 approved these changes
LGTMです、お疲れ様でした！
![203589](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/e965c642-59f5-4231-aa4e-58702ecf2b55)

2023-07-11 09:20 UTC, merged