close #64 コマンドファイルを読み込み、Motionをインスタンス化後、順次実行する
KatLab-MiyazakiUniv/etrobocon2023 pull request #68
Opened 2023-07-10 13:30 UTC by aridome222

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
当初の予定よりも多くのファイルを作成、修正することになった。しかし、内容自体は少ないため、レビューをお願いいたします。
以下に作成・修正ファイルを示す。

etrobocon2023/datafiles下に
- BlockDeTreasureLeft.csv
- BlockDeTreasureRight.csv
- DoubleLoopLeft.csv
- DoubleLoopRight.csv
- LineTraceLeft.csv
- LineTraceRight.csv
（今後必要になるcsvファイルを作成しましたが、全て同じ内容です。全コマンドを試せるようにしました。）

etrobocon2023/module下に
- AreaMaster.cpp
- AreaMaster.h
- EtRobocon2023.cpp
- MotionParser.cpp
- MotionParser.h
（今回のタスクのメインです。全て確認をお願いします。）

etrobocon2023/module/Motion下に
- ColorLineTracing.cpp
- DistanceLineTracing
- LineTracing.cpp
（テストを通すために、ログとして表示されるpwm, basePwmを削除しました。）

etrobocon2023/module/common下に
- StringOperator.cpp
- StringOperator.h
（文字列の末尾の改行コードを消すクラスがどっかで必要だったため、去年のを取ってきました。）

etrobocon2023/test下に
- AreaMasterTest.cpp
- MotionParserTest.cpp
- StringOperaterTest.cpp
（AreaMasterTest以外はほとんど変更してないので、AreaMasterTestだけでも確認お願いします。）

etrobocon2023/test/gtest下に
- gtest_build.sh
（今回作成したdatafilesフォルダのパスを通して、csvファイルを読み込めるようにしました。）

etrobocon2023/test/test_data下に
- CommandParserTestData.csv
（MotionParserTestで使うファイルです。去年と同じです。）

# 動作テスト
実機テストは7/11にやります。

# 関連資料
issue64(https://github.com/KatLab-MiyazakiUniv/etrobocon2023/issues/64#issue-1793105588)

2023-07-10 15:08 UTC, miyashita64 requested changes
ぎりぎりで申し訳ないけど修正お願いします。

2023-07-10 15:08 UTC, miyashita64 commented on module/AreaMaster.cpp
> +#include <string>
多分、消して大丈夫

2023-07-10 15:08 UTC, miyashita64 commented on module/AreaMaster.h
> +   * @param area エリア名
エリア名だと文字列っぽい

```suggestion
   * @param area エリアの指定(Area型のEnum)
```

2023-07-10 15:08 UTC, miyashita64 commented on module/Motion/LineTracing.cpp
>             "(%.2f,%.2f,%.2f), isLeftEdge: %s)",
フォーマットで改行されないなら１行がいいかな
```suggestion
           "targetBrightness: %d, gain: (%.2f,%.2f,%.2f), isLeftEdge: %s)",
```

2023-07-10 15:08 UTC, miyashita64 commented on module/MotionParser.cpp
> +  const char* separator = ",";  // 行ごとにパラメータを読み込む
内容的には
```suggestion
  const char* separator = ",";  // 区切り文字
```

2023-07-10 15:08 UTC, miyashita64 commented on module/MotionParser.cpp
> +  while(fgets(row, BUF_SIZE, fp) != NULL) {
書くならこの辺？
```suggestion

  // 行ごとにパラメータを読み込む
  while(fgets(row, BUF_SIZE, fp) != NULL) {
```

2023-07-10 15:08 UTC, miyashita64 commented on module/EtRobocon2023.cpp
> +  AreaMaster blockDeTreasureAreaMaster(BlockDeTreasure, isLeftCourse, isLeftEdge, targetBrightness);
ついてた方がいいかな。
[記事](https://monozukuri-c.com/langcpp-funclist-enum-class/#toc-3)によっては型名(Area)の記述が必須らしい

```suggestion
  AreaMaster lineTraceAreaMaster(Area::LineTrace, isLeftCourse, isLeftEdge, targetBrightness);
  AreaMaster doubleLoopAreaMaster(Area::DoubleLoop, isLeftCourse, isLeftEdge, targetBrightness);
  AreaMaster blockDeTreasureAreaMaster(Area::BlockDeTreasure, isLeftCourse, isLeftEdge, targetBrightness);
```

2023-07-10 15:08 UTC, miyashita64 commented on test/AreaMasterTest.cpp
> +    Area area = LineTrace;
ほかのテストも同様
```suggestion
    Area area = Area::LineTrace;
```

2023-07-10 15:08 UTC, miyashita64 commented on test/gtest/gtest_build.sh
> +# cp ../logfiles/* etrobocon2023/logfiles/
消していいかな
```suggestion
```

2023-07-10 15:08 UTC, miyashita64 commented on test/AreaMasterTest.cpp
> +  }
ほかの4ファイル(2エリア * 左右)の呼び出しもやって欲しい

2023-07-10 15:54 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/95766)

2023-07-11 05:06 UTC, Negimarge approved these changes
LGTM

2023-07-11 06:25 UTC, KakinokiKanta requested changes
こまかいけど

2023-07-11 06:25 UTC, KakinokiKanta commented on module/AreaMaster.h
> +   * @param area エリアの指定(Area型のEnum)
```suggestion
   * @param area エリアの指定(Enum型のArea)
```
かな

2023-07-11 07:55 UTC, KakinokiKanta reviewed
LGTM
![LGTM](https://image.lgtmoon.dev/214983)

2023-07-11 08:03 UTC, desty505 approved these changes

2023-07-11 08:04 UTC, desty505 approved these changes
LGTM

2023-07-11 09:15 UTC, kodama0720 requested changes

2023-07-11 09:15 UTC, kodama0720 commented on module/MotionParser.h
> +  static bool convertBool(char* command, char* binaryParameter);
文字列のパラメータがbinaryParameterって変な気がします
stringParameterか、回転方向の文字列だけならturnDirectionとか？

2023-07-11 09:21 UTC, KakinokiKanta approved these changes

2023-07-11 12:08 UTC, miyashita64 commented on module/EtRobocon2023.cpp
> +  bool isLeftEdge = true;
調整的に↓みたいにしてほしい
```suggestion
  bool isLeftCourse = false;
  bool isLeftEdge = false;
```

2023-07-12 01:27 UTC, kodama0720 commented on test/StringOperaterTest.cpp
ファイル名　Operater → Operator

2023-07-12 07:56 UTC, miyashita64 commented on module/MotionParser.cpp
> +bool MotionParser::convertBool(char* command, char* StringParameter)
```suggestion
bool MotionParser::convertBool(char* command, char* stringParameter)
```

2023-07-12 07:56 UTC, miyashita64 commented on module/MotionParser.cpp
> +  char* param = StringOperator::removeEOL(StringParameter);
```suggestion
  char* param = StringOperator::removeEOL(stringParameter);
```

2023-07-12 12:48 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/204747)

2023-07-12 12:51 UTC, merged