close #3 モータを動かす
KatLab-MiyazakiUniv/etrobocon2023 pull request #7
Opened 2023-05-15 11:58 UTC by aridome222

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
etrobocon2023/moduleの直下にAPIフォルダ(etrobocon2023/module/API/)を作成し、
そこに以下の2つのファイルを追加。

- Controller.cpp 
- Controller.h

# 動作テスト

## 添付資料

2023-05-16 07:38 UTC, miyashita64 requested changes
迅速なプルリクお疲れ様です。
主に使ってない要素についてコメントしているので対応お願いします。
静的にするかは、ほかの人の意見も聞きたいです。

2023-05-16 07:38 UTC, miyashita64 commented on module/API/Controller.h
> +// #include "Measurer.h" // TODO 他の人がこのファイルを作成したら、このコメントアウトを消す
使わなくても動作確認できてるなら、includeしなくていいんじゃない？

2023-05-16 07:38 UTC, miyashita64 commented on module/API/Controller.h
> +  // Measurer measurer; // TODO Measurer.hを作成したら、このコメントアウトを消す
使ってないなら消していいんじゃない？

2023-05-16 07:38 UTC, miyashita64 commented on module/API/Controller.h
> +  static const int MOTOR_PWM_MIN = -100;
現状、ほかのクラスから呼び出す必要がないなら、privateでいいと思う。

2023-05-16 07:38 UTC, miyashita64 commented on module/API/Controller.h
> +  // void notifyCompletedToSimulator();
現状必要なさそうなものは消していいと思う。

2023-05-16 07:38 UTC, miyashita64 commented on module/API/Controller.h
> +  Controller();
特にコンストラクタやメンバ関数で、値が変わるようなメンバ変数を持ってないから、コンストラクタをなくして、ほかの関数を静的(static)な関数として宣言した方がいい気もするけど、どうでしょう？

2023-05-20 15:32 UTC, KakinokiKanta reviewed
遅くなって申し訳ない

2023-05-20 15:32 UTC, KakinokiKanta commented on module/API/Controller.cpp
> +
今年の競技内容的にアームを使わない気がするから、いらないかも…
ただ去年は、走行中にアームが勝手に上がってきちゃうのを抑えるために使おうとしてたけど、結局やらなかった覚えがあるんですけど、どうでしたっけ？ @miyashita64 @kawanoichi

2023-05-20 15:32 UTC, KakinokiKanta commented on module/API/Controller.h
> +  Controller();
単純にコンストラクタを記述しないってことですか？それとも静的なクラスにしてインスタンス化を禁止するってことですか？

2023-05-21 00:38 UTC, KakinokiKanta commented on module/API/Controller.h
> +  Controller();
単純にコンストラクタを無くすってことですか？それともインスタンス化を禁止するってことですか？

2023-05-21 00:59 UTC, KakinokiKanta commented on module/API/Controller.h
> +  Controller();
measurerで言ってる感じだと、インスタンス化の禁止の方ですかね？それなら宮下さんの提案してるやり方でいいと思います。

2023-05-21 04:31 UTC, bizyutyu commented
確認した感じ、他の人のレビューを反映してもらえれば良いと思います。

2023-05-21 05:54 UTC, miyashita64 commented on module/API/Controller.h
> +  Controller();
そう。
言い方悪かったけど、コンストラクタをなくすじゃなくて、privateにする(外部から呼び出せなくする)ことでコンストラクタの使用を禁止するです。

2023-05-21 06:03 UTC, kawanoichi commented on module/API/Controller.cpp
> +
@KakinokiKanta 
ブロック設置後の後退で、ブロックがアームから離れないことがある問題があって、その時にアームの上げ下げを行ってたような気がする。

2023-05-21 11:18 UTC, aridome222 commented on module/API/Controller.h
> +  Controller();
@miyashita64 Controller();をpublicではなく、privateの中に入れることでコンストラクタの使用を禁止するという認識で合っていますか？

2023-05-21 12:48 UTC, OnagaHaruki reviewed
締め切り直前のレビューになって申し訳ないです．
他の方々の指摘への対応をよろしくお願いします🙇‍♂️

2023-05-21 12:48 UTC, OnagaHaruki commented on module/API/Controller.h
> +  Controller();
質問に答えきれていなくて申し訳ないけど，コンストラクタを明示的に使用禁止にするには，publicでコンストラクタにdeleteを代入することもあるみたいです．
C++11以降だとそのほうが明示的にインスタンス化の禁止を示せるかもしれません．

参考資料
- [C++でstaticクラス](https://sygh.hatenadiary.jp/entry/2018/08/12/010257)
- [明示的なdefault/delete関数](https://yohe.gitbooks.io/cpp-14/content/chapter_1/core/explicit_default_func.html)

2023-05-21 14:19 UTC, aridome222 commented on module/API/Controller.h
> +  Controller();
@OnagaHaruki 色々調べて頂きありがとうございます。参考資料を元に明示的にインスタンス化の禁止をやってみました。

2023-05-21 15:45 UTC, miyashita64 commented on module/API/Controller.h
> +  Controller();
返信遅くなってごめん。
クラス内からのコンストラクタ呼び出しとかも禁止できるみたいだし、deleteで禁止する方法すごくいいと思う。

2023-05-21 16:39 UTC, KakinokiKanta commented on module/API/Controller.cpp
> +
今年の場合、ゲームエリア全体通してブロックが1つしかないので、いらないのかなって気がするんですけど、どう思いますか？ @miyashita64 @kawanoichi

2023-05-22 01:33 UTC, kawanoichi commented on module/API/Controller.cpp
> +
@KakinokiKanta @aridome222 
必要になってから開発すべきなのか、必要になるかもしれないものは開発しとくべきなのか...
どっちが正しいんだろう。
最終的に使わない機能を消す作業とかしないと思うから必要になったら開発するでいいかも

2023-05-22 01:34 UTC, miyashita64 commented on module/API/Controller.cpp
> +
基本、必要ないものはない方がいいんだけど、ControllerとMeasurerのロボットの基本動作については、仕様変更次第で使う使わないが変わるから、個人的にはあってもいいと思う。
一応、アームの操作もスタート時に勝手にアームを下すみたいな使用方法も考えられるし。

2023-05-22 01:40 UTC, KakinokiKanta commented on module/API/Controller.cpp
> +
なるほど。それならこのまま残してて良さそうですね。

2023-05-22 01:48 UTC, miyashita64 requested changes
直前になってごめん。
インスタンス化を禁止できてなさそうな点と、禁止した場合にstaticにしないと動かなさそうな点についてコメントです。
やっぱり、これホントに動くの？って思ったときに、呼び出しについてだけでもテストある方が安心はできるとは思う。

2023-05-22 01:48 UTC, miyashita64 commented on module/API/Controller.h
> +  Controller(const Controller&) = delete;  // 明示的にインスタンス化を禁止
これ、インスタンスのコピーを禁止してるだけで、インスタンスが自体は禁止できてない気がする。

```suggestion
  Controller() = delete;  // 明示的にインスタンス化を禁止
```
まだ、試してないけど、こういうイメージだった。

2023-05-22 01:48 UTC, miyashita64 commented on module/API/Controller.h
> +  void setLeftMotorPwm(const int pwm);
コンストラクタ禁止したからstaticにしないと外部から呼び出せないかな？
```suggestion
  static void setRightMotorPwm(const int pwm);
  static void setLeftMotorPwm(const int pwm);
```

2023-05-22 01:48 UTC, miyashita64 commented on module/API/Controller.h
> +  void stopMotor();
これも
```suggestion
  static void stopMotor();
```
(他のメンバも同様)

2023-05-24 01:35 UTC, miyashita64 requested changes
消し忘れ？のコメント部分だけ対応お願いします。

2023-05-24 01:35 UTC, miyashita64 commented on module/API/Controller.cpp
> +// Controller::Controller() : rightWheel(PORT_B), leftWheel(PORT_C), armMotor(PORT_A) {}
基本、いらないコメント部分は消して欲しいです

2023-05-24 01:35 UTC, miyashita64 commented on module/API/Controller.h
> +  // static ev3api::Motor armMotor;
これも

2023-05-24 01:58 UTC, miyashita64 approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/209566)

2023-05-24 04:26 UTC, bizyutyu approved these changes
LGTM！

2023-05-24 08:01 UTC, kawanoichi approved these changes
遅くなり申し訳ありません。お疲れ様です。
![201735](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/0f591e6c-cfa3-4bf8-8b3a-c5bfda3ef801)

2023-05-24 10:27 UTC, merged