close #69 キャリブレーションを左右ボタンのみで実行
KatLab-MiyazakiUniv/etrobocon2023 pull request #72
Opened 2023-07-13 12:36 UTC by KakinokiKanta

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- キャリブレーション時、(走行体正面から見て)左ボタンでコースの左右を切り替えて、右ボタンで決定するように変更
- 輝度取得時も右ボタンで決定するように変更

# 動作テスト
- 実機でキャリブレーションが行えることを確認

2023-07-13 14:17 UTC, bizyutyu approved these changes
お疲れ様です。
![LGTM](https://image.lgtmoon.dev/179237)

2023-07-13 14:30 UTC, aridome222 approved these changes
LGTM！
![LGTM](https://image.lgtmoon.dev/74962)

2023-07-13 15:00 UTC, miyashita64 requested changes
輝度の再取得とsleep()かsleep(10)の統一をお願いします。

2023-07-13 15:00 UTC, miyashita64 commented on module/Calibrator.cpp
>    }
外れ値を引いたときに手軽に再取得できた方がいいかも。（実装はなんでもいい）

```suggestion
  targetBrightbess = -1;
  // 左ボタンで輝度を取得し、右ボタンで待機状態に入る
  while(targetBrightness < 0 || !Measurer::getRightButton()){
    // 左ボタンが押されるまで待機
    while(!Measurer::getLeftButton()){
      timer.sleep(10);
    }
    // 輝度取得
    targetBrightness = Measurer::getBrightness();
    snprintf(buf, BUF_SIZE, ">> Target Brightness Value is %d", targetBrightness);
    logger.log(buf);
    timer.sleep(10);  // 10ミリ秒スリープ
  }
```

2023-07-13 15:00 UTC, miyashita64 commented on module/Calibrator.cpp
> +      timer.sleep(10);  // 10ミリ秒スリープ
timer.sleep(); と混在してるから統一してほしい。
個人的には、10を入れずに打ち間違いを回避する方がいいと思うけど、10入ってるファイルが多いからどっちにするかは任せます。

2023-07-13 15:07 UTC, miyashita64 commented on module/Calibrator.cpp
>    }
Ctrl＋Zで抜けると、高確率でkillできないプロセスが残って現状再起動しないと消せないから、できるだけ中断したくない

2023-07-13 17:13 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/190139)

2023-07-13 17:14 UTC, miyashita64 commented
LGTM出したけど、フォーマット通ってなかった...

2023-07-14 01:54 UTC, KakinokiKanta commented
今フォーマットチェック通しました！

2023-07-15 07:20 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/89791)

2023-07-15 09:29 UTC, merged