close #75 試走会１
KatLab-MiyazakiUniv/etrobocon2023 pull request #77
Opened 2023-07-22 11:07 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- 試走会１の試走用ブランチです。
- 試走会１中時点の"リアカメラによる画像取得"の変更も加えたままになっています。

# 動作テスト
- 試走会の布コースでは、おそらく一度程ですが、スタート〜ダブルループ攻略までの走行を通しておこなえました。

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-07-24 01:59 UTC, KakinokiKanta requested changes
細かい修正だけお願いします。
後camera_interface.pyはこのチケットでマージして大丈夫？河野さんの方ではない？

2023-07-24 01:59 UTC, KakinokiKanta commented on module/Calibrator.cpp
>    targetBrightness = -1;
ここはいらなくなるかな？

2023-07-24 01:59 UTC, KakinokiKanta commented on module/Calibrator.cpp
>    logger.log("Press the Right Button on the Line");
```suggestion
  // 黒線で右ボタンを押して、黒の輝度を取得する
  logger.log("Press the Right Button on the Black");
```

2023-07-24 01:59 UTC, KakinokiKanta commented on module/Calibrator.cpp
> +
```suggestion

// 白線で右ボタンを押して、白の輝度を取得する
  logger.log("Press the Right Button on the White");
```

2023-07-24 03:57 UTC, miyashita64 requested changes
処理の書き方でいくつか気になったので、対応お願いします

2023-07-24 03:57 UTC, miyashita64 commented on module/Calibrator.cpp
> +    while(blackBrightness < 0 && !Measurer::getLeftButton()) {
これ必要だっけ？

`blackBrightness < 0 && `

2023-07-24 03:57 UTC, miyashita64 commented on module/Calibrator.cpp
> +    while(whiteBrightness < 0 && !Measurer::getLeftButton()) {
これも
`whiteBrightness < 0 && `

2023-07-24 03:57 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +    SpeedCalculator speedCalculator(-targetSpeed, targetSpeed);
分岐しなくても↓でいいと思う
```suggestion
  SpeedCalculator speedCalculator(targetSpeed * rightSign, targetSpeed * leftSign);
```

2023-07-25 11:30 UTC, miyashita64 approved these changes
お疲れ様!!
![LGTM](https://image.lgtmoon.dev/21412)

2023-07-25 12:12 UTC, molpui0726 approved these changes
条件を一緒に実機で確認しました。&& じゃないと通りませんでした。
LGTMです、お疲れ様でした！🙇
![114068](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/48f020ed-4b09-47cf-b5ba-523af01ef30f)

2023-07-26 06:52 UTC, KakinokiKanta approved these changes
LGTM

2023-07-28 12:19 UTC, aridome222 approved these changes
お疲れ様です。確認したところ、問題ないと思います！
![LGTM](https://image.lgtmoon.dev/70488)

2023-07-28 12:19 UTC, merged