close #2 PIDを計算する
KatLab-MiyazakiUniv/etrobocon2023 pull request #8
Opened 2023-05-16 08:21 UTC by Negimarge

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
etrobocon2023/moduleの直下にCalculatorフォルダ(etrobocon2023/module/Calculator/)を作成し、
そこに以下の2つのファイルを追加。
- Pid.cpp
- Pid.h

etrobocon2023/testに以下のファイルを追加。
- PidTest.cpp

etrobocon2023/のCMakeLists.txtに以下の参照先を追加。
- include_directories(${PROJECT_SOURCE_DIR}/module/Calculator)
- ${PROJECT_SOURCE_DIR}/module/Calculator/*.cpp

# 動作テスト
PidTest.cppのテストに通りました。

## 添付資料

2023-05-17 06:57 UTC, miyashita64 requested changes
処理はいいと思います。
主に、去年、全体で統一できてなかったところについてのコメントです。

2023-05-17 06:57 UTC, miyashita64 commented on module/Calculator/Pid.cpp
> + * @author Negihara
GitHubのユーザ名に合わせたいから、Negimargeの方がいいかな

2023-05-17 06:57 UTC, miyashita64 commented on module/Calculator/Pid.cpp
> +  // delta 周期[ms](デフォルト値0.01[10ms]、省略可)
どちらかというとコメントが上下逆のような...どっちでもいいけど

2023-05-17 06:57 UTC, miyashita64 commented on module/Calculator/Pid.cpp
> +  // 積分の処理を行う
```suggestion
  // 積分の処理を行う(前回の誤差上辺、今回の誤差を下辺とする台形の面積を求める)
```
とか？

2023-05-17 06:57 UTC, miyashita64 commented on module/Calculator/Pid.h
> + * @author Negihara
ここも

2023-05-17 06:57 UTC, miyashita64 commented on module/Calculator/Pid.h
> +   * @fn void setPidGain(double _kp, double _ki, double _kd);
去年書いたり書かなかったりしたから、全体で統一した方がいいと思うんだけど、@fnって必要かな？

2023-05-17 06:57 UTC, miyashita64 commented on test/PidTest.cpp
> + * @author Negihara
ここも

2023-05-17 06:57 UTC, miyashita64 commented on test/PidTest.cpp
> +    preDeviation = currentDeviation;            // 前回の誤差の更新
フォーマットエラーは多分ここ。
プルリクのページの下の方に赤い×が表示されているとこの右側にDetailsってあって、そこから詳細が見れるよ。

2023-05-17 06:57 UTC, miyashita64 commented on test/PidTest.cpp
> +    double expected_p = 0.1;
これも去年統一できてなかったんだけど、テストコードでも、変数名はローワーキャメルケース(小文字始まりの大文字つなぎ)にしたい。

```suggestion
    double expectedP = 0.1;
```

2023-05-17 06:57 UTC, miyashita64 commented on test/PidTest.cpp
> +    double expected_d = 0.03;
どちらかというとkpかな？
PidGainのテストではその値が期待されてたからexpectedだけど今回はただの初期化用の値。
```suggestion
    double kp = 0.6;
    double ki = 0.02;
    double kd = 0.03;
```

2023-05-17 06:57 UTC, miyashita64 commented on test/PidTest.cpp
> +    double d = (currentDeviation - preDeviation) * expected_d / DELTA;
むしろこっちがexpected？
```suggestion
    double expectedP = currentDeviation * kp;
    double expectedI = ((preDeviation + currentDeviation) * DELTA / 2.0) * ki;
    double expectedD = (currentDeviation - preDeviation) * kd / DELTA;
```

2023-05-17 06:57 UTC, miyashita64 commented on test/PidTest.cpp
> +
kp以外が0、ki以外が0、kd以外が0で、P,I,Dそれぞれの値が正しいか検証するテストケースがある方がよりよいかも

2023-05-17 07:58 UTC, kawanoichi requested changes
clang format もう一度見直したうえで、できないときは教えてください

2023-05-17 07:58 UTC, kawanoichi commented on test/PidTest.cpp
> +    preDeviation = currentDeviation;            // 前回の誤差の更新
[clang format](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/wiki/clang-format%E3%81%AE%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95) を見て確認お願いします。

2023-05-17 08:00 UTC, kawanoichi commented on module/Calculator/Pid.cpp
> +  return (p + i + d);
好みの話になりますが、
```suggestion
  return p + i + d;
```
がいいです。

2023-05-20 15:45 UTC, KakinokiKanta commented on module/Calculator/Pid.h
> +   * @fn void setPidGain(double _kp, double _ki, double _kd);
結局すぐ下を見ればわかるんで、いらないと思います。

2023-05-21 06:06 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/209280)

2023-05-21 08:25 UTC, kawanoichi approved these changes, later dismissed
LGTM

2023-05-21 11:02 UTC, bizyutyu approved these changes
OKだと思います。

2023-05-21 16:53 UTC, KakinokiKanta approved these changes
![209279](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/105735727/4ffb3b14-6c75-4406-b6c1-4ea82b5b6901)

2023-05-22 01:57 UTC, merged