close #78 リアカメラによる回頭補正
KatLab-MiyazakiUniv/etrobocon2023 pull request #80
Opened 2023-07-31 11:53 UTC by aridome222

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

2023-08-12 16:36 UTC, miyashita64 requested changes
お疲れ様です。
ひとまず、cpp関連だけ。python側は起きてからちゃんと見ます。

あと動作してる動画をあげてもらえるとありがたいです。

2023-08-12 16:36 UTC, miyashita64 commented on rear_camera_py/Makefile
追加したコマンドについてのhelpを追記して欲しいです。

2023-08-12 16:36 UTC, miyashita64 commented on module/Motion/CorrectingRotation.cpp
> +  }
事前条件で判定した方がいいかな

2023-08-12 16:36 UTC, miyashita64 commented on module/Motion/CorrectingRotation.cpp
> +  Controller::stopMotor();
DistanceRotationをincludeして使った方がいいと思う。

2023-08-12 16:36 UTC, miyashita64 commented on module/Motion/CorrectingRotation.h
> +class CorrectingRotation : public Motion {
DistanceRotation読み込む場合は、CompositeMotionを継承するように変更して欲しい。

```suggestion
class CorrectingRotation : public CompositeMotion {
```

2023-08-12 16:36 UTC, miyashita64 commented on rear_camera_py/tests/test_angle_server.py
> +"""AngleServerクラスのテストコード."""
author漏れ

2023-08-13 04:06 UTC, kawanoichi requested changes
poetry環境ができてるけど、走行体でも環境作れましたか？
あと、補正動作は行っているけれど、補正角度が大きいような気がします。
算出されているエッジがどこを使っているのか、何度として出力されているかも表してください。

2023-08-13 05:04 UTC, ykimura0726 requested changes
いくつかあるので修正お願いします。宮下さんレビューの CompositeMotion 継承を反映させるまわりのところが中心です。

2023-08-13 05:04 UTC, ykimura0726 commented on module/Motion/CorrectingRotation.cpp
> +}
```suggestion
{};
```
セミコロン抜け。いらないと思いますが、他ファイルはあるので一応。
書いておいてなんですが、なくても Google Test, build ともに通るので大丈夫だとは思います。

2023-08-13 05:04 UTC, ykimura0726 commented on module/Motion/CorrectingRotation.h
> +
```suggestion
#include "CompositeMotion.h"
```
CompositeMotion 継承とのことなので、include も。

2023-08-13 05:04 UTC, ykimura0726 commented on module/Motion/CorrectingRotation.h
> +  void logRunning();
```suggestion
  /**
   * @brief 角度補正回頭する際の事前条件判定をする
   * @param targetAngle 目標角度(deg) 0~89
   * @param targetSpeed 目標速度[mm/s]
   * @note オーバーライド必須
   */
  bool isMetPrecondition(int targetAngle, double targetSpeed) override;
  
  /**
   * @brief 実行のログを取る
   * @note オーバーライド必須
   */
  void logRunning() override;
```
CompositeMotion 継承なので、logRunning はオーバーライド必要になると思います。同様に、事前条件の関数作るならそっちにも必要と思われます。

2023-08-13 09:27 UTC, kodama0720 commented
> 質問への回答をお願いします。
> 
> * poetry環境ができてるけど、走行体でも環境作れましたか？

試しましたが作れなかったため、関連ファイルを削除しました。

> * あと、補正動作の動画で、補正角度が大きいような気がします。動作テストの値は算出された角度？それとも分度器か何かで計算した角度？

動作テストの表の値は、角度計測アプリで計測した角度と算出された角度の比較です。動画で補正角度が大きいのは回頭動作の問題だと思います。

> * あと、test_dataの中身が去年の競技の画像なのですが、変えるべきではないですか？

今年の画像に差し替えました。

2023-08-13 13:37 UTC, kawanoichi requested changes
ちょっと大変かもしれないですが、変更をお願いします。

2023-08-13 13:37 UTC, kawanoichi commented on rear_camera_py/rear_camera/__init__.py
> +"""cameraパッケージの初期化を行うモジュール.
このファイルは何かに使ってますか？
あと、`rear_camera/`の中のファイルをすべて`src/`に入れてほしいです。

2023-08-13 13:37 UTC, kawanoichi commented on rear_camera_py/poetry.lock
> +[[package]]
これいらないファイルかな？

2023-08-13 13:37 UTC, kawanoichi commented on rear_camera_py/pyproject.toml
> +[tool.poetry]
このファイルもいらない

2023-08-13 13:37 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +                                                          = 80
ここで使っている言葉と値が去年のものなので、今年バージョンに変えてください

2023-08-13 13:37 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2*1.3  # 交点toブロック置き場*2*余幅補正 (mm)
ここの値も、今年これでいいのか検討してほしいです。検討済みなら、理由を書き換えてください

2023-08-13 13:37 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        straight_line_lower = np.array([909.996, 1198.916, 759.986, 1204.6339])
ここは、画角が変わっているのに座標が去年と同じってのはおかしいと思う。

2023-08-13 13:37 UTC, kawanoichi commented on rear_camera_py/tests/test_data/group-00-calibration-image-normal.png
データが入れ替わってない

2023-08-13 16:25 UTC, miyashita64 requested changes
理解できた範囲では、あまり問題なさそうに見えました。
ただ、理解が合ってるか不安なので、自分の認識が合っているか教えて欲しいです。
よろしくお願いします。

2023-08-13 16:25 UTC, miyashita64 commented on module/Motion/CorrectingRotation.cpp
> +  FILE* fp = fopen("result.txt", "r");
下の分岐でopenするならここではopenしない方がいいと思う
```suggestion
  FILE* fp = nullptr;
```

2023-08-13 16:25 UTC, miyashita64 commented on module/Motion/CorrectingRotation.cpp
> +  // 以降はRotation::run()と同様
AngleRotatonを使ってほしい。
その場合SpeedCalculatorはincludeしなくていいはず

2023-08-13 16:25 UTC, miyashita64 commented on module/Motion/CorrectingRotation.cpp
> +  system(cmd);
bashファイルの名前を変更してほしいです。
別ファイルや通信を経由しているので、出来るだけわかりやすくしたいです。
```suggestion
  snprintf(cmd, 1024, "bash ./etrobocon2023/scripts/rear_camera_request.sh %d > response.txt",
           ANGLE_SERVER_PORT);
```


それと、以下の流れだと認識しているのであってるか教えてください。


(あらかじめサーバを起動)
↓
`rear_camera.sh`を呼び出し、以下の処理でサーバにangleってコマンドを送信する
`bash -c "echo angle | nc 127.0.0.1 ${port}"`
↓
リクエストを受信したサーバが、`rear_camera/__main__.py`で設定された以下の処理で`line_angle_calculator.calc_yaw_angle()`を呼び出す
```
    angle_server = AngleServer(
        server_ip=args.server_ip,
        server_port=args.server_port,
        listen_num=127,
        buf_size=1024,
        debug=args.debug
    )

    angle_server.add_command(
        'angle',
        lambda _: str(line_angle_calculator.calc_yaw_angle())
    )
```
↓
`line_angle_calculator.calc_yaw_angle()`が返した値を`result.txt`にリダイレクトで書き込む
↓
`result.txt`内の値を読み込む

2023-08-13 16:25 UTC, miyashita64 commented on rear_camera_py/Makefile
> +	python -m rear_camera --debug
このコマンドは、デバック用のものですか？それとも、実行に必要？
もしデバック用なら
```suggestion
debug:
	python -m rear_camera --debug
```
にして欲しいです。

2023-08-14 06:05 UTC, aridome222 commented on module/Motion/CorrectingRotation.cpp
> +  system(cmd);
その認識で間違いないです。

2023-08-14 06:43 UTC, aridome222 commented on module/Motion/CorrectingRotation.cpp
> +  // 以降はRotation::run()と同様
CorrectingRotation.cppでのAngleRotationの使い方が分かりません。
CorrectingRotation.hでAngleRotation.hをincludeして、CorrectingRotation.cppで
```
  // 以降はRotation::run()と同様
```
上記のコメント以降を削除して、
```
AngleRotation angleRotation;
angleRotation.run();
```
みたいにしたのですが、

> error: 'AngleRotaiton' has not been declared
>    AngleRotaiton::Rotation.run();
> warning: unused variable 'angle' [-Wunused-variable]
>    int angle = abs(correctionAngle);  // 補正角度の小数点以下は切り捨てる
>        ^~~~~
> warning: unused variable 'isClockwise' [-Wunused-variable]
>    bool isClockwise = correctionAngle > 0 ? true : false;
>         ^~~~~~~~~~~
上記のようなエラーと警告が出ます。

数時間考えても分からなかったので、教えて頂きたいです。

2023-08-14 08:55 UTC, molpui0726 commented on module/Motion/CorrectingRotation.cpp
> +}
```suggestion
{};
```
セミコロン抜け。他ファイルはあったと思うので一応。
セミコロンなくても Google Test も build も通った記憶はあります。セミコロンあるなしで動作に影響が出ることってさすがにないですよね？　コメントしておいてなんですが、ないならわざわざ直すほどでもない気はします。

2023-08-14 08:55 UTC, molpui0726 commented on module/Motion/CorrectingRotation.h
> +  void logRunning();
```suggestion
  /**
   * @brief 角度補正回頭する際の事前条件判定をする
   * @param _targetAngle 目標角度(deg) 0~89
   * @param _targetSpeed 目標速度[mm/s]
   * @note オーバーライド必須
   */
  bool isMetPrecondition(int targetAngle, double targetSpeed) override;
  
  /**
   * @brief 実行のログを取る
   * @note オーバーライド必須
   */
  void logRunning() override;
```
CompositeMotion 継承なので、logRunning はオーバーライドが必要。事前条件も同様。

2023-08-14 09:19 UTC, aridome222 commented on module/Motion/CorrectingRotation.cpp
> +  // 以降はRotation::run()と同様
解決しました！

2023-08-16 15:07 UTC, aridome222 commented on rear_camera_py/rear_camera/__init__.py
> +"""cameraパッケージの初期化を行うモジュール.
調べたところ、python3.3以降からは中身が空っぽの__init__.pyは不要らしいので削除しておきます。
> 参考文献：https://qiita.com/herr-shigeo/items/9f3ef8de1c5c9561d905

2023-08-18 03:22 UTC, bizyutyu commented
ざっと目を通した感じだと問題ないように思うのですが、もう少し詳しく見ようと思うので、少しお待ちください。

2023-08-18 05:56 UTC, KakinokiKanta approved these changes
LGTM!!

2023-08-18 06:53 UTC, kawanoichi requested changes
お願いします

2023-08-18 06:53 UTC, kawanoichi commented on rear_camera_py/src/line_angle_calculator.py
> +                                                          = 145
交点の半径に内直径の値を使ってるのはなぜ？
あと、昨年は交点to中点は交点の半径も含んでいたけど、今年の応用動作に交点to中点に交点内移動は含んでないかな...？

2023-08-18 06:53 UTC, kawanoichi commented on rear_camera_py/src/line_angle_calculator.py
> +        straight_line_lower = np.array([940.000, 1095.000, 701.000, 1095.000])
これに変更した後に線分が検出できるかの確認はしましたか？いろんなパターンのコース画像で検証してください。

2023-08-18 07:25 UTC, bizyutyu requested changes

2023-08-18 07:25 UTC, bizyutyu commented on module/Motion/CorrectingRotation.cpp
> +   * 計測角度(絶対値)が目標角度より45度より大きい場合，横線を採用したと判定する
以下の変更で合ってるか分からないけど、コメントが変な気がします。
```suggestion
   * 計測角度と目標角度の差の絶対値が45度より大きい場合，横線を採用したと判定する
```

2023-08-18 07:27 UTC, miyashita64 requested changes

2023-08-18 07:27 UTC, miyashita64 commented on rear_camera_py/Makefile
> +
キャリブレーション用のコマンドを追加してほしいです。
（これがあってるかわからないけど）
```suggestion
calibrate:
        python -m src --calibrate
```

2023-08-18 11:31 UTC, aridome222 commented on rear_camera_py/src/line_angle_calculator.py
> +                                                          = 145
@kodama0720 @kawanoichi 
まず、確認したいこととして、交点って、サークルと直線の交わる部分なのか、サークルの中心なのかどっちなんでしょうか？
児玉さんと作業をしていたときは、サークルの中心が交点だとおもっていたのですが、
ブロックエリアのコマンドを作った木村君に聞いたところ、サークルと直線の交わる部分が交点ではないかと思ってます。
その前提で話を進めます。

確かに交点の半径に内直径の値を使ってるのは僕も疑問に思っていて、というか、検出したい線分の長さ = 交点to中点-ブロックの半径という式じゃなくて、検出したい線分の長さ = 交点to交点の線分の長さの半分で良いのではないかと思ってるのですが、どうなんでしょうか？

交点to中点に交点内移動は含んでいると思います。木村君に確認済みで、聞いたところ、まだmainブランチに更新していないInCrossLeft.cppなどがあるらしく、そのファイルには交点内移動の処理を追加しているそうです。

2023-08-18 11:38 UTC, aridome222 commented on rear_camera_py/src/line_angle_calculator.py
> +        straight_line_lower = np.array([940.000, 1095.000, 701.000, 1095.000])
いろんなパターンで検証してみました。例えば、ブロックが含まれる場合の線分検出など試してみました。
試した感じ、ある程度どんなパターンでも線分検出ができることを確認できました。
debugによる画像をいろいろ撮ったので、下記のgoogleドライブから確認して頂けるとありがたいです。
[線分検出画像](https://drive.google.com/drive/folders/1nQaMqfFuzxJjWOFD5g-WnN68-aOMtXun?usp=drive_link)

2023-08-18 11:44 UTC, aridome222 commented on module/Motion/CorrectingRotation.cpp
> +   * 計測角度(絶対値)が目標角度より45度より大きい場合，横線を採用したと判定する
ありがとうございます。日本語おかしいと思っていたのですが、修正するのを忘れてました。

2023-08-18 15:12 UTC, bizyutyu approved these changes
LGTM!お疲れ様です。
![LGTM](https://image.lgtmoon.dev/198117)

2023-08-18 17:08 UTC, kawanoichi commented on rear_camera_py/src/line_angle_calculator.py
> +                                                          = 145
CrossToMidの中でInCrossLeft(Right)してたね。すみません勘違いしていました。
```
検出したい線分の長さ = 交点to交点の線分の長さの半分（※交点サークル内の距離は除く）
```
```suggestion
                                       検出したい線分の長さ = 交点to交点の線分の長さの半分（※交点サークル内の距離は除く）
                                                          = 125？
```
みたいな感じのコメントにすれば分かりやすい？
「交点の半径に内直径の値を使ってるのは僕も疑問に思っている」ってのは @kodama0720 が担当してる場所ってことかな？

2023-08-18 17:38 UTC, miyashita64 commented on rear_camera_py/src/line_angle_calculator.py
> +                                                          = 145
> 
> まず、確認したいこととして、交点って、サークルと直線の交わる部分なのか、サークルの中心なのかどっちなんでしょうか？
> 

個人の認識になるけど一応。
※調整では違ったよってことならごめんなさい。


「交点」は、昨年(下図参照)も一昨年(交点to中点の参考元)も、線が交わってる円(塗りつぶしの差はあれど)の事のはず。交点サークルの略。

ただ昨年は、交点からの移動は、図にあるような「エッジの交差点(開発ではこれも略して交点って呼んでたかも)」から始めて、交点への移動は、エッジの交差点で終わるようにしてた。

一昨年は、交点からの移動は、交点とラインの接点から始めて、交点への移動は、交点とラインの接点で終わるようにしてた。
だから、交点to〇〇の交点は、サークルと交わる部分とか、サークルの中心とかではなく、サークルそのもの。

![image](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/83441177/4bac31d0-8be4-403a-b061-b30709f59eaa)

2023-08-18 17:39 UTC, miyashita64 commented
> 
> まず、確認したいこととして、交点って、サークルと直線の交わる部分なのか、サークルの中心なのかどっちなんでしょうか？
> 

個人の認識になるけど一応。
※調整では違ったよってことならごめんなさい。


「交点」は、昨年(下図参照)も一昨年(交点to中点の参考元)も、線が交わってる円(塗りつぶしの差はあれど)の事のはず。交点サークルの略。

ただ昨年は、交点からの移動は、図にあるような「エッジの交差点(開発ではこれも略して交点って呼んでたかも)」から始めて、交点への移動は、エッジの交差点で終わるようにしてた。

一昨年は、交点からの移動は、交点とラインの接点から始めて、交点への移動は、交点とラインの接点で終わるようにしてた。
だから、交点to〇〇の交点は、サークルと交わる部分とか、サークルの中心とかではなく、サークルそのもの。

![image](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/83441177/4bac31d0-8be4-403a-b061-b30709f59eaa)

2023-08-18 18:00 UTC, miyashita64 approved these changes
google driveのやつ的に動きには問題なさそう
![LGTM](https://image.lgtmoon.dev/103196)

2023-08-19 00:37 UTC, aridome222 commented on rear_camera_py/src/line_angle_calculator.py
> +                                                          = 145
児玉さんが担当していたというか、僕も一緒にやってたんですけど、何となくで分かってるつもりになってました。

2023-08-19 01:51 UTC, aridome222 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2*1.3  # 交点toブロック置き場*2*余幅補正 (mm)
検討済みです。交点toブロッコリー置き場の値を今年のものに変えました。

2023-08-19 04:04 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2*1.3  # 交点toブロック置き場*2*余幅補正 (mm)
今年ブロック置き場(ブロッコリー置き場)なんてものはないので、別の言葉に変えてほしいな

2023-08-19 04:14 UTC, kawanoichi commented on rear_camera_py/src/line_angle_calculator.py
> +                                                          = 145
分からなかったら聞いてね

2023-08-19 04:53 UTC, YKhm20020 approved these changes
resolve した後に Approve 出し忘れていました。LGTMです、お疲れ様でした！
![129503](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/128010507/df0fabe9-6a09-44fe-a5ca-ea99ba2135f8)

2023-08-23 13:03 UTC, aridome222 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2*1.3  # 交点toブロック置き場*2*余幅補正 (mm)
すみません、しっかり確認するよう気を付けます！（ブロッコリー置き場も）
修正しましたので、ご確認よろしくお願いします。

2023-08-24 15:13 UTC, kawanoichi approved these changes
お疲れさまでした。
![215173](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/d24b6173-5165-421f-9cf9-00a011ca255f)

2023-09-03 02:57 UTC, merged