#83 撮影動作用のファイルを追加
KatLab-MiyazakiUniv/etrobocon2023 pull request #85
Opened 2023-08-05 08:36 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-08-06 06:51 UTC, miyashita64 reviewed
いい感じだと思います。
指摘というよりちょっとした疑問だけ

2023-08-06 06:51 UTC, miyashita64 commented on module/Motion/CameraAction.cpp
> +  if(cameraActionFlag == false) {
これは事前条件ではない？

2023-08-06 06:51 UTC, miyashita64 commented on module/Motion/CameraAction.cpp
> +    snprintf(cmd, 256, "cd etrobocon2023/rear_camera_py && make image && cd ../..");
最後の"cd ../.."っているんだっけ？

2023-08-06 13:20 UTC, bizyutyu commented on module/Motion/CameraAction.cpp
> +    snprintf(cmd, 256, "cd etrobocon2023/rear_camera_py && make image && cd ../..");
走行体動作中(make start)は、workspaceの下で実行しているみたいなので、撮影動作後にworkspace/etrobocon2023/rear_camera_pyに居るままなのもどうかなと思い付けてます。
しかし、workspace/etrobocon2023/rear_camera_pyに居たままだと後の動作に影響が出るかどうかは確認しきれてないので、明日(8/7)確認してみます。

2023-08-06 22:53 UTC, kawanoichi requested changes
お疲れ様です。
boolに違和感があったところだけ...
あとはいいと思います

2023-08-06 22:53 UTC, kawanoichi commented on module/Motion/CameraAction.cpp
> +  if(cameraActionFlag == false) {
名前的にcameraActionFlagがTrueの時に動作を実行しそうじゃない？cameraActionSkipFlagとかならわかるけど...

2023-08-07 12:39 UTC, kawanoichi requested changes
スペルミスありました。

2023-08-07 12:39 UTC, kawanoichi commented on module/Motion/CameraAction.cpp
> +  : isClockwis(_isClockwis), preTargetAngle(_preTargetAngle), postTargetAngle(_postTargetAngle){};
```suggestion
CameraAction::CameraAction(bool _isClockwise, int _preTargetAngle, int _postTargetAngle)
  : isClockwise(_isClockwise), preTargetAngle(_preTargetAngle), postTargetAngle(_postTargetAngle){};
```
他にもたくさん`isClockwis`がいるので修正してください

2023-08-07 16:09 UTC, KakinokiKanta requested changes
1つだけよろしくです

2023-08-07 16:09 UTC, KakinokiKanta commented on module/Motion/CameraAction.cpp
> +  bool cameraActionSkipFlag = false;
systeminfoとかに持たせた方が良いんじゃない？

2023-08-07 16:37 UTC, kawanoichi approved these changes
![163828](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/406f4e69-2d9a-4b03-b935-7213c7e55cf0)

2023-08-07 18:22 UTC, bizyutyu reviewed
上記コミットによる変更後に実機での走行確認を行い、systemInfo.hにフラグを置いても問題なく動作することを確認しました。しかし、systemInfo.hにフラグを置いたことで、フラグ未使用のwarning（In file included from /home/takakura/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Motion/Straight.h:15:0,
from /home/takakura/etrobo/hrp3/sdk/workspace/etrobocon2023/module/Motion/DistanceStraight.h:10,
from /home/takakura/etrobo/hrp3/sdk/workspace/etrobocon2023/module/MotionParser.h:17,
from /home/takakura/etrobo/hrp3/sdk/workspace/etrobocon2023/module/AreaMaster.h:13,
from /home/takakura/etrobo/hrp3/sdk/workspace/etrobocon2023/module/EtRobocon2023.cpp:9:
/home/takakura/etrobo/hrp3/sdk/workspace/etrobocon2023/module/common/SystemInfo.h:17:13: warning: 'cameraActionSkipFlag' defined but not used [-Wunused-variable] static bool cameraActionSkipFlag = false;  みたいなやつ）が10数カ所箇所程出てきており、解決できなかったので、一時的対処として、systemInfo.hにてフラグ未使用のwarningを無視する処理を追加しています。

2023-08-07 19:20 UTC, miyashita64 commented
動作確認までできてるならひとまずいいのかな。
お疲れ様でした！

![LGTM](https://image.lgtmoon.dev/75791)

2023-08-08 04:22 UTC, KakinokiKanta approved these changes
![LGTM](https://image.lgtmoon.dev/217995)

2023-08-08 06:57 UTC, Negimarge approved these changes
見た感じ不明な点はなさそうです
LGTM

2023-08-08 10:15 UTC, miyashita64 approved these changes
LGTM

2023-08-08 10:28 UTC, merged