#84 ブロックエリア内の移動動作の実装
KatLab-MiyazakiUniv/etrobocon2023 pull request #86
Opened 2023-08-05 11:01 UTC by YKhm20020

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点

etrobocon2023/module 下に以下のフォルダを追加。
- module/BlockMotion

CMAkeLists.txt 71行目、81行目に以下の記述を追加。
- include_directories(${PROJECT_SOURCE_DIR}/module/BlockMotion)
- ${PROJECT_SOURCE_DIR}/module/BlockMotion/*.cpp

Makefile.inc 26行目、37行目に以下の記述を追加。
- $(mkfile_path)module/BlockMotion \
- -I$(mkfile_path)module/BlockMotion \

同様に、

BlockMotion フォルダ下に以下のファイルを追加。
- BlockMotion.h
- BlockMotion.cpp
- DirectionChanger.h
- DirectionChanger.cpp
- InCrossLeft.h
- InCrossLeft.cpp
- InCrossRight.h
- InCrossRight.cpp
- InCrossStraight.h
- InCrossStraight.cpp
- ToCrossMotion.h
- ToCrossMotion.cpp

ToCrossMotion の最後に「白黒以外までライントレース」、DirectionChanger の最後に「白黒を判定するまで直進」という、一昨年にあって今年にない動作を今年にあうように変更しています。targetColor を引数にとって、それを指定色として動作を行うようにしています。

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2023-08-06 07:45 UTC, miyashita64 requested changes
お疲れ様。
めちゃめちゃ申し訳ないけど、
BlockPivotTurnとMidToMidは使わないかな。

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/BlockPivotTurn.cpp
> + * @file BlockPivotTurn.cpp
ごめん多分使わない

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/BlockPivotTurn.h
> + * @file BlockPivotTurn.h
こいつも

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/CrossToMid.cpp
> +  : BlockMotion(1.02, 1.01),
```suggestion
  : BlockMotion(1.02, 1.01),  // 動作時間, 失敗リスク TODO: 測定し直す
```
みたいなコメントが欲しいです。
他動作も同様

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/MidToMid.cpp
> + * @file MidToMid.cpp
ごめん、こいつも使わない

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/MidToMid.h
> + * @file MidToMid.h
こいつも

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/DirectionChanger.cpp
> +                                   bool& _isLeftEdge, int _rotateAngle, int _changeAngle)
_isClockwiseを、受け取った方がいいと思う。
一昨年は、rotateAngleの正負で回頭方向決めてたけど、今年は、全体的にどっち回りかを指定してるから。

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/DirectionChanger.cpp
> +  : BlockMotion(0.88, 0.92),
ここもコメント追加お願いします

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/DirectionChanger.cpp
> +  } else {
事前条件で負のrotationAngleを許容してないので到達不可

2023-08-06 07:45 UTC, miyashita64 commented on module/Motion/ToCrossMotion.cpp
> + * @file ToCrossMotion.cpp
他に合わせるならToCrossかな

2023-08-06 07:50 UTC, miyashita64 commented on module/Motion/DirectionChanger.cpp
> + * @brief 方向転換クラス
@kodama0720 @kawanoichi @OnagaHaruki @KakinokiKanta @bizyutyu 

ブロックエリアの話あんまりできてないけど、交差点(交点)での右左折直進ができれば、方向転換のタイミングない気はするんだけど、あってるっけ？

右左折を方向転換に置き換える方針もなくはないけど。

2023-08-06 18:23 UTC, miyashita64 requested changes
コメントのピボットターンを回頭にしてほしいのと、書き方で少々

2023-08-06 18:23 UTC, miyashita64 commented on module/Motion/DirectionChanger.cpp
> +  }
これでいいかな
```suggestion
  AngleRotation rotation(targetAngle, targetSpeed, isClockwise);
  rotation.run();
```

2023-08-06 18:23 UTC, miyashita64 commented on module/Motion/InCrossLeft.cpp
> +  // ピボットターン後の位置を調整するため、直進する
```suggestion
  // 回頭後の位置を調整するため、直進する
```
他のピボットターンも回頭でお願いします

2023-08-06 18:23 UTC, miyashita64 commented on module/Motion/DirectionChanger.cpp
> +  }
無駄なインスタンス化は減らせるなら減らしたい

```suggestion
  if(targetAngle == 180) {  // 後ろ方向に方向転換する場合
    nextEdge = !isLeftEdge;
  } else {
    nextEdge = isClockwise;
  }
  EdgeChanging ec(isLeftEdge, nextEdge);
  ec.run();
```

2023-08-06 22:33 UTC, kawanoichi requested changes
モデルで話し合ってからまたレビューします

2023-08-06 22:33 UTC, kawanoichi commented on module/Motion/BlockMotion.cpp
> + * @file BlockMotion.cpp
```suggestion
 * @file BlockAreaMotion.cpp
```
ファイル名だけ見たときに何のファイルかできるだけわかりやすいようにしたいです。

2023-08-06 22:33 UTC, kawanoichi commented on module/Motion/BlockMotion.h
> + * @file BlockMotion.h
```suggestion
 * @file BlockAreaMotion.h
```

2023-08-06 22:33 UTC, kawanoichi commented on module/Motion/DirectionChanger.cpp
> + * @brief 方向転換クラス
去年なかったやつだよね？いらないかな

2023-08-07 05:50 UTC, bizyutyu requested changes
細かいコメントの修正です。

2023-08-07 05:50 UTC, bizyutyu commented on module/Motion/CrossToMid.cpp
> + * @brief サークルの交点から交点へ移動するクラス
```suggestion
 * @brief サークルの交点から中点へ移動するクラス
```

2023-08-07 05:50 UTC, bizyutyu commented on module/Motion/CrossToMid.h
> + * @brief サークルの交点から交点へ移動するクラス
```suggestion
 * @brief サークルの交点から中点へ移動するクラス
```

2023-08-07 11:40 UTC, bizyutyu requested changes
多いけどもよろしくお願いします。

2023-08-07 11:40 UTC, bizyutyu commented on module/Motion/CrossToMid.h
> +
```suggestion
#include "InCrossStraight.h"
#include "InCrossLeft.h"
#include "InCrossRight.h"
#include "ColorJudge.h"
#include "DistanceLineTracing.h"
#include "BlockAreaMotion.h"

```
今は大丈夫みたいだけど、後々を考えたらあったほうが良いと思う。BlockAreaMotion.getMotionTime()使うときとかに不具合が出るかも。

2023-08-07 11:40 UTC, bizyutyu commented on module/Motion/InCrossRight.cpp
> +  AngleRotation rotation(targetAngle, targetSpeed, isClockwise);
```suggestion
  DistanceStraight ds(targetDistance, dsTargetSpeed);
  AngleRotation rotation(targetAngle, arTargetSpeed, isClockwise);
```
区別をつけたほうが良いと思います。

2023-08-07 11:40 UTC, bizyutyu commented on module/Motion/InCrossStraight.h
> +  double targetDistance = 100.0;  // 交点サークルの外径
```suggestion
  const double targetDistance = 100.0;  // 交点サークルの外径

```
のようにして、メンバにするか、コンストラクタがtargetDistanceを受け取るなら
//外径100.0mm
というコメントにして、適切な箇所に残す。

2023-08-07 11:40 UTC, bizyutyu commented on module/Motion/InCrossRight.h
> +  double targetDistance = 25.0;  // 目標距離
コメントにして残しておく。

2023-08-07 11:40 UTC, bizyutyu commented on module/Motion/InCrossRight.h
> +  int targetAngle = 74;          // 目標回頭角度
コメントにして残しておく。

2023-08-07 11:40 UTC, bizyutyu commented on module/Motion/InCrossLeft.cpp
> +  AngleRotation rotation(targetAngle, targetSpeed, isClockwise);
```suggestion
  DistanceStraight ds(targetDistance, dstargetSpeed);
  AngleRotation rotation(targetAngle, artargetSpeed, isClockwise);
```
区別をつけるべきだと思う。

2023-08-07 11:40 UTC, bizyutyu commented on module/Motion/InCrossRight.h
> +  InCrossRight(double _targetDistance, double _targetSpeed, int _targetAngle);
```suggestion
  InCrossRight(double _targetDistance, double dsTargetSpeed, double arTargetSpeed ,int _targetAngle);
```
他のクラスも同様にお願いします。

2023-08-07 11:40 UTC, bizyutyu commented on module/Motion/InCrossRight.cpp
> +    targetAngle(_targetAngle){};
```suggestion
InCrossRight::InCrossRight(double _targetDistance, double _targetSpeed, int _targetAngle)
  : BlockAreaMotion(1.23, 1.09),  // 動作時間, 失敗リスク TODO: 測定し直す
    targetDistance(_targetDistance),
    dstargetSpeed(_dstargetSpeed),
    artargetSpeed(_artargetSpeed),
    targetAngle(_targetAngle){};
```
他のクラスでも同様にお願いします。

2023-08-07 18:59 UTC, miyashita64 approved these changes
LGTM お疲れ様！

![LGTM](https://image.lgtmoon.dev/215306)

2023-08-07 19:52 UTC, kawanoichi requested changes
レビューが遅くなってしまい申し訳ございません
コメントの言葉の統一ができていない気がしました。(勘違いだったらごめんなさい)
![IMG_0933](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/6d086dd5-1bbf-48d0-a58a-6343443ce945)

2023-08-07 19:52 UTC, kawanoichi commented on module/Motion/InCrossStraight.h
> +  double targetDistance;  // 交点サークルの外径 (一昨年は 100.0)
```suggestion
  double targetDistance;  // 交点サークルの外径 (100.0mm)

```
今年のコースも測定して100mmってわかってるから一昨年の情報はいらないかな

2023-08-07 19:52 UTC, kawanoichi commented on module/MotionParser.cpp
> +    return COMMAND::CM;
IRとTCなくね？

2023-08-07 19:52 UTC, kawanoichi commented on module/Motion/ToCross.cpp
> + * @brief 交点サークル間移動のクラス
```suggestion
 * @file CrossToCross.cpp
 * @brief 交点から交点までライントレースするクラス

```
交点サークル間って言葉ちょっとわかりにくいかな

2023-08-07 19:52 UTC, kawanoichi commented on module/Motion/ToCross.h
> + * @author YKhm20020
```suggestion
 * @file CrossToCross.h
 * @brief 交点から交点までライントレースするクラス

```
ここも

2023-08-07 19:52 UTC, kawanoichi commented on module/MotionParser.cpp
> +    else if(command == COMMAND::IS) {  // サークルの交点から交点までの直進
```suggestion
    else if(command == COMMAND::IS) {  // 交点内移動（直進）
```
「交点サークル」と「サークルの交点」って紛らわしいからできれば別の言葉で...

2023-08-07 19:52 UTC, kawanoichi commented on module/MotionParser.h
> +  IS,  // サークルの交点から交点までの直進
```suggestion
  IS,  // 交点内移動（直進）
```

2023-08-07 19:52 UTC, kawanoichi commented on module/MotionParser.h
> +  TC,  // 交点サークル間移動
```suggestion
  TC,  // 交点サークルから交点サークル
```

2023-08-07 19:52 UTC, kawanoichi commented on module/MotionParser.h
> +  CM,  // サークルの交点から直線の中点へ移動
```suggestion
  CM,  // 交点サークルから直線の中点
```

2023-08-07 19:58 UTC, bizyutyu requested changes

2023-08-07 19:58 UTC, bizyutyu commented on module/MotionParser.cpp
> +          convertBool(params[0], params[12]));  // 切り替え後のエッジ
convertBoolに、CMについての処理の追加だけお願いします！

2023-08-07 20:00 UTC, bizyutyu commented on module/MotionParser.cpp
> +          convertBool(params[0], params[12]));  // 切り替え後のエッジ
`
  if(strcmp(command, "EC") == 0) {    //  コマンドがECの場合
    if(strcmp(param, "left") == 0) {  // パラメータがleftの場合
      return true;
    } else if(strcmp(param, "right") == 0) {  // パラメータがrightの場合
      return false;
    } else {  // 想定していないパラメータが来た場合
      logger.logWarning("Parameter before conversion must be 'left' or 'right'");
      return true;
    }
  }`

2023-08-07 20:03 UTC, kawanoichi commented on module/MotionParser.cpp
> +          convertBool(params[0], params[12]));  // 切り替え後のエッジ
@bizyutyu 
```
複数行の時はこの書き方があるよ。editで見てみて
```

2023-08-07 20:07 UTC, bizyutyu commented on module/MotionParser.cpp
> +          convertBool(params[0], params[12]));  // 切り替え後のエッジ
```
ありがとうございます！
```

2023-08-08 02:39 UTC, bizyutyu approved these changes
お疲れ様です！LGTM！
![LGTM](https://image.lgtmoon.dev/13669)

2023-08-08 04:17 UTC, kawanoichi requested changes
まだ残ってました

2023-08-08 04:17 UTC, kawanoichi commented on module/Motion/CrossToMid.cpp
> + * @brief サークルの交点から直線の中点へ移動するクラス
```suggestion
 * @brief 交点サークルから直線の中点へ移動するクラス
```

2023-08-08 04:17 UTC, kawanoichi commented on module/Motion/CrossToMid.h
> + * @brief サークルの交点から直線の中点へ移動するクラス
```suggestion
 * @brief 交点サークルから直線の中点へ移動するクラス
```

2023-08-08 04:17 UTC, kawanoichi commented on module/Motion/CrossToMid.h
> +   * @brief サークルの交点から中点へ移動
```suggestion
   * @brief 交点サークルから中点へ移動
```

2023-08-08 07:15 UTC, Negimarge approved these changes
修正終わったら大丈夫だと思います

2023-08-08 10:40 UTC, aridome222 requested changes
レビュー遅れてすみません。
気になる所があったので、修正お願いします。

2023-08-08 10:40 UTC, aridome222 commented on module/MotionParser.cpp
> +                                        atoi(params[4]));  // 目標回頭角度
```suggestion
                                        atoi(params[3]),  // 目標回頭角度
                                        atof(params[4]));  // 角度指定回頭の目標速度 [mm/s]
```
上記のように、引数の順番逆がいいかな。
目標距離、直進の目標速度の順に指定するなら、それに従って目標回頭角度、回頭の目標速度の順が良いと思う。.cppと.hファイルの引数の順番も逆にするように。

2023-08-08 10:40 UTC, aridome222 commented on module/MotionParser.cpp
> +                                          atoi(params[4]));  // 目標回頭角度
ここも同じように引数の順番逆に

2023-08-08 10:40 UTC, aridome222 commented on module/MotionParser.cpp
> +          convertBool(params[0], params[12]));  // 切り替え後のエッジ
引数多くて調整するとき、大変そう。
引数あんまり取らなくて済む方法思いつかないけど、新しいコマンド作るより、今ある簡単なコマンドをcsvにそのまま書いた方が良さそうだなって個人的に思いました。

2023-08-08 10:40 UTC, aridome222 commented on module/Motion/CrossToMid.cpp
> +  }
```suggestion
  // arTargetSpeed値が0の場合はwarningを出して終了する
  if(arTargetSpeed == 0.0) {
    snprintf(buf, BUF_SIZE, "The arTargetSpeed value passed to CrossToMid is 0");
    logger.logWarning(buf);
    return false;
  }
```
コメントがdsのコメントになってる

2023-08-08 10:45 UTC, aridome222 commented on module/MotionParser.cpp
> +          convertBool(params[0], params[12]));  // 切り替え後のエッジ
引数多くて調整するとき、大変そう。
引数あんまり取らなくて済む方法思いつかないけど、新しいコマンド作るより、今ある簡単なコマンドをcsvにそのまま書いた方が良さそうだなって個人的に思いました。

2023-08-10 09:35 UTC, kawanoichi approved these changes
![209136](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/64b8f479-ae4f-42a2-aae9-505fc0eb494d)

2023-08-11 02:58 UTC, aridome222 approved these changes
修正お疲れ様です。

2023-08-11 03:00 UTC, merged