add: カラーセンサー等の値を取得するクラスとそのテストを追加
KatLab-MiyazakiUniv/etrobocon2023 pull request #9
Opened 2023-05-17 14:27 UTC by YKhm20020

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
etrobocon2023/module に API フォルダを作成。
以下のファイルを etrobocon2023/module/API に追加。
- Measure.cpp
- Measure.h

さらに、以下のファイルを etrobocon2023/test/dummy に追加。
- ColorSensor.cpp
- ColorSensor.h
- Motor.cpp
- Motor.h
- Port.h
- SonarSensor.cpp
- SonarSensor.h

動作に関係ないため不要だと思ったのですが、
ColorSensor.hのgetRawColorのコメントに@param rgb RGB値を代入する変数（参照渡し）
の説明を加えています。間違っていたらすみません。

昨年のSonarSensor.cppの13行目のgetDistanceのコメントが「RGB値を取得」になっていたのですが、コミット後に気づいたため、プルリクの修正反映と一緒に「距離を測定する」に修正しようと考えています。この修正予定が間違っていないかも確認していただけると幸いです。

```
// RGB値を取得
int SonarSensor::getDistance()
{
  // 呼び出すたびにdistanceを1引く（0~100）
  if(distance == 0) {
    distance = 100;
  } else {
    distance--;
  }

  return distance;
}
```

# 動作テスト

## 添付資料

2023-05-19 10:38 UTC, miyashita64 requested changes
細々としたことです。

2023-05-19 10:38 UTC, miyashita64 commented on CMakeLists.txt
> +  ${PROJECT_SOURCE_DIR}/module/*/*.cpp
意図してないファイルが入るかもしれないから
```suggestion
  ${PROJECT_SOURCE_DIR}/module/API/*.cpp
```
の方が安心かな

2023-05-19 10:38 UTC, miyashita64 commented on module/API/Measurer.cpp
> + * @file Measurer.h
```suggestion
 * @file Measurer.cpp
```

2023-05-19 10:38 UTC, miyashita64 commented on module/API/Measurer.h
> + * @file Measurer.cpp
```suggestion
 * @file Measurer.h
```

2023-05-19 10:38 UTC, miyashita64 commented on module/API/Measurer.cpp
> +Measurer::Measurer()
Controllerでも言ったけど、staticにしてインスタンス化しない方がいい気もする。
どうでしょう？

2023-05-19 10:38 UTC, miyashita64 commented on test/MeasurerTest.cpp
> +  TEST(MeasurerTest, getRawColor)
ほかの関数についてもテストを書いてほしいです。

2023-05-21 03:09 UTC, kawanoichi commented on module/API/Measurer.h
> +   * 左モータ角位置取得
```suggestion
   * 左モータ角位置を取得
```

2023-05-21 03:10 UTC, kawanoichi commented on module/API/Measurer.h
> +   * 左モータ角位置取得
```suggestion
   * 左モータ角位置を取得
```

2023-05-21 03:17 UTC, kawanoichi commented on module/API/Measurer.h
> +   * 左モータ角位置取得
```suggestion
   * 左モータ角位置を取得
```
ヘッダーファイル内で「位置を取得」と「位置取得」が統一されていないので、どちらかに統一してください。

2023-05-21 03:20 UTC, kawanoichi commented on module/API/Measurer.h
> +   * @return 左ボタンの押下状態 true:押されてる, false：押されていない
```suggestion
   * @return 左ボタンの押下状態 true:押されている, false：押されていない
```
他のところにもあるので修正お願いします。

2023-05-21 04:25 UTC, kawanoichi requested changes
訂正部分をシングルコメントで送ってました。すみません。まだ全部見れてないです。

2023-05-21 06:18 UTC, KakinokiKanta requested changes
細かいところ１つだけ

2023-05-21 06:18 UTC, KakinokiKanta commented on test/dummy/SonarSensor.cpp
> +// RGB値を取得
```suggestion
// センサーまでの距離を取得
```
RGB値じゃなくて、センサーまでの距離じゃない？

2023-05-21 17:21 UTC, KakinokiKanta requested changes
1か所だけ修正をお願いします。夜遅くに申し訳ない。

2023-05-21 17:21 UTC, KakinokiKanta commented on module/API/Measurer.h
> +  Measurer();  // インスタンス化を禁止する
翁長くんがControllerの方で教えてくれたんだけど、コンストラクタを明示的に使用禁止にするのに、publicでコンストラクタにdeleteを代入することがあるらしい。こっちの方が良さそうだから、変更お願いしてもいい？

参考資料
- [C++でstaticクラス](https://sygh.hatenadiary.jp/entry/2018/08/12/010257)
- [明示的なdefault/delete関数](https://yohe.gitbooks.io/cpp-14/content/chapter_1/core/explicit_default_func.html)

2023-05-21 17:21 UTC, KakinokiKanta commented on test/MeasurerTest.cpp
> +  TEST(MeasurerTest, getRawColor)
そもそもAPI呼び出しするだけのMeasurerにテストっているんですかね？なんかダミーのテストをしているように見えるんですけど…

2023-05-21 17:21 UTC, KakinokiKanta commented on module/API/Measurer.cpp
> +}
Controllerの方で話してるんだけど、今年はアーム使わないかもしれないからいらないかも…。まだ決まってないから、とりあえずはこのままで大丈夫。

2023-05-22 01:09 UTC, miyashita64 commented on test/MeasurerTest.cpp
> +  TEST(MeasurerTest, getRawColor)
割と根幹だから、呼び出せるかのテストだけでも意味はあると思う

2023-05-22 01:43 UTC, KakinokiKanta commented on test/MeasurerTest.cpp
> +  TEST(MeasurerTest, getRawColor)
テスト環境だとAPIの呼び出しができないから、ダミーを用意しているって認識なんですけど、ダミーに対するテストが必要ってことですか？

2023-05-22 01:45 UTC, KakinokiKanta commented on module/API/Measurer.cpp
> +}
やっぱり必要ってことになったから、この話は無視してください

2023-05-22 02:03 UTC, miyashita64 commented on test/MeasurerTest.cpp
> +  TEST(MeasurerTest, getRawColor)
Controllerの方で思ったけど、呼び出してエラーなしに実行できるか、そもそも呼び出せるかの確認はあった方がいいと思う。
dummyも仮に作ってるだけではあるけど、ev3api内のやつとある程度同じ作りにはなってるはずだから、意味ないことはないと思う。

2023-05-22 18:40 UTC, KakinokiKanta approved these changes
遅くまでお疲れ様!

2023-05-23 05:39 UTC, miyashita64 reviewed
何度もごめん。
昨日思いつかんかったけど、普通にポインタ使えば書けたかも。期限過ぎてどうこう言うのもなんけど、ポインタでいけそうか確認して行けそうならこっちにして欲しい。

2023-05-23 05:39 UTC, miyashita64 commented on module/API/Measurer.h
> +  static const ePortM armMotorPort = PORT_A;
もしかして↓で動く？
```suggestion
  static ColorSensor* colorSensor;
  static SonarSensor* sonarSensor;
  static Moter* leftWheel;
  static Moter* rightWheel;
  static Moter* armMotor;
```

2023-05-23 05:39 UTC, miyashita64 commented on module/API/Measurer.cpp
> +
もしかして↓で動く？
```suggestion
ColorSensor* Measurer::colorSensor = &ColorSensor(PORT_2);
SonarSensor* Measurer::sonarSensor = &SonarSensor(PORT_3);
Moter* Measurer::leftWheel = &Motor(PORT_C);
Moter* Measurer::rightWheel = &Motor(PORT_B);
Moter* Measurer::armMotor = &Motor(PORT_A);
```

2023-05-23 05:39 UTC, miyashita64 commented on module/API/Measurer.cpp
> +  ev3api::ColorSensor(colorSensorPort).getRawColor(rgb);
もしかして↓で動く？
```suggestion
  Measurer::colorSensor->getRawColor(rgb);
```

以降の「ev3api::〇〇(Measurer::△△Port).xx」も同様に
「Measurer::△△->xx」

2023-05-23 08:34 UTC, miyashita64 approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/209508)

2023-05-24 06:14 UTC, kawanoichi approved these changes
レビュー遅くなってすみません。
![186630](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/assets/96767490/ad63eb20-a853-45d9-98ca-1e03140572a1)

2023-05-24 10:27 UTC, merged